/* ---- 生僻字解释：按经典 id 对应，每条含字/词、读音、释义 ---- */
export interface GlossaryEntry {
  char: string;
  pinyin: string;
  meaning: string;
}

export const ZEN_GLOSSARY: Record<string, GlossaryEntry[]> = {
  tanjing: [
    { char: '薙', pinyin: 'tì', meaning: '剃除，指剃发出家' },
    { char: '獦', pinyin: 'gé', meaning: '獦獠，古时对南方少数民族的贬称' },
    { char: '獠', pinyin: 'liáo', meaning: '同上，獦獠连用' },
    { char: '碓', pinyin: 'duì', meaning: '舂米的器具' },
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈' },
    { char: '阖', pinyin: 'hé', meaning: '全、都' },
    { char: '刹那', pinyin: 'chà nà', meaning: '极短的时间，一瞬间' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，即从生死此岸到达涅槃彼岸' },
    { char: '阿耨多罗三藐三菩提', pinyin: 'ā nòu duō luó sān miǎo sān pú tí', meaning: '无上正等正觉，佛果的智德' },
  ],
  jingangjing: [
    { char: '祇', pinyin: 'qí', meaning: '祇树给孤独园，佛说法处' },
    { char: '衲', pinyin: 'nà', meaning: '僧衣，也指僧人' },
    { char: '恒河沙', pinyin: 'héng hé shā', meaning: '比喻数量极多，如恒河中的沙粒' },
    { char: '须菩提', pinyin: 'xū pú tí', meaning: '佛陀十大弟子之一，解空第一' },
    { char: '阿兰那', pinyin: 'ā lán nà', meaning: '寂静处，修行之所' },
    { char: '筏', pinyin: 'fá', meaning: '竹筏，比喻佛法为渡河工具' },
    { char: '诃', pinyin: 'hē', meaning: '呵斥、责备' },
  ],
  xinjing: [
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜多', pinyin: 'bō luó mì duō', meaning: '到彼岸，超越生死到达涅槃' },
    { char: '羯谛', pinyin: 'jié dì', meaning: '咒语，意为"去"——超越生死' },
    { char: '僧羯谛', pinyin: 'sēng jié dì', meaning: '咒语，意为"完全去"——究竟超越' },
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '萨婆诃', pinyin: 'sà pó hē', meaning: '咒语结语，意为"成就"' },
  ],
  yuanjuejing: [
    { char: '骛', pinyin: 'wù', meaning: '追求、追逐' },
    { char: '棼', pinyin: 'fén', meaning: '纷乱、交错' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、障蔽' },
    { char: '幻', pinyin: 'huàn', meaning: '虚幻不实，如幻术' },
    { char: '奢摩他', pinyin: 'shē mó tā', meaning: '止，禅定的第一阶段——心专注一境' },
    { char: '三摩钵提', pinyin: 'sān mó bō tí', meaning: '观，禅定的第二阶段——于定中起观' },
    { char: '禅那', pinyin: 'chán nà', meaning: '静虑，禅定的第三阶段——止观双运' },
    { char: '陀罗尼', pinyin: 'tuó luó ní', meaning: '总持，能持集无量善法、遮止恶法' },
  ],
  lengyanjing: [
    { char: '洎', pinyin: 'jì', meaning: '及、到' },
    { char: '麈', pinyin: 'zhǔ', meaning: '鹿类，尾毛可做拂尘；麈尾即说法时所用拂尘' },
    { char: '殒', pinyin: 'yǔn', meaning: '死亡、坠落' },
    { char: '抟', pinyin: 'tuán', meaning: '把东西揉成球形' },
    { char: '醐', pinyin: 'hú', meaning: '醍醐，酥酪提炼出的最精纯之物，喻佛果' },
    { char: '醍', pinyin: 'tí', meaning: '同上，醍醐连用' },
    { char: '阿難', pinyin: 'ā nán', meaning: '佛陀堂弟，多闻第一' },
    { char: '摩登伽', pinyin: 'mó dēng jiā', meaning: '低种姓女子，以咒术迷惑阿难' },
    { char: '毘', pinyin: 'pí', meaning: '同"毗"，相近、相邻' },
    { char: '楞严', pinyin: 'léng yán', meaning: '一切事究竟坚固，此经名' },
  ],
  weimojiejing: [
    { char: '维摩诘', pinyin: 'wéi mó jié', meaning: '在家菩萨，意为"净名"——清净无垢' },
    { char: '毘耶离', pinyin: 'pí yē lí', meaning: '古印度城名，维摩诘居住之地' },
    { char: '殁', pinyin: 'mò', meaning: '死亡' },
    { char: '诃', pinyin: 'hē', meaning: '呵斥、责备' },
    { char: '寤', pinyin: 'wù', meaning: '醒悟、觉醒' },
    { char: '筌', pinyin: 'quán', meaning: '捕鱼竹器，比喻言教为得鱼之工具' },
    { char: '蹄', pinyin: 'tí', meaning: '捕兔网，与"筌"同喻工具' },
    { char: '阿閦佛', pinyin: 'ā chù fó', meaning: '东方不动佛，意为"不动"' },
    { char: '殃', pinyin: 'yāng', meaning: '灾祸' },
    { char: '缶', pinyin: 'fǒu', meaning: '瓦器，盛酒浆的陶器' },
  ],
  xinxinming: [
    { char: '至道', pinyin: 'zhì dào', meaning: '最高的道，指佛道、真如' },
    { char: '憎爱', pinyin: 'zēng ài', meaning: '厌恶与贪爱，一切烦恼的根源' },
    { char: '洞然', pinyin: 'dòng rán', meaning: '清楚明白的样子' },
    { char: '泯', pinyin: 'mǐn', meaning: '消灭、消除' },
    { char: '毫厘', pinyin: 'háo lí', meaning: '极微小的差别' },
    { char: '差', pinyin: 'cī', meaning: '差别、不同（读cī时不作"错误"解）' },
  ],
  zhengdaoge: [
    { char: '兀', pinyin: 'wù', meaning: '高耸特立的样子' },
    { char: '迥', pinyin: 'jiǒng', meaning: '远、差得远' },
    { char: '澄', pinyin: 'chéng', meaning: '水静而清' },
    { char: '皎', pinyin: 'jiǎo', meaning: '洁白明亮' },
    { char: '渊', pinyin: 'yuān', meaning: '深水、深潭' },
  ],
  shiniutu: [
    { char: '廛', pinyin: 'chán', meaning: '市集、店铺集中的街道；入廛即入市井' },
    { char: '跣', pinyin: 'xiǎn', meaning: '赤脚、光脚' },
    { char: '迤逦', pinyin: 'yǐ lǐ', meaning: '曲折连绵、缓缓行走的样子' },
    { char: '羌笛', pinyin: 'qiāng dí', meaning: '古代西北少数民族的管乐器' },
    { char: '懡㦬', pinyin: 'mǒ luǒ', meaning: '羞愧、惭愧的样子' },
    { char: '廓庵', pinyin: 'kuò ān', meaning: '禅师号，南宋临济宗杨岐派' },
    { char: '威音劫', pinyin: 'wēi yīn jié', meaning: '最古远的劫名，指天地未分之前的绝对时间' },
    { char: '筌鱼', pinyin: 'quán yú', meaning: '筌为捕鱼工具，喻言教为工具' },
    { char: '蹄兔', pinyin: 'tí tù', meaning: '蹄为捕兔网，喻与筌同' },
  ],
  chanlinbaoxun: [
    { char: '衲子', pinyin: 'nà zǐ', meaning: '僧人，穿衲衣者' },
    { char: '苞苴', pinyin: 'bāo jū', meaning: '贿赂、馈赠之物' },
    { char: '砭', pinyin: 'biān', meaning: '古代治病的石针，引申为规劝、救治' },
    { char: '褫', pinyin: 'chǐ', meaning: '剥夺、脱去' },
    { char: '谮', pinyin: 'zèn', meaning: '诬陷、中伤' },
    { char: '刍', pinyin: 'chú', meaning: '割草、草料' },
    { char: '舂', pinyin: 'chōng', meaning: '用杵臼捣谷物去壳' },
    { char: '爨', pinyin: 'cuàn', meaning: '烧火做饭' },
    { char: '恣', pinyin: 'zì', meaning: '放纵、无拘束' },
    { char: '谧', pinyin: 'mì', meaning: '安静、静默' },
  ],
  qifo: [
    { char: '毗婆尸', pinyin: 'pí pó shī', meaning: '过去七佛之第一佛，意为"胜观"' },
    { char: '尸弃', pinyin: 'shī qì', meaning: '过去七佛之第二佛，意为"最上"' },
    { char: '毗舍浮', pinyin: 'pí shè fú', meaning: '过去七佛之第三佛，意为"一切胜"' },
    { char: '拘留孙', pinyin: 'jū liú sūn', meaning: '过去七佛之第四佛' },
    { char: '拘那含牟尼', pinyin: 'jū nà hán móu ní', meaning: '过去七佛之第五佛，意为"金寂"' },
    { char: '迦叶', pinyin: 'jiā shè', meaning: '过去七佛之第六佛，亦指佛陀大弟子' },
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈' },
    { char: '聚沫', pinyin: 'jù mò', meaning: '聚集的水泡，比喻身体虚幻不实' },
    { char: '正法眼藏', pinyin: 'zhèng fǎ yǎn zàng', meaning: '禅宗指佛陀心传的究竟法门' },
  ],
  juelin: [
    { char: '觉林', pinyin: 'jué lín', meaning: '菩萨名，出自《华严经》' },
    { char: '大种', pinyin: 'dà zhǒng', meaning: '地水火风四大元素' },
    { char: '五蕴', pinyin: 'wǔ yùn', meaning: '色受想行识，构成身心的五种要素' },
    { char: '法界', pinyin: 'fǎ jiè', meaning: '一切法的总汇，宇宙万有的整体' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '舍利弗', pinyin: 'shè lì fú', meaning: '佛陀十大弟子之一，智慧第一' },
  ],
  wenshu: [
    { char: '文殊师利', pinyin: 'wén shū shī lì', meaning: '大智菩萨，智慧第一的菩萨' },
    { char: '摩诃般若', pinyin: 'mó hē bō rě', meaning: '大智慧，通达诸法实相的究竟智慧' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '法界', pinyin: 'fǎ jiè', meaning: '一切法的总汇，宇宙万有的整体' },
    { char: '舍利弗', pinyin: 'shè lì fú', meaning: '佛陀十大弟子之一，智慧第一' },
    { char: '曼陀罗仙', pinyin: 'màn tuó luó xiān', meaning: '梁代译经僧，译出《文殊说般若经》' },
  ],
  wuran: [
    { char: '莲花生', pinyin: 'lián huā shēng', meaning: '藏传佛教宁玛派祖师' },
    { char: '觉性', pinyin: 'jué xìng', meaning: '本觉之性，众生本具的灵知灵觉' },
    { char: '三味耶', pinyin: 'sān mèi yē', meaning: '密宗誓约、印契' },
    { char: '娑婆', pinyin: 'suō pó', meaning: '堪忍世界，即我们所在的现实世间' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '轮回', pinyin: 'lún huí', meaning: '众生在六道中生死流转不已' },
    { char: '声闻', pinyin: 'shēng wén', meaning: '听闻佛法而悟道者，修四谛法' },
    { char: '缘觉', pinyin: 'yuán jué', meaning: '观十二因缘而自行悟道者' },
    { char: '中观', pinyin: 'zhōng guān', meaning: '龙树所创学派，离空有二边之中道' },
    { char: '瑜珈', pinyin: 'yú jiā', meaning: '相应、结合，密宗修法之一' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉、愚痴，一切烦恼的根本' },
  ],
  zhangzhi: [
    { char: '兰若', pinyin: 'lán rě', meaning: '阿兰若的简称，寂静处、寺院' },
    { char: '曼达', pinyin: 'màn dá', meaning: '密宗供养法器，象征宇宙供养' },
    { char: '明觉', pinyin: 'míng jué', meaning: '清明觉知，本觉的灵知作用' },
    { char: '空性', pinyin: 'kōng xìng', meaning: '一切法无自性的本质' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '常见', pinyin: 'cháng jiàn', meaning: '执着万法恒常不变的错误见解' },
    { char: '断见', pinyin: 'duàn jiàn', meaning: '执着万法断灭归无的错误见解' },
  ],
  xuemaicong: [
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '三界', pinyin: 'sān jiè', meaning: '欲界、色界、无色界，众生生死轮回的范围' },
    { char: '旷大劫', pinyin: 'kuàng dà jié', meaning: '极漫长的时间，无数亿年' },
    { char: '驰求', pinyin: 'chí qiú', meaning: '向外奔走追求，指心向外攀缘' },
    { char: '十二部经', pinyin: 'shí èr bù jīng', meaning: '佛经的十二种分类体裁' },
    { char: '善星比丘', pinyin: 'shàn xīng bǐ qiū', meaning: '佛经中虽诵十二部经却不见性而轮回的人物' },
    { char: '皂白', pinyin: 'zào bái', meaning: '黑白，比喻是非善恶' },
    { char: '无间地狱', pinyin: 'wú jiān dì yù', meaning: '受苦无间断的地狱，最苦之处' },
  ],
  wuxinglun: [
    { char: '寂照', pinyin: 'jì zhào', meaning: '寂而常照、照而常寂，定慧一体的境界' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '转第八识所成之智，如大圆镜映现万法' },
    { char: '无念', pinyin: 'wú niàn', meaning: '不执着妄念，非无心如木石' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
  ],
  poxianglun: [
    { char: '六度', pinyin: 'liù dù', meaning: '布施、持戒、忍辱、精进、禅定、般若六种修行' },
    { char: '名相', pinyin: 'míng xiàng', meaning: '事物的名称和表相，非实相本体' },
    { char: '伽蓝', pinyin: 'qié lán', meaning: '寺院，僧伽蓝摩的简称' },
    { char: '塔庙', pinyin: 'tǎ miào', meaning: '供奉佛舍利或经像的建筑' },
    { char: '持犯', pinyin: 'chí fàn', meaning: '持戒与犯戒' },
    { char: '福田', pinyin: 'fú tián', meaning: '种福之田，比喻供养布施能生福报' },
  ],
  wuxinlun: [
    { char: '无心', pinyin: 'wú xīn', meaning: '无妄心，非无真心；不起执着分别' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '妄心', pinyin: 'wàng xīn', meaning: '虚妄分别之心，执着外境之念' },
    { char: '真心', pinyin: 'zhēn xīn', meaning: '本来自性清净之心' },
  ],
  xixulun: [
    { char: '无生法忍', pinyin: 'wú shēng fǎ rěn', meaning: '忍可诸法本自无生之真理' },
    { char: '狂心', pinyin: 'kuáng xīn', meaning: '狂乱的妄想心，歇下即菩提' },
    { char: '顿悟', pinyin: 'dùn wù', meaning: '顿时悟入本来实相' },
  ],
  sixingguan: [
    { char: '报冤行', pinyin: 'bào yuān xíng', meaning: '逢苦不怨，认旧业而不报新怨' },
    { char: '随缘行', pinyin: 'suí yuán xíng', meaning: '苦乐随缘，得失不动' },
    { char: '无所求行', pinyin: 'wú suǒ qiú xíng', meaning: '万有皆空，无所贪求' },
    { char: '称法行', pinyin: 'chēng fǎ xíng', meaning: '称合清净法性而行六度' },
    { char: '理入', pinyin: 'lǐ rù', meaning: '藉教悟宗，深信含生同一真性' },
    { char: '行入', pinyin: 'xíng rù', meaning: '四行实践，于日常中磨炼心性' },
  ],
  fangcunlun: [
    { char: '方寸', pinyin: 'fāng cùn', meaning: '心，古人以方寸之地喻心' },
    { char: '须弥', pinyin: 'xū mí', meaning: '须弥山，佛教宇宙观中的世界中心' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '缘木求鱼', pinyin: 'yuán mù qiú yú', meaning: '爬到树上去找鱼，比喻方向错误徒劳无功' },
    { char: '中道', pinyin: 'zhōng dào', meaning: '离空有二边的不二之道' },
    { char: '灵山', pinyin: 'líng shān', meaning: '灵鹫山，佛说法处；亦指自心清净处' },
  ],
  anxin: [
    { char: '蕲州', pinyin: 'qí zhōu', meaning: '古地名，今湖北蕲春一带' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '楞伽经', pinyin: 'léng qié jīng', meaning: '禅宗所依经典，以佛语心为宗' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '实相', pinyin: 'shí xiàng', meaning: '万法的真实本相，即空性' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '泯然', pinyin: 'mǐn rán', meaning: '消融、消失的样子' },
  ],
  zuishangcheng: [
    { char: '金刚佛性', pinyin: 'jīn gāng fó xìng', meaning: '坚固不坏、能破一切的佛性' },
    { char: '五阴', pinyin: 'wǔ yīn', meaning: '即五蕴：色受想行识' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '三涂', pinyin: 'sān tú', meaning: '地狱、饿鬼、畜生三恶道' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '凝然', pinyin: 'níng rán', meaning: '安定不动摇的样子' },
    { char: '守心', pinyin: 'shǒu xīn', meaning: '守护本心不令散乱，五祖弘忍的核心教法' },
  ],
  mazu: [
    { char: '什邡', pinyin: 'shí fāng', meaning: '古地名，今四川什邡市，马祖故里' },
    { char: '醍醐', pinyin: 'tí hú', meaning: '酥酪提炼出的最精纯之物，喻最上法味' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '般若多罗', pinyin: 'bō rě duō luó', meaning: '达摩之师，西天第二十七祖' },
    { char: '蹋', pinyin: 'tà', meaning: '踩、踏' },
    { char: '谄曲', pinyin: 'chǎn qū', meaning: '谄媚歪曲，不正直' },
    { char: '海印三昧', pinyin: 'hǎi yìn sān mèi', meaning: '如大海映现万象的三昧境界' },
    { char: '声闻', pinyin: 'shēng wén', meaning: '听闻佛法而悟道者，修四谛法' },
    { char: '法性', pinyin: 'fǎ xìng', meaning: '万法的本性，即空性、真如' },
    { char: '恒沙', pinyin: 'héng shā', meaning: '恒河沙，比喻数量极多' },
  ],
  baizhang: [
    { char: '怀海', pinyin: 'huái hǎi', meaning: '百丈禅师名，马祖道一的法嗣' },
    { char: '该练', pinyin: 'gāi liàn', meaning: '全面通达、熟习' },
    { char: '寮', pinyin: 'liáo', meaning: '僧人住的房间' },
    { char: '罔然', pinyin: 'wǎng rán', meaning: '茫然、不知所措的样子' },
    { char: '拂子', pinyin: 'fú zǐ', meaning: '拂尘，禅师说法时手持的器具' },
    { char: '岩峦', pinyin: 'yán luán', meaning: '山峰、山峦' },
    { char: '蘑至', pinyin: 'mó zhì', meaning: '纷纷到来' },
    { char: '不昧因果', pinyin: 'bù mèi yīn guǒ', meaning: '不蒙蔽因果，悟者仍在因果中但不被蒙蔽' },
    { char: '迥脱', pinyin: 'jiǒng tuō', meaning: '迥然超脱，彻底超越' },
    { char: '根尘', pinyin: 'gēn chén', meaning: '六根（眼耳鼻舌身意）与六尘（色声香味触法）' },
  ],
  huangbo: [
    { char: '希运', pinyin: 'xī yùn', meaning: '黄檗禅师名，临济义玄之师' },
    { char: '鹫峰', pinyin: 'jiù fēng', meaning: '灵鹫山，黄檗山所在' },
    { char: '嫡孙', pinyin: 'dí sūn', meaning: '正宗法孙，直系传人' },
    { char: '裴休', pinyin: 'péi xiū', meaning: '唐代宰相，黄檗禅师俗家弟子，记录《传心法要》' },
    { char: '纤埃', pinyin: 'xiān āi', meaning: '极微小的尘埃' },
    { char: '乖', pinyin: 'guāi', meaning: '违背、背离' },
    { char: '蠢动含灵', pinyin: 'chǔn dòng hán líng', meaning: '一切有知觉的生命，从人到微小虫类' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '如如', pinyin: 'rú rú', meaning: '真如之体，本来如是、不生不灭' },
  ],
  xiuxinjue: [
    { char: '热恼', pinyin: 'rè nǎo', meaning: '炽热的烦恼，如火灼身' },
    { char: '火宅', pinyin: 'huǒ zhái', meaning: '比喻三界生死充满众苦，如着火的房屋' },
    { char: '无漏', pinyin: 'wú lòu', meaning: '没有烦恼漏失的清净法' },
    { char: '顿悟', pinyin: 'dùn wù', meaning: '顿时悟入本来实相' },
    { char: '渐修', pinyin: 'jiàn xiū', meaning: '循序渐进地修行，逐步除习气' },
    { char: '习气', pinyin: 'xí qì', meaning: '多生多世积累的烦恼惯势' },
    { char: '蒸沙作饭', pinyin: 'zhēng shā zuò fàn', meaning: '蒸沙子想做成饭，比喻方法错误徒劳无功' },
  ],
  linji: [
    { char: '无位真人', pinyin: 'wú wèi zhēn rén', meaning: '临济宗核心概念，超越一切名位框架的本来自性' },
    { char: '干屎橛', pinyin: 'gān shǐ jué', meaning: '干粪块，禅师用以截断学人分别心的峻烈话头' },
    { char: '赤肉团', pinyin: 'chì ròu tuán', meaning: '血肉之躯，指人的身体' },
    { char: '面门', pinyin: 'miàn mén', meaning: '面部，指眼耳鼻舌等感官' },
    { char: '精魅', pinyin: 'jīng mèi', meaning: '妖精鬼怪，比喻迷惑学人的邪见' },
    { char: '凑泊', pinyin: 'còu bó', meaning: '凑近、靠拢，指心向外攀缘执着' },
    { char: '五无间业', pinyin: 'wǔ wú jiàn yè', meaning: '五种必堕无间地狱的重罪' },
    { char: '驰求', pinyin: 'chí qiú', meaning: '向外奔走追求，指心向外攀缘' },
    { char: '逢着便杀', pinyin: 'féng zhe biàn shā', meaning: '遇佛杀佛遇祖杀祖，比喻彻底放下一切执着' },
  ],
  dunwu: [
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '以头触地行礼，佛教最敬礼' },
    { char: '和南', pinyin: 'hé nán', meaning: '佛教礼敬语，即顶礼' },
    { char: '有情', pinyin: 'yǒu qíng', meaning: '一切有情感知觉的众生' },
    { char: '八风', pinyin: 'bā fēng', meaning: '利衰毁誉称讥苦乐，八种能动摇人心的境界' },
    { char: '无生心', pinyin: 'wú shēng xīn', meaning: '不生妄念的清净心' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '无住', pinyin: 'wú zhù', meaning: '心不执着于任何一处' },
  ],
  zhenxin: [
    { char: '真心', pinyin: 'zhēn xīn', meaning: '本来自性清净之心' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '转第八识所成之智，如大圆镜映现万法' },
    { char: '六尘', pinyin: 'liù chén', meaning: '色声香味触法六种外境' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉、愚痴，一切烦恼的根本' },
    { char: '法身', pinyin: 'fǎ shēn', meaning: '以空为体的佛身，无形无相' },
    { char: '威仪', pinyin: 'wēi yí', meaning: '行住坐卧四种姿态，僧人举止规范' },
  ],
  zhigong: [
    { char: '宝志', pinyin: 'bǎo zhì', meaning: '梁代高僧，又称志公，以神通异行著称' },
    { char: '骑驴觅驴', pinyin: 'qí lǘ mì lǘ', meaning: '骑着驴找驴，比喻本已具足却向外驰求' },
    { char: '波旬', pinyin: 'bō xún', meaning: '魔王名，常干扰修行人' },
    { char: '泥盘', pinyin: 'ní pán', meaning: '同涅槃，烦恼熄灭的解脱境界' },
    { char: '大乘', pinyin: 'dà chéng', meaning: '能载众人至彼岸的佛法，以利他为宗' },
  ],
  xinwangming: [
    { char: '心王', pinyin: 'xīn wáng', meaning: '心之主体，统率诸心所，比喻自性真心' },
    { char: '胶青', pinyin: 'jiāo qīng', meaning: '胶质，比喻真心存在而不可见其形' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '六道', pinyin: 'liù dào', meaning: '天、人、阿修罗、地狱、饿鬼、畜生六种轮回境界' },
  ],
  shenhui: [
    { char: '无念', pinyin: 'wú niàn', meaning: '不执着妄念，非无心如木石' },
    { char: '真空', pinyin: 'zhēn kōng', meaning: '非断灭之空，而是含摄万法的真实空性' },
    { char: '妙有', pinyin: 'miào yǒu', meaning: '从空性中显现的妙用，非实有之有' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '二乘', pinyin: 'èr chéng', meaning: '声闻乘与缘觉乘，修自了生死者' },
    { char: '断常', pinyin: 'duàn cháng', meaning: '断见与常见，两种边见' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '系缚', pinyin: 'xì fù', meaning: '被烦恼捆绑，不得自在' },
    { char: '荷泽', pinyin: 'hé zé', meaning: '神会大师的宗派名，荷泽宗' },
  ],
  baojingsanmei: [
    { char: '盌', pinyin: 'wǎn', meaning: '同"碗"，盛器。银盌盛雪，喻本体与现象浑然难辨' },
    { char: '鹭', pinyin: 'lù', meaning: '鹭鸟，羽毛洁白。明月藏鹭，喻法界一相、理事交融' },
    { char: '窠臼', pinyin: 'kē jiù', meaning: '旧格式、陈套。动成窠臼，谓一动言说便落俗套' },
    { char: '顾伫', pinyin: 'gù zhù', meaning: '迟疑徘徊。差落顾伫，谓稍有迟疑便失机锋' },
    { char: '荎', pinyin: 'tí', meaning: '荎草，一种五味草。如荎草味，喻五味和合、偏正交融' },
    { char: '馵', pinyin: 'zhù', meaning: '马左后足白。如马之馵，喻不纯、有偏' },
    { char: '貍奴', pinyin: 'lí nú', meaning: '猫。貍奴白牯，喻以平常之物接引惊异根器者' },
    { char: '缁', pinyin: 'zī', meaning: '黑色。以缁为素，谓黑白颠倒、以邪为正' },
    { char: '檀度', pinyin: 'tán dù', meaning: '布施波罗蜜，六度之首。为法檀度，谓为法建立度门' },
    { char: '鞔鞔', pinyin: 'mán mán', meaning: '网罗密布貌。金锁网鞔鞔，喻修行不力则如披枷带锁' },
    { char: '渗漏', pinyin: 'shèn lòu', meaning: '三种修行偏差：见渗漏、情渗漏、语渗漏' },
    { char: '回互', pinyin: 'huí hù', meaning: '曹洞宗核心概念，指体用、偏正、理事相互含摄转化' },
    { char: '主中主', pinyin: 'zhǔ zhōng zhǔ', meaning: '曹洞四宾主最高位，超越宾主、不涉正偏的绝对境界' },
  ],
  dongshanyulu: [
    { char: '溈山', pinyin: 'wéi shān', meaning: '沩山灵祐禅师，洞山曾参之。沩仰宗开山祖师' },
    { char: '云岩', pinyin: 'yún yán', meaning: '云岩昙晟禅师，洞山得法师父，药山惟俨法嗣' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语，意为轨范师，对僧人的尊称' },
    { char: '五位', pinyin: 'wǔ wèi', meaning: '曹洞宗纲宗：正中偏、偏中正、正中来、兼中至、兼中到' },
    { char: '功勋五位', pinyin: 'gōng xūn wǔ wèi', meaning: '向、奉、功、共功、功功——从发心到究竟的修证次第' },
    { char: '鸟道', pinyin: 'niǎo dào', meaning: '洞山三路之一，空中鸟迹无迹可寻，喻心空行无迹' },
    { char: '玄路', pinyin: 'xuán lù', meaning: '洞山三路之一，识偏正回互之路，接中下根器' },
    { char: '展手', pinyin: 'zhǎn shǒu', meaning: '洞山三路之一，当下便了，接上根利智' },
    { char: '乾慧', pinyin: 'qián huì', meaning: '有慧无定之空头智慧，末法时代人之通病' },
    { char: '粟畬', pinyin: 'sù yú', meaning: '烧荒种田处。洞山答僧"向甚处去"云"粟畬里去"' },
    { char: '㳂流', pinyin: 'yán liú', meaning: '沿流、顺流而下。洞山答兴平云"㳂流无定止"' },
    { char: '曹洞宗', pinyin: 'cáo dòng zōng', meaning: '洞山良价与曹山本寂共创之禅宗五家之一，以偏正回互、绵密宗风著称' },
  ],
  yongjia: [
    { char: '玄觉', pinyin: 'xuán jué', meaning: '永嘉大师法名，谥真觉大师，人称"一宿觉"' },
    { char: '一宿觉', pinyin: 'yī xiǔ jué', meaning: '永嘉参六祖，一宿之间言下大悟，故得此号' },
    { char: '奢摩他', pinyin: 'shē mó tā', meaning: '梵语，意为"止"，禅定之异名，令心住于一境' },
    { char: '毗婆舍那', pinyin: 'pí pó shě nà', meaning: '梵语，意为"观"，以智慧观照诸法实相' },
    { char: '优毕叉', pinyin: 'yōu bì chā', meaning: '梵语，意为"止观等持"，定慧平等之中道' },
    { char: '四宏誓愿', pinyin: 'sì hóng shì yuàn', meaning: '众生无边誓愿度，烦恼无数誓愿断，法门无量誓愿学，佛道无上誓愿成' },
    { char: '三谛', pinyin: 'sān dì', meaning: '天台宗核心：真谛（空）、俗谛（假）、中谛（中道）' },
    { char: '三乘', pinyin: 'sān shèng', meaning: '声闻乘、缘觉乘、菩萨乘，三种修行阶位' },
    { char: '黄门', pinyin: 'huáng mén', meaning: '古指阉人，发愿文中指不愿生为残缺之身' },
    { char: '曹溪', pinyin: 'cáo xī', meaning: '广东韶关曹溪，六祖惠能道场所在地，代指南宗禅' },
  ],
  yunmen: [
    { char: '文偃', pinyin: 'wén yǎn', meaning: '云门大师法名，五代高僧，云门宗开山祖师' },
    { char: '睦州', pinyin: 'mù zhōu', meaning: '睦州道明禅师，黄檗法嗣，云门初参之师，机辩峭捷' },
    { char: '乾屎橛', pinyin: 'gān shǐ jué', meaning: '拭粪之竹片。云门答"如何是佛"云"乾屎橛"，以秽语破名相执' },
    { char: '函盖乾坤', pinyin: 'hán gài qián kūn', meaning: '云门三句之一：万法皆真，物物全真，天地万法尽在一句中' },
    { char: '截断众流', pinyin: 'jié duàn zhòng liú', meaning: '云门三句之一：斩断妄想之流，言语道断，心行处灭' },
    { char: '随波逐浪', pinyin: 'suí bō zhú làng', meaning: '云门三句之一：随学人根机接引，应病与药，灵活无碍' },
    { char: '掠虚汉', pinyin: 'lüè xū hàn', meaning: '云门斥语，指记言抄语、依葫芦画瓢而无实悟之徒' },
    { char: '秦时轹钻', pinyin: 'qín shí lì zuān', meaning: '睦州勘云门之语。秦时之钻，钝而无用，截断学人思量' },
    { char: '灵树', pinyin: 'líng shù', meaning: '灵树如敏禅师道场，云门初为首座之处，在广东韶州' },
    { char: '苏噜苏噜', pinyin: 'sū lǔ sū lǔ', meaning: '云门答话惯用语，象声词，截断问头，不落言诠' },
    { char: '髫龀', pinyin: 'tiáo chèn', meaning: '童年。云门"才自髫龀，志尚率己厌俗"' },
  ],
};
