/* ---- 生僻字解释：按经典 id 对应，每条含字/词、读音、释义 ---- */
export interface GlossaryEntry {
  char: string;
  pinyin: string;
  meaning: string;
}

export const ZEN_GLOSSARY: Record<string, GlossaryEntry[]> = {
  tanjing: [
    { char: '薙', pinyin: 'tì', meaning: '剃除，指剃发出家' },
    { char: '獦', pinyin: 'gé', meaning: '獦獠，古时对南方少数民族的贬称' },
    { char: '獠', pinyin: 'liáo', meaning: '同上，獦獠连用' },
    { char: '碓', pinyin: 'duì', meaning: '舂米的器具' },
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈' },
    { char: '阖', pinyin: 'hé', meaning: '全、都' },
    { char: '刹那', pinyin: 'chà nà', meaning: '极短的时间，一瞬间' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，即从生死此岸到达涅槃彼岸' },
    { char: '阿耨多罗三藐三菩提', pinyin: 'ā nòu duō luó sān miǎo sān pú tí', meaning: '无上正等正觉，佛果的智德' },
  ],
  jingangjing: [
    { char: '祇', pinyin: 'qí', meaning: '祇树给孤独园，佛说法处' },
    { char: '衲', pinyin: 'nà', meaning: '僧衣，也指僧人' },
    { char: '恒河沙', pinyin: 'héng hé shā', meaning: '比喻数量极多，如恒河中的沙粒' },
    { char: '须菩提', pinyin: 'xū pú tí', meaning: '佛陀十大弟子之一，解空第一' },
    { char: '阿兰那', pinyin: 'ā lán nà', meaning: '寂静处，修行之所' },
    { char: '筏', pinyin: 'fá', meaning: '竹筏，比喻佛法为渡河工具' },
    { char: '诃', pinyin: 'hē', meaning: '呵斥、责备' },
  ],
  xinjing: [
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜多', pinyin: 'bō luó mì duō', meaning: '到彼岸，超越生死到达涅槃' },
    { char: '羯谛', pinyin: 'jié dì', meaning: '咒语，意为"去"——超越生死' },
    { char: '僧羯谛', pinyin: 'sēng jié dì', meaning: '咒语，意为"完全去"——究竟超越' },
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '萨婆诃', pinyin: 'sà pó hē', meaning: '咒语结语，意为"成就"' },
  ],
  yuanjuejing: [
    { char: '骛', pinyin: 'wù', meaning: '追求、追逐' },
    { char: '棼', pinyin: 'fén', meaning: '纷乱、交错' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、障蔽' },
    { char: '幻', pinyin: 'huàn', meaning: '虚幻不实，如幻术' },
    { char: '奢摩他', pinyin: 'shē mó tā', meaning: '止，禅定的第一阶段——心专注一境' },
    { char: '三摩钵提', pinyin: 'sān mó bō tí', meaning: '观，禅定的第二阶段——于定中起观' },
    { char: '禅那', pinyin: 'chán nà', meaning: '静虑，禅定的第三阶段——止观双运' },
    { char: '陀罗尼', pinyin: 'tuó luó ní', meaning: '总持，能持集无量善法、遮止恶法' },
  ],
  lengyanjing: [
    { char: '洎', pinyin: 'jì', meaning: '及、到' },
    { char: '麈', pinyin: 'zhǔ', meaning: '鹿类，尾毛可做拂尘；麈尾即说法时所用拂尘' },
    { char: '殒', pinyin: 'yǔn', meaning: '死亡、坠落' },
    { char: '抟', pinyin: 'tuán', meaning: '把东西揉成球形' },
    { char: '醐', pinyin: 'hú', meaning: '醍醐，酥酪提炼出的最精纯之物，喻佛果' },
    { char: '醍', pinyin: 'tí', meaning: '同上，醍醐连用' },
    { char: '阿难', pinyin: 'ā nán', meaning: '佛陀堂弟，多闻第一' },
    { char: '摩登伽', pinyin: 'mó dēng jiā', meaning: '低种姓女子，以咒术迷惑阿难' },
    { char: '毘', pinyin: 'pí', meaning: '同"毗"，相近、相邻' },
    { char: '楞严', pinyin: 'léng yán', meaning: '一切事究竟坚固，此经名' },
  ],
  weimojiejing: [
    { char: '维摩诘', pinyin: 'wéi mó jié', meaning: '在家菩萨，意为"净名"——清净无垢' },
    { char: '毘耶离', pinyin: 'pí yē lí', meaning: '古印度城名，维摩诘居住之地' },
    { char: '殁', pinyin: 'mò', meaning: '死亡' },
    { char: '诃', pinyin: 'hē', meaning: '呵斥、责备' },
    { char: '寤', pinyin: 'wù', meaning: '醒悟、觉醒' },
    { char: '筌', pinyin: 'quán', meaning: '捕鱼竹器，比喻言教为得鱼之工具' },
    { char: '蹄', pinyin: 'tí', meaning: '捕兔网，与"筌"同喻工具' },
    { char: '阿閦佛', pinyin: 'ā chù fó', meaning: '东方不动佛，意为"不动"' },
    { char: '殃', pinyin: 'yāng', meaning: '灾祸' },
    { char: '缶', pinyin: 'fǒu', meaning: '瓦器，盛酒浆的陶器' },
  ],
  xinxinming: [
    { char: '至道', pinyin: 'zhì dào', meaning: '最高的道，指佛道、真如' },
    { char: '憎爱', pinyin: 'zēng ài', meaning: '厌恶与贪爱，一切烦恼的根源' },
    { char: '洞然', pinyin: 'dòng rán', meaning: '清楚明白的样子' },
    { char: '泯', pinyin: 'mǐn', meaning: '消灭、消除' },
    { char: '毫厘', pinyin: 'háo lí', meaning: '极微小的差别' },
    { char: '差', pinyin: 'cī', meaning: '差别、不同（读cī时不作"错误"解）' },
  ],
  zhengdaoge: [
    { char: '兀', pinyin: 'wù', meaning: '高耸特立的样子' },
    { char: '迥', pinyin: 'jiǒng', meaning: '远、差得远' },
    { char: '澄', pinyin: 'chéng', meaning: '水静而清' },
    { char: '皎', pinyin: 'jiǎo', meaning: '洁白明亮' },
    { char: '渊', pinyin: 'yuān', meaning: '深水、深潭' },
  ],
  shiniutu: [
    { char: '廛', pinyin: 'chán', meaning: '市集、店铺集中的街道；入廛即入市井' },
    { char: '跣', pinyin: 'xiǎn', meaning: '赤脚、光脚' },
    { char: '迤逦', pinyin: 'yǐ lǐ', meaning: '曲折连绵、缓缓行走的样子' },
    { char: '羌笛', pinyin: 'qiāng dí', meaning: '古代西北少数民族的管乐器' },
    { char: '懡㦬', pinyin: 'mǒ luǒ', meaning: '羞愧、惭愧的样子' },
    { char: '廓庵', pinyin: 'kuò ān', meaning: '禅师号，南宋临济宗杨岐派' },
    { char: '威音劫', pinyin: 'wēi yīn jié', meaning: '最古远的劫名，指天地未分之前的绝对时间' },
    { char: '筌鱼', pinyin: 'quán yú', meaning: '筌为捕鱼工具，喻言教为工具' },
    { char: '蹄兔', pinyin: 'tí tù', meaning: '蹄为捕兔网，喻与筌同' },
  ],
  chanlinbaoxun: [
    { char: '衲子', pinyin: 'nà zǐ', meaning: '僧人，穿衲衣者' },
    { char: '苞苴', pinyin: 'bāo jū', meaning: '贿赂、馈赠之物' },
    { char: '砭', pinyin: 'biān', meaning: '古代治病的石针，引申为规劝、救治' },
    { char: '褫', pinyin: 'chǐ', meaning: '剥夺、脱去' },
    { char: '谮', pinyin: 'zèn', meaning: '诬陷、中伤' },
    { char: '刍', pinyin: 'chú', meaning: '割草、草料' },
    { char: '舂', pinyin: 'chōng', meaning: '用杵臼捣谷物去壳' },
    { char: '爨', pinyin: 'cuàn', meaning: '烧火做饭' },
    { char: '恣', pinyin: 'zì', meaning: '放纵、无拘束' },
    { char: '谧', pinyin: 'mì', meaning: '安静、静默' },
  ],
  qifo: [
    { char: '毗婆尸', pinyin: 'pí pó shī', meaning: '过去七佛之第一佛，意为"胜观"' },
    { char: '尸弃', pinyin: 'shī qì', meaning: '过去七佛之第二佛，意为"最上"' },
    { char: '毗舍浮', pinyin: 'pí shè fú', meaning: '过去七佛之第三佛，意为"一切胜"' },
    { char: '拘留孙', pinyin: 'jū liú sūn', meaning: '过去七佛之第四佛' },
    { char: '拘那含牟尼', pinyin: 'jū nà hán móu ní', meaning: '过去七佛之第五佛，意为"金寂"' },
    { char: '迦叶', pinyin: 'jiā shè', meaning: '过去七佛之第六佛，亦指佛陀大弟子' },
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈' },
    { char: '聚沫', pinyin: 'jù mò', meaning: '聚集的水泡，比喻身体虚幻不实' },
    { char: '正法眼藏', pinyin: 'zhèng fǎ yǎn zàng', meaning: '禅宗指佛陀心传的究竟法门' },
  ],
  juelin: [
    { char: '觉林', pinyin: 'jué lín', meaning: '菩萨名，出自《华严经》' },
    { char: '大种', pinyin: 'dà zhǒng', meaning: '地水火风四大元素' },
    { char: '五蕴', pinyin: 'wǔ yùn', meaning: '色受想行识，构成身心的五种要素' },
    { char: '法界', pinyin: 'fǎ jiè', meaning: '一切法的总汇，宇宙万有的整体' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '舍利弗', pinyin: 'shè lì fú', meaning: '佛陀十大弟子之一，智慧第一' },
  ],
  wenshu: [
    { char: '文殊师利', pinyin: 'wén shū shī lì', meaning: '大智菩萨，智慧第一的菩萨' },
    { char: '摩诃般若', pinyin: 'mó hē bō rě', meaning: '大智慧，通达诸法实相的究竟智慧' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '法界', pinyin: 'fǎ jiè', meaning: '一切法的总汇，宇宙万有的整体' },
    { char: '舍利弗', pinyin: 'shè lì fú', meaning: '佛陀十大弟子之一，智慧第一' },
    { char: '曼陀罗仙', pinyin: 'màn tuó luó xiān', meaning: '梁代译经僧，译出《文殊说般若经》' },
  ],
  wuran: [
    { char: '莲花生', pinyin: 'lián huā shēng', meaning: '藏传佛教宁玛派祖师' },
    { char: '觉性', pinyin: 'jué xìng', meaning: '本觉之性，众生本具的灵知灵觉' },
    { char: '三味耶', pinyin: 'sān mèi yē', meaning: '密宗誓约、印契' },
    { char: '娑婆', pinyin: 'suō pó', meaning: '堪忍世界，即我们所在的现实世间' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '轮回', pinyin: 'lún huí', meaning: '众生在六道中生死流转不已' },
    { char: '声闻', pinyin: 'shēng wén', meaning: '听闻佛法而悟道者，修四谛法' },
    { char: '缘觉', pinyin: 'yuán jué', meaning: '观十二因缘而自行悟道者' },
    { char: '中观', pinyin: 'zhōng guān', meaning: '龙树所创学派，离空有二边之中道' },
    { char: '瑜珈', pinyin: 'yú jiā', meaning: '相应、结合，密宗修法之一' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉、愚痴，一切烦恼的根本' },
  ],
  zhangzhi: [
    { char: '兰若', pinyin: 'lán rě', meaning: '阿兰若的简称，寂静处、寺院' },
    { char: '曼达', pinyin: 'màn dá', meaning: '密宗供养法器，象征宇宙供养' },
    { char: '明觉', pinyin: 'míng jué', meaning: '清明觉知，本觉的灵知作用' },
    { char: '空性', pinyin: 'kōng xìng', meaning: '一切法无自性的本质' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '常见', pinyin: 'cháng jiàn', meaning: '执着万法恒常不变的错误见解' },
    { char: '断见', pinyin: 'duàn jiàn', meaning: '执着万法断灭归无的错误见解' },
  ],
  xuemaicong: [
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '三界', pinyin: 'sān jiè', meaning: '欲界、色界、无色界，众生生死轮回的范围' },
    { char: '旷大劫', pinyin: 'kuàng dà jié', meaning: '极漫长的时间，无数亿年' },
    { char: '驰求', pinyin: 'chí qiú', meaning: '向外奔走追求，指心向外攀缘' },
    { char: '十二部经', pinyin: 'shí èr bù jīng', meaning: '佛经的十二种分类体裁' },
    { char: '善星比丘', pinyin: 'shàn xīng bǐ qiū', meaning: '佛经中虽诵十二部经却不见性而轮回的人物' },
    { char: '皂白', pinyin: 'zào bái', meaning: '黑白，比喻是非善恶' },
    { char: '无间地狱', pinyin: 'wú jiān dì yù', meaning: '受苦无间断的地狱，最苦之处' },
  ],
  wuxinglun: [
    { char: '寂照', pinyin: 'jì zhào', meaning: '寂而常照、照而常寂，定慧一体的境界' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '转第八识所成之智，如大圆镜映现万法' },
    { char: '无念', pinyin: 'wú niàn', meaning: '不执着妄念，非无心如木石' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
  ],
  poxianglun: [
    { char: '六度', pinyin: 'liù dù', meaning: '布施、持戒、忍辱、精进、禅定、般若六种修行' },
    { char: '名相', pinyin: 'míng xiàng', meaning: '事物的名称和表相，非实相本体' },
    { char: '伽蓝', pinyin: 'qié lán', meaning: '寺院，僧伽蓝摩的简称' },
    { char: '塔庙', pinyin: 'tǎ miào', meaning: '供奉佛舍利或经像的建筑' },
    { char: '持犯', pinyin: 'chí fàn', meaning: '持戒与犯戒' },
    { char: '福田', pinyin: 'fú tián', meaning: '种福之田，比喻供养布施能生福报' },
  ],
  wuxinlun: [
    { char: '无心', pinyin: 'wú xīn', meaning: '无妄心，非无真心；不起执着分别' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '妄心', pinyin: 'wàng xīn', meaning: '虚妄分别之心，执着外境之念' },
    { char: '真心', pinyin: 'zhēn xīn', meaning: '本来自性清净之心' },
  ],
  xixulun: [
    { char: '无生法忍', pinyin: 'wú shēng fǎ rěn', meaning: '忍可诸法本自无生之真理' },
    { char: '狂心', pinyin: 'kuáng xīn', meaning: '狂乱的妄想心，歇下即菩提' },
    { char: '顿悟', pinyin: 'dùn wù', meaning: '顿时悟入本来实相' },
  ],
  sixingguan: [
    { char: '报冤行', pinyin: 'bào yuān xíng', meaning: '逢苦不怨，认旧业而不报新怨' },
    { char: '随缘行', pinyin: 'suí yuán xíng', meaning: '苦乐随缘，得失不动' },
    { char: '无所求行', pinyin: 'wú suǒ qiú xíng', meaning: '万有皆空，无所贪求' },
    { char: '称法行', pinyin: 'chēng fǎ xíng', meaning: '称合清净法性而行六度' },
    { char: '理入', pinyin: 'lǐ rù', meaning: '藉教悟宗，深信含生同一真性' },
    { char: '行入', pinyin: 'xíng rù', meaning: '四行实践，于日常中磨炼心性' },
  ],
  fangcunlun: [
    { char: '方寸', pinyin: 'fāng cùn', meaning: '心，古人以方寸之地喻心' },
    { char: '须弥', pinyin: 'xū mí', meaning: '须弥山，佛教宇宙观中的世界中心' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '缘木求鱼', pinyin: 'yuán mù qiú yú', meaning: '爬到树上去找鱼，比喻方向错误徒劳无功' },
    { char: '中道', pinyin: 'zhōng dào', meaning: '离空有二边的不二之道' },
    { char: '灵山', pinyin: 'líng shān', meaning: '灵鹫山，佛说法处；亦指自心清净处' },
  ],
  anxin: [
    { char: '蕲州', pinyin: 'qí zhōu', meaning: '古地名，今湖北蕲春一带' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '楞伽经', pinyin: 'léng qié jīng', meaning: '禅宗所依经典，以佛语心为宗' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '实相', pinyin: 'shí xiàng', meaning: '万法的真实本相，即空性' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '泯然', pinyin: 'mǐn rán', meaning: '消融、消失的样子' },
  ],
  zuishangcheng: [
    { char: '金刚佛性', pinyin: 'jīn gāng fó xìng', meaning: '坚固不坏、能破一切的佛性' },
    { char: '五阴', pinyin: 'wǔ yīn', meaning: '即五蕴：色受想行识' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '三涂', pinyin: 'sān tú', meaning: '地狱、饿鬼、畜生三恶道' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '凝然', pinyin: 'níng rán', meaning: '安定不动摇的样子' },
    { char: '守心', pinyin: 'shǒu xīn', meaning: '守护本心不令散乱，五祖弘忍的核心教法' },
  ],
  mazu: [
    { char: '什邡', pinyin: 'shí fāng', meaning: '古地名，今四川什邡市，马祖故里' },
    { char: '醍醐', pinyin: 'tí hú', meaning: '酥酪提炼出的最精纯之物，喻最上法味' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '般若多罗', pinyin: 'bō rě duō luó', meaning: '达摩之师，西天第二十七祖' },
    { char: '蹋', pinyin: 'tà', meaning: '踩、踏' },
    { char: '谄曲', pinyin: 'chǎn qū', meaning: '谄媚歪曲，不正直' },
    { char: '海印三昧', pinyin: 'hǎi yìn sān mèi', meaning: '如大海映现万象的三昧境界' },
    { char: '声闻', pinyin: 'shēng wén', meaning: '听闻佛法而悟道者，修四谛法' },
    { char: '法性', pinyin: 'fǎ xìng', meaning: '万法的本性，即空性、真如' },
    { char: '恒沙', pinyin: 'héng shā', meaning: '恒河沙，比喻数量极多' },
    { char: '弋猎', pinyin: 'yì liè', meaning: '以弓箭射猎' },
    { char: '摑', pinyin: 'guō', meaning: '用巴掌打、掴' },
    { char: '祗对', pinyin: 'zhī duì', meaning: '应对、对答' },
    { char: '伎儿', pinyin: 'jì ér', meaning: '表演技艺的人' },
    { char: '篾', pinyin: 'miè', meaning: '竹篾，劈成细条的竹片' },
    { char: '蹋', pinyin: 'tà', meaning: '同踏，踩' },
  ],
  baizhang: [
    { char: '怀海', pinyin: 'huái hǎi', meaning: '百丈禅师名，马祖道一的法嗣' },
    { char: '该练', pinyin: 'gāi liàn', meaning: '全面通达、熟习' },
    { char: '寮', pinyin: 'liáo', meaning: '僧人住的房间' },
    { char: '罔然', pinyin: 'wǎng rán', meaning: '茫然、不知所措的样子' },
    { char: '拂子', pinyin: 'fú zǐ', meaning: '拂尘，禅师说法时手持的器具' },
    { char: '岩峦', pinyin: 'yán luán', meaning: '山峰、山峦' },
    { char: '蘑至', pinyin: 'mó zhì', meaning: '纷纷到来' },
    { char: '不昧因果', pinyin: 'bù mèi yīn guǒ', meaning: '不蒙蔽因果，悟者仍在因果中但不被蒙蔽' },
    { char: '迥脱', pinyin: 'jiǒng tuō', meaning: '迥然超脱，彻底超越' },
    { char: '根尘', pinyin: 'gēn chén', meaning: '六根（眼耳鼻舌身意）与六尘（色声香味触法）' },
  ],
  huangbo: [
    { char: '希运', pinyin: 'xī yùn', meaning: '黄檗禅师名，临济义玄之师' },
    { char: '鹫峰', pinyin: 'jiù fēng', meaning: '灵鹫山，黄檗山所在' },
    { char: '嫡孙', pinyin: 'dí sūn', meaning: '正宗法孙，直系传人' },
    { char: '裴休', pinyin: 'péi xiū', meaning: '唐代宰相，黄檗禅师俗家弟子，记录《传心法要》' },
    { char: '纤埃', pinyin: 'xiān āi', meaning: '极微小的尘埃' },
    { char: '乖', pinyin: 'guāi', meaning: '违背、背离' },
    { char: '蠢动含灵', pinyin: 'chǔn dòng hán líng', meaning: '一切有知觉的生命，从人到微小虫类' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '如如', pinyin: 'rú rú', meaning: '真如之体，本来如是、不生不灭' },
  ],
  xiuxinjue: [
    { char: '热恼', pinyin: 'rè nǎo', meaning: '炽热的烦恼，如火灼身' },
    { char: '火宅', pinyin: 'huǒ zhái', meaning: '比喻三界生死充满众苦，如着火的房屋' },
    { char: '无漏', pinyin: 'wú lòu', meaning: '没有烦恼漏失的清净法' },
    { char: '顿悟', pinyin: 'dùn wù', meaning: '顿时悟入本来实相' },
    { char: '渐修', pinyin: 'jiàn xiū', meaning: '循序渐进地修行，逐步除习气' },
    { char: '习气', pinyin: 'xí qì', meaning: '多生多世积累的烦恼惯势' },
    { char: '蒸沙作饭', pinyin: 'zhēng shā zuò fàn', meaning: '蒸沙子想做成饭，比喻方法错误徒劳无功' },
  ],
  linji: [
    { char: '无位真人', pinyin: 'wú wèi zhēn rén', meaning: '临济宗核心概念，超越一切名位框架的本来自性' },
    { char: '干屎橛', pinyin: 'gān shǐ jué', meaning: '干粪块，禅师用以截断学人分别心的峻烈话头' },
    { char: '赤肉团', pinyin: 'chì ròu tuán', meaning: '血肉之躯，指人的身体' },
    { char: '面门', pinyin: 'miàn mén', meaning: '面部，指眼耳鼻舌等感官' },
    { char: '精魅', pinyin: 'jīng mèi', meaning: '妖精鬼怪，比喻迷惑学人的邪见' },
    { char: '凑泊', pinyin: 'còu bó', meaning: '凑近、靠拢，指心向外攀缘执着' },
    { char: '五无间业', pinyin: 'wǔ wú jiàn yè', meaning: '五种必堕无间地狱的重罪' },
    { char: '驰求', pinyin: 'chí qiú', meaning: '向外奔走追求，指心向外攀缘' },
    { char: '逢着便杀', pinyin: 'féng zhe biàn shā', meaning: '遇佛杀佛遇祖杀祖，比喻彻底放下一切执着' },
  ],
  dunwu: [
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '以头触地行礼，佛教最敬礼' },
    { char: '和南', pinyin: 'hé nán', meaning: '佛教礼敬语，即顶礼' },
    { char: '有情', pinyin: 'yǒu qíng', meaning: '一切有情感知觉的众生' },
    { char: '八风', pinyin: 'bā fēng', meaning: '利衰毁誉称讥苦乐，八种能动摇人心的境界' },
    { char: '无生心', pinyin: 'wú shēng xīn', meaning: '不生妄念的清净心' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '无住', pinyin: 'wú zhù', meaning: '心不执着于任何一处' },
  ],
  zhenxin: [
    { char: '真心', pinyin: 'zhēn xīn', meaning: '本来自性清净之心' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '转第八识所成之智，如大圆镜映现万法' },
    { char: '六尘', pinyin: 'liù chén', meaning: '色声香味触法六种外境' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉、愚痴，一切烦恼的根本' },
    { char: '法身', pinyin: 'fǎ shēn', meaning: '以空为体的佛身，无形无相' },
    { char: '威仪', pinyin: 'wēi yí', meaning: '行住坐卧四种姿态，僧人举止规范' },
  ],
  zhigong: [
    { char: '宝志', pinyin: 'bǎo zhì', meaning: '梁代高僧，又称志公，以神通异行著称' },
    { char: '骑驴觅驴', pinyin: 'qí lǘ mì lǘ', meaning: '骑着驴找驴，比喻本已具足却向外驰求' },
    { char: '波旬', pinyin: 'bō xún', meaning: '魔王名，常干扰修行人' },
    { char: '泥盘', pinyin: 'ní pán', meaning: '同涅槃，烦恼熄灭的解脱境界' },
    { char: '大乘', pinyin: 'dà chéng', meaning: '能载众人至彼岸的佛法，以利他为宗' },
  ],
  xinwangming: [
    { char: '心王', pinyin: 'xīn wáng', meaning: '心之主体，统率诸心所，比喻自性真心' },
    { char: '胶青', pinyin: 'jiāo qīng', meaning: '胶质，比喻真心存在而不可见其形' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '六道', pinyin: 'liù dào', meaning: '天、人、阿修罗、地狱、饿鬼、畜生六种轮回境界' },
  ],
  shenhui: [
    { char: '无念', pinyin: 'wú niàn', meaning: '不执着妄念，非无心如木石' },
    { char: '真空', pinyin: 'zhēn kōng', meaning: '非断灭之空，而是含摄万法的真实空性' },
    { char: '妙有', pinyin: 'miào yǒu', meaning: '从空性中显现的妙用，非实有之有' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '二乘', pinyin: 'èr chéng', meaning: '声闻乘与缘觉乘，修自了生死者' },
    { char: '断常', pinyin: 'duàn cháng', meaning: '断见与常见，两种边见' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '系缚', pinyin: 'xì fù', meaning: '被烦恼捆绑，不得自在' },
    { char: '荷泽', pinyin: 'hé zé', meaning: '神会大师的宗派名，荷泽宗' },
  ],
  baojingsanmei: [
    { char: '盌', pinyin: 'wǎn', meaning: '同"碗"，盛器。银盌盛雪，喻本体与现象浑然难辨' },
    { char: '鹭', pinyin: 'lù', meaning: '鹭鸟，羽毛洁白。明月藏鹭，喻法界一相、理事交融' },
    { char: '窠臼', pinyin: 'kē jiù', meaning: '旧格式、陈套。动成窠臼，谓一动言说便落俗套' },
    { char: '顾伫', pinyin: 'gù zhù', meaning: '迟疑徘徊。差落顾伫，谓稍有迟疑便失机锋' },
    { char: '荎', pinyin: 'tí', meaning: '荎草，一种五味草。如荎草味，喻五味和合、偏正交融' },
    { char: '馵', pinyin: 'zhù', meaning: '马左后足白。如马之馵，喻不纯、有偏' },
    { char: '貍奴', pinyin: 'lí nú', meaning: '猫。貍奴白牯，喻以平常之物接引惊异根器者' },
    { char: '缁', pinyin: 'zī', meaning: '黑色。以缁为素，谓黑白颠倒、以邪为正' },
    { char: '檀度', pinyin: 'tán dù', meaning: '布施波罗蜜，六度之首。为法檀度，谓为法建立度门' },
    { char: '鞔鞔', pinyin: 'mán mán', meaning: '网罗密布貌。金锁网鞔鞔，喻修行不力则如披枷带锁' },
    { char: '渗漏', pinyin: 'shèn lòu', meaning: '三种修行偏差：见渗漏、情渗漏、语渗漏' },
    { char: '回互', pinyin: 'huí hù', meaning: '曹洞宗核心概念，指体用、偏正、理事相互含摄转化' },
    { char: '主中主', pinyin: 'zhǔ zhōng zhǔ', meaning: '曹洞四宾主最高位，超越宾主、不涉正偏的绝对境界' },
  ],
  dongshanyulu: [
    { char: '溈山', pinyin: 'wéi shān', meaning: '沩山灵祐禅师，洞山曾参之。沩仰宗开山祖师' },
    { char: '云岩', pinyin: 'yún yán', meaning: '云岩昙晟禅师，洞山得法师父，药山惟俨法嗣' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语，意为轨范师，对僧人的尊称' },
    { char: '五位', pinyin: 'wǔ wèi', meaning: '曹洞宗纲宗：正中偏、偏中正、正中来、兼中至、兼中到' },
    { char: '功勋五位', pinyin: 'gōng xūn wǔ wèi', meaning: '向、奉、功、共功、功功——从发心到究竟的修证次第' },
    { char: '鸟道', pinyin: 'niǎo dào', meaning: '洞山三路之一，空中鸟迹无迹可寻，喻心空行无迹' },
    { char: '玄路', pinyin: 'xuán lù', meaning: '洞山三路之一，识偏正回互之路，接中下根器' },
    { char: '展手', pinyin: 'zhǎn shǒu', meaning: '洞山三路之一，当下便了，接上根利智' },
    { char: '乾慧', pinyin: 'qián huì', meaning: '有慧无定之空头智慧，末法时代人之通病' },
    { char: '粟畬', pinyin: 'sù yú', meaning: '烧荒种田处。洞山答僧"向甚处去"云"粟畬里去"' },
    { char: '㳂流', pinyin: 'yán liú', meaning: '沿流、顺流而下。洞山答兴平云"㳂流无定止"' },
    { char: '曹洞宗', pinyin: 'cáo dòng zōng', meaning: '洞山良价与曹山本寂共创之禅宗五家之一，以偏正回互、绵密宗风著称' },
  ],
  yongjia: [
    { char: '玄觉', pinyin: 'xuán jué', meaning: '永嘉大师法名，谥真觉大师，人称"一宿觉"' },
    { char: '一宿觉', pinyin: 'yī xiǔ jué', meaning: '永嘉参六祖，一宿之间言下大悟，故得此号' },
    { char: '奢摩他', pinyin: 'shē mó tā', meaning: '梵语，意为"止"，禅定之异名，令心住于一境' },
    { char: '毗婆舍那', pinyin: 'pí pó shě nà', meaning: '梵语，意为"观"，以智慧观照诸法实相' },
    { char: '优毕叉', pinyin: 'yōu bì chā', meaning: '梵语，意为"止观等持"，定慧平等之中道' },
    { char: '四宏誓愿', pinyin: 'sì hóng shì yuàn', meaning: '众生无边誓愿度，烦恼无数誓愿断，法门无量誓愿学，佛道无上誓愿成' },
    { char: '三谛', pinyin: 'sān dì', meaning: '天台宗核心：真谛（空）、俗谛（假）、中谛（中道）' },
    { char: '三乘', pinyin: 'sān shèng', meaning: '声闻乘、缘觉乘、菩萨乘，三种修行阶位' },
    { char: '黄门', pinyin: 'huáng mén', meaning: '古指阉人，发愿文中指不愿生为残缺之身' },
    { char: '曹溪', pinyin: 'cáo xī', meaning: '广东韶关曹溪，六祖惠能道场所在地，代指南宗禅' },
  ],
  yunmen: [
    { char: '文偃', pinyin: 'wén yǎn', meaning: '云门大师法名，五代高僧，云门宗开山祖师' },
    { char: '睦州', pinyin: 'mù zhōu', meaning: '睦州道明禅师，黄檗法嗣，云门初参之师，机辩峭捷' },
    { char: '乾屎橛', pinyin: 'gān shǐ jué', meaning: '拭粪之竹片。云门答"如何是佛"云"乾屎橛"，以秽语破名相执' },
    { char: '函盖乾坤', pinyin: 'hán gài qián kūn', meaning: '云门三句之一：万法皆真，物物全真，天地万法尽在一句中' },
    { char: '截断众流', pinyin: 'jié duàn zhòng liú', meaning: '云门三句之一：斩断妄想之流，言语道断，心行处灭' },
    { char: '随波逐浪', pinyin: 'suí bō zhú làng', meaning: '云门三句之一：随学人根机接引，应病与药，灵活无碍' },
    { char: '掠虚汉', pinyin: 'lüè xū hàn', meaning: '云门斥语，指记言抄语、依葫芦画瓢而无实悟之徒' },
    { char: '秦时轹钻', pinyin: 'qín shí lì zuān', meaning: '睦州勘云门之语。秦时之钻，钝而无用，截断学人思量' },
    { char: '灵树', pinyin: 'líng shù', meaning: '灵树如敏禅师道场，云门初为首座之处，在广东韶州' },
    { char: '苏噜苏噜', pinyin: 'sū lǔ sū lǔ', meaning: '云门答话惯用语，象声词，截断问头，不落言诠' },
    { char: '髫龀', pinyin: 'tiáo chèn', meaning: '童年。云门"才自髫龀，志尚率己厌俗"' },
  ],
  bashiguijusong: [
    { char: '净色根', pinyin: 'jìng sè gēn', meaning: '佛教术语，指感官的微细生理基础，非肉眼可见' },
    { char: '九缘', pinyin: 'jiǔ yuán', meaning: '眼识生起所需的九种条件：空、明、根、境、作意、分别依、染净依、根本依、种子' },
    { char: '带质境', pinyin: 'dài zhì jìng', meaning: '唯识三境之一，以本质为依据而变现的影像境' },
    { char: '独影境', pinyin: 'dú yǐng jìng', meaning: '唯识三境之一，无所本质，由意识独自变现的影像' },
    { char: '性境', pinyin: 'xìng jìng', meaning: '唯识三境之一，有实体境，如实显现' },
    { char: '现量', pinyin: 'xiàn liàng', meaning: '三量之一，不经分别推度，直接缘境的真实认知' },
    { char: '比量', pinyin: 'bǐ liàng', meaning: '三量之一，经由推理比度而得的认知' },
    { char: '非量', pinyin: 'fēi liàng', meaning: '三量之一，错误的认知，不符合实际的判断' },
    { char: '末那识', pinyin: 'mò nà shí', meaning: '第七识，恒审思量第八识为"我"，是一切我执的根源' },
    { char: '阿赖耶识', pinyin: 'ā lài yē shí', meaning: '第八识，含藏一切种子，受熏持种，异熟果报' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '第八识所转之智，如大圆镜无所不照' },
    { char: '平等性智', pinyin: 'píng děng xìng zhì', meaning: '第七识所转之智，了知自他平等' },
    { char: '妙观察智', pinyin: 'miào guān chá zhì', meaning: '第六识所转之智，善观诸法自相共相' },
    { char: '成所作智', pinyin: 'chéng suǒ zuò zhì', meaning: '前五识所转之智，能现三类分身利益众生' },
    { char: '异熟', pinyin: 'yì shú', meaning: '因果异时成熟，指第八识感果报的功能' },
    { char: '无覆无记', pinyin: 'wú fù wú jì', meaning: '第八识的性：不覆障圣道，非善非恶' },
    { char: '有覆无记', pinyin: 'yǒu fù wú jì', meaning: '第七识的性：覆障圣道但非善非恶' },
    { char: '遍行', pinyin: 'biàn xíng', meaning: '五种遍行心所：触、作意、受、想、思，通一切识一切性' },
    { char: '随烦恼', pinyin: 'suí fán nǎo', meaning: '随根本烦恼而起的烦恼，分大随、中随、小随' },
    { char: '金刚道', pinyin: 'jīn gāng dào', meaning: '成佛前最后一念无间道，金刚喻定，断尽最后一品微细无明' },
  ],
  wumenguan: [
    { char: '无门', pinyin: 'wú mén', meaning: '无门慧开，宋代禅宗高僧，编集《无门关》四十八则公案' },
    { char: '慧开', pinyin: 'huì kāi', meaning: '无门慧开之法名，宋绍定元年编集无门关' },
    { char: '敲门瓦子', pinyin: 'qiāo mén wǎ zi', meaning: '敲门砖，比喻公案是参究的工具，非究竟道理' },
    { char: '热铁丸', pinyin: 'rè tiě wán', meaning: '比喻参"无"字时疑情逼拶之状——吞不下吐不出' },
    { char: '依草附木', pinyin: 'yī cǎo fù mù', meaning: '比喻无实悟者依附他人言句，如精灵依附草木' },
    { char: '那吒', pinyin: 'né zhā', meaning: '那吒太子，佛教护法神，八臂那吒喻勇猛无畏' },
    { char: '俱胝', pinyin: 'jù zhī', meaning: '俱胝和尚，唐代禅师，以"一指禅"著称' },
    { char: '天龙', pinyin: 'tiān lóng', meaning: '天龙禅师，俱胝之师，传一指禅' },
    { char: '香严', pinyin: 'xiāng yán', meaning: '香严智闲禅师，沩山灵祐法嗣' },
    { char: '瑞岩', pinyin: 'ruì yán', meaning: '瑞岩师彦禅师，每日自唤"主人公"' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒觉了之状，禅宗常言"惺惺着"' },
    { char: '婆子', pinyin: 'pó zi', meaning: '台山婆子，无门关中勘验学人的女性禅者' },
    { char: '罔明', pinyin: 'wǎng míng', meaning: '罔明菩萨，出自无门关第四十二则"女子出定"' },
    { char: '竹篦', pinyin: 'zhú bì', meaning: '竹制禅具，首山省念拈竹篦勘验学人' },
    { char: '话堕', pinyin: 'huà duò', meaning: '言语落套，被言句所堕，云门勘破学人"话堕"' },
    { char: '净瓶', pinyin: 'jìng píng', meaning: '僧人用水器，百丈拈净瓶选沩山主人' },
    { char: '草鞋', pinyin: 'cǎo xié', meaning: '赵州顶草鞋出，以颠倒行径破南泉斩猫之令' },
    { char: '大庾岭', pinyin: 'dà yú lǐng', meaning: '六祖为惠明开示处，在广东江西交界' },
    { char: '本来面目', pinyin: 'běn lái miàn mù', meaning: '六祖为惠明直指——善恶念头不起时的本来觉性' },
    { char: '定盘星', pinyin: 'dìng pán xīng', meaning: '秤上的基准星，比喻错认标准或执着处' },
  ],
  changuancejin: [
    { char: '禅关', pinyin: 'chán guān', meaning: '禅修之关隘，喻修行须经之关卡' },
    { char: '关棙子', pinyin: 'guān lì zi', meaning: '机关枢纽，喻禅修关键处' },
    { char: '蒲团', pinyin: 'pú tuán', meaning: '禅僧坐禅用的圆形坐垫' },
    { char: '话头', pinyin: 'huà tóu', meaning: '参究的语句，如"无"字、"念佛是谁"' },
    { char: '疑情', pinyin: 'yí qíng', meaning: '参禅时生起的疑团，是悟道的动力' },
    { char: '本参', pinyin: 'běn cān', meaning: '修行者本人在参究的话头或公案' },
    { char: '打彻', pinyin: 'dǎ chè', meaning: '彻底悟透，禅宗语' },
    { char: '髑髅', pinyin: 'dú lóu', meaning: '头骨，喻妄心壳子，打破髑髅即打破妄心' },
    { char: '拚', pinyin: 'pàn', meaning: '豁出去，不顾一切' },
    { char: '厮捱', pinyin: 'sī ái', meaning: '相持、挨磨，喻与话头持续参究' },
    { char: '提撕', pinyin: 'tí sī', meaning: '提举警醒，不断提起话头' },
    { char: '增上慢', pinyin: 'zēng shàng màn', meaning: '未得谓得，以少为足的傲慢' },
    { char: '般舟三昧', pinyin: 'bān zhōu sān mèi', meaning: '九十日常行三昧，不坐不卧的修行法' },
    { char: '头陀', pinyin: 'tóu tuó', meaning: '苦行，舍弃贪着的修行方式' },
  ],
  dachengqixinlun: [
    { char: '摩诃衍', pinyin: 'mó hē yǎn', meaning: '大乘的梵语音译' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '诸法真实本性，离言绝相的绝对真理' },
    { char: '如来藏', pinyin: 'rú lái zàng', meaning: '众生本具的佛性，含藏如来一切功德' },
    { char: '阿赖耶识', pinyin: 'ā lài yē shí', meaning: '第八识，含藏一切种子的根本识' },
    { char: '熏习', pinyin: 'xūn xí', meaning: '互相影响、熏染，如衣熏香' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉悟，一切烦恼生死的根本' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '止观', pinyin: 'zhǐ guān', meaning: '止息妄念与观察实相，禅修两大法门' },
    { char: '檀那', pinyin: 'tán nà', meaning: '布施，梵语音译' },
    { char: '尸罗', pinyin: 'shī luó', meaning: '戒律，梵语音译' },
    { char: '羼提', pinyin: 'chàn tí', meaning: '忍辱，梵语音译' },
    { char: '毘梨耶', pinyin: 'pí lí yē', meaning: '精进，梵语音译' },
    { char: '禅那', pinyin: 'chán nà', meaning: '禅定，梵语音译' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，通达诸法实相的智慧' },
    { char: '阿僧祇劫', pinyin: 'ā sēng qí jié', meaning: '无数劫，极长的时间单位' },
    { char: '摩尼宝', pinyin: 'mó ní bǎo', meaning: '如意宝珠，能满足所愿' },
    { char: '客尘', pinyin: 'kè chén', meaning: '外在的烦恼染污，如客尘染污明镜' },
  ],
  huanwuxinyao: [
    { char: '覰', pinyin: 'qù', meaning: '看、窥视，禅宗多用此字表示机锋审视' },
    { char: '蹊径', pinyin: 'qī jìng', meaning: '小路，比喻修行的方法途径' },
    { char: '铢两', pinyin: 'zhū liǎng', meaning: '极微小的重量，比喻精密的判断' },
    { char: '阃奥', pinyin: 'kǔn ào', meaning: '深处、精微之地，比喻学问的精深处' },
    { char: '矻矻', pinyin: 'kū kū', meaning: '勤劳不懈的样子' },
    { char: '摝', pinyin: 'lù', meaning: '捞取、搅动，禅宗用语' },
    { char: '蚬', pinyin: 'xiǎn', meaning: '小蛤蜊，比喻微细事物' },
    { char: '湫湫', pinyin: 'qiū qiū', meaning: '冷清寂静的样子' },
    { char: '倮倮', pinyin: 'luǒ luǒ', meaning: '赤裸无遮，比喻心无挂碍' },
    { char: '洒洒', pinyin: 'sǎ sǎ', meaning: '洒脱无拘的样子' },
    { char: '踈', pinyin: 'shū', meaning: '同"疏"，疏通、疏远' },
    { char: '蹋', pinyin: 'tà', meaning: '踩、踏，禅宗机锋中常指一踏令悟' },
    { char: '箇', pinyin: 'gè', meaning: '同"个"，禅宗语录常用量词' },
    { char: '觑', pinyin: 'qù', meaning: '看、窥，禅宗指审视观照' },
    { char: '蓦', pinyin: 'mò', meaning: '忽然、突然' },
    { char: '踟蹰', pinyin: 'chí chú', meaning: '犹豫不决、徘徊不前' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、障碍，比喻无明遮蔽真心' },
    { char: '亘', pinyin: 'gèn', meaning: '横贯、贯穿，亘然即一直如此' },
    { char: '杲', pinyin: 'gǎo', meaning: '明亮，杲日即明亮的太阳' },
    { char: '趺', pinyin: 'fū', meaning: '盘腿坐，结加趺坐即双盘打坐' },
  ],
  huanwuyulu: [
    { char: '謷', pinyin: 'áo', meaning: '诋毁、讥讽，謷讹即讹误差错' },
    { char: '鹁鸠', pinyin: 'bó jiū', meaning: '一种鸟名，斑鸠类' },
    { char: '蟇', pinyin: 'má', meaning: '同"蟆"，蛤蟆' },
    { char: '仓庚', pinyin: 'cāng gēng', meaning: '黄鹂鸟' },
    { char: '寒蝉', pinyin: 'hán chán', meaning: '秋天的蝉，天冷不再鸣叫' },
    { char: '椀', pinyin: 'wǎn', meaning: '同"碗"，小碗' },
    { char: '幞头', pinyin: 'fú tóu', meaning: '古代男子头巾' },
    { char: '刬', pinyin: 'chǎn', meaning: '同"铲"，铲除' },
    { char: '镆', pinyin: 'mò', meaning: '镆铘，古代宝剑名' },
    { char: '毘', pinyin: 'pí', meaning: '同"毗"，毗卢遮那佛' },
    { char: '凫', pinyin: 'fú', meaning: '野鸭' },
    { char: '胫', pinyin: 'jìng', meaning: '小腿' },
    { char: '棘', pinyin: 'jí', meaning: '荆棘' },
    { char: '鹄', pinyin: 'hú', meaning: '天鹅' },
    { char: '葛怛', pinyin: 'gé dá', meaning: '烦恼痛苦的佛教音译词' },
    { char: '阇维', pinyin: 'shé wéi', meaning: '梵语jhāpita，火化、荼毗' },
    { char: '龛', pinyin: 'kān', meaning: '供奉佛像或存放骨灰的小阁' },
    { char: '刈', pinyin: 'yì', meaning: '割、收割' },
    { char: '蟭螟', pinyin: 'jiāo míng', meaning: '极微小的虫' },
    { char: '拕', pinyin: 'tuō', meaning: '同"拖"，拖拽' },
  ],
  dahuiyulu: [
    { char: '劄', pinyin: 'zhá', meaning: '奏札，臣下呈给皇帝的文书' },
    { char: '𦶟', pinyin: 'ruò', meaning: '点燃、焚烧，同"爇"' },
    { char: '拈', pinyin: 'niān', meaning: '用手指夹取，禅宗常用"拈拄杖""拈香"' },
    { char: '槌', pinyin: 'chuí', meaning: '锤子，禅宗"白槌"为打椎宣布开堂' },
    { char: '搀', pinyin: 'chān', meaning: '抢先、插话，"搀前"即上前' },
    { char: '磕', pinyin: 'kē', meaning: '碰撞，"筑著磕著"为禅宗俗语，意为恰好说中' },
    { char: '谩', pinyin: 'màn', meaning: '欺骗、蒙蔽，"热谩"为禅宗斥语' },
    { char: '噇', pinyin: 'chuáng', meaning: '大口吃喝，"噇眠"即吃了睡' },
    { char: '鞦韆', pinyin: 'qiū qiān', meaning: '秋千，禅宗喻指虚妄不实' },
    { char: '夤', pinyin: 'yín', meaning: '攀附连结，"夤缘"为攀缘向上' },
    { char: '泞', pinyin: 'nìng', meaning: '泥泞，"淡泞"形容云烟淡荡' },
    { char: '蒺蔾', pinyin: 'jí lí', meaning: '蒺藜，带刺植物，喻指难以吞咽的话头' },
    { char: '鍚', pinyin: 'yáng', meaning: '马额上的金属饰物' },
    { char: '刬', pinyin: 'chǎn', meaning: '同"铲"，削平、除去' },
    { char: '搦', pinyin: 'nuò', meaning: '握持、挑惹，"搦生"为禅宗机语' },
    { char: '趂', pinyin: 'chèn', meaning: '同"趁"，乘机、追逐' },
    { char: '蓦', pinyin: 'mò', meaning: '突然、忽然，"蓦然"为禅宗常用语' },
    { char: '拄杖', pinyin: 'zhǔ zhàng', meaning: '禅师手中的法杖，用于开示和接引学人' },
    { char: '白槌', pinyin: 'bái chuí', meaning: '打椎宣布开堂，禅宗开法仪式' },
    { char: '热谩', pinyin: 'rè màn', meaning: '禅宗斥语，意为蒙骗、糊弄' },
  ],
  chanjia_guijian: [
    { char: '挆', pinyin: 'duǒ', meaning: '同"垛"，此处指落根、着落' },
    { char: '飏', pinyin: 'yáng', meaning: '抛掷、丢开，"飏在无事匣里"指把话头丢在无事中' },
    { char: '卜度', pinyin: 'bǔ duó', meaning: '猜测、揣度，禅宗斥为意识分别' },
    { char: '逼拶', pinyin: 'bī zā', meaning: '逼迫、催迫，禅宗指以言句或话头逼迫学人至思量不及处' },
    { char: '漆桶', pinyin: 'qī tǒng', meaning: '禅宗喻指无明暗昧之心，"打破漆桶"喻开悟' },
    { char: '龟鉴', pinyin: 'guī jiàn', meaning: '龟甲可卜，青铜镜可照，比喻借鉴、指南' },
    { char: '嫡子', pinyin: 'dí zǐ', meaning: '正室所生之子，禅宗喻指得法正宗的弟子' },
    { char: '孽子', pinyin: 'niè zǐ', meaning: '庶出或非正统之子，禅宗喻指偏离宗旨的弟子' },
    { char: '葛藤', pinyin: 'gé téng', meaning: '禅宗喻指文字语言的纠缠，"一篇葛藤"指一堆文字说理' },
    { char: '踞地', pinyin: 'jù dì', meaning: '蹲踞于地，"踞地狮子"为临济四喝之一' },
    { char: '探竿', pinyin: 'tàn gān', meaning: '探测之竿，"探竿影草"为临济四喝之一，指试探学人' },
    { char: '料拣', pinyin: 'liào jiǎn', meaning: '同"料简"，选择、简别，临济四料拣为接人法门' },
    { char: '甲子', pinyin: 'jiǎ zǐ', meaning: '天干地支纪年，"年代甲子总不知"指不计时日' },
    { char: '八风', pinyin: 'bā fēng', meaning: '利、衰、毁、誉、称、讥、苦、乐八种境界' },
    { char: '四恩', pinyin: 'sì ēn', meaning: '父母恩、国王恩、师友恩、施主恩' },
  ],
  xinming: [
    { char: '熏炼', pinyin: 'xūn liàn', meaning: '熏习修炼，指渐次修持以转化心性' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒明觉貌，禅宗指灵知不昧的状态' },
    { char: '寂寂', pinyin: 'jì jì', meaning: '寂静无为之貌，与惺惺相对' },
    { char: '森罗', pinyin: 'sēn luó', meaning: '森罗万象，指宇宙间一切现象' },
    { char: '顽嚣', pinyin: 'wán xiāo', meaning: '愚顽喧嚣，此处指外表看似愚钝无知的模样' },
    { char: '虚冲', pinyin: 'xū chōng', meaning: '虚寂冲淡，指本际空灵无相' },
    { char: '诠神', pinyin: 'quán shén', meaning: '诠释神妙，指以言语表述不可言之境界' },
    { char: '四等', pinyin: 'sì děng', meaning: '即慈悲喜舍四无量心，又称四等心' },
  ],
  zuochanyi: [
    { char: '跏趺', pinyin: 'jiā fū', meaning: '佛陀坐法，两足交叠置于两腿之上，全跏趺为双盘，半跏趺为单盘' },
    { char: '髀', pinyin: 'bì', meaning: '大腿，"安左髀上"即安放在左大腿上' },
    { char: '拄', pinyin: 'zhǔ', meaning: '支撑、抵住，"拇指相拄"即两拇指相抵' },
    { char: '腭', pinyin: 'è', meaning: '口腔上壁，"舌拄上腭"即舌抵上腭' },
    { char: '欠', pinyin: 'qiàn', meaning: '欠身，身体前倾的动作' },
    { char: '浮屠', pinyin: 'fú tú', meaning: '佛塔，"状如浮屠"指身正如塔' },
    { char: '卒暴', pinyin: 'cù bào', meaning: '仓促粗暴，"不得卒暴"指出定时不可动作太猛' },
    { char: '蹉跎', pinyin: 'cuō tuó', meaning: '虚度光阴，错失时机' },
  ],
  huangbo_wanlinglu: [
    { char: '幻翳', pinyin: 'huàn yì', meaning: '幻象与眼翳，比喻虚妄的见闻觉知如眼翳所见之幻相' },
    { char: '息机', pinyin: 'xī jī', meaning: '止息心机妄动，与"忘见"连用指放下一切分别心' },
    { char: '寝疾', pinyin: 'qǐn jí', meaning: '卧病在床，"唯置一床寝疾而卧"比喻心不起诸见如人卧病攀缘都息' },
    { char: '宝器', pinyin: 'bǎo qì', meaning: '珍贵的食器，"诸天共宝器食"谓诸天用同一宝器进食，随福德不同饭色各异' },
    { char: '铁围山', pinyin: 'tiě wéi shān', meaning: '佛教宇宙观中的铁轮围山，"贬向二铁围山"喻指落入二边见之困境' },
    { char: '权实', pinyin: 'quán shí', meaning: '权智与实智，文殊代表实智，普贤代表权智，究竟而言权实不二' },
    { char: '一体三宝', pinyin: 'yī tǐ sān bǎo', meaning: '于一心中具足佛法僧三宝，法即是佛，佛法俱无即僧' },
    { char: '歌利王', pinyin: 'gē lì wáng', meaning: '佛陀本生故事中的暴君，曾割截忍辱仙人身体，比喻心向外求如游猎' },
    { char: '摩诃衍', pinyin: 'mó hē yǎn', meaning: '大乘的梵语音译，"摩诃衍胜出"谓大乘能超越三界' },
    { char: '棙子', pinyin: 'lì zi', meaning: '机关、关键，"遮关棙子"指禅关的机括要害' },
    { char: '兀然', pinyin: 'wù rán', meaning: '安然不动貌，"兀然无著"指心不动摇无所执着' },
    { char: '黄叶为金', pinyin: 'huáng yè wéi jīn', meaning: '以黄叶当金子哄小孩不哭，比喻佛说一切法只是方便化度，实无有法' },
    { char: '蠲除', pinyin: 'juān chú', meaning: '清除、去除，"蠲除戏论之粪"指除去心中戏论见解' },
  ],
  zhaozhouyulu: [
    { char: '𨍏轹', pinyin: 'lì lì', meaning: '人名号，𨍏轹道人为重校赵州语录者' },
    { char: '掠彴子', pinyin: 'lüè zhuó zi', meaning: '小木桥，简陋的便桥，赵州以之对比石桥' },
    { char: '丫角童', pinyin: 'yā jiǎo tóng', meaning: '梳双髻的童子，指行脚途中遇到的异僧' },
    { char: '齁齁', pinyin: 'hōu hōu', meaning: '酣睡貌，"得一句子直至如今齁齁地饱"比喻饱餐禅味' },
    { char: '啗啄', pinyin: 'dàn zhuó', meaning: '鸟类进食貌，禅宗喻指学人参究时当机立断，不可犹豫' },
    { char: '洎合', pinyin: 'jì hé', meaning: '恰好、正该，"洎合放过这汉"意为正该放过他' },
    { char: '田厍奴', pinyin: 'tián shè nú', meaning: '田舍奴，讥称乡野无知之人' },
    { char: '箍桶', pinyin: 'gū tǒng', meaning: '箍制木桶，赵州以"箍桶汉"斥学人，意指本分事' },
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面，禅宗常用"觌面相呈"指当面直指' },
    { char: '阐提', pinyin: 'chǎn tí', meaning: '一阐提的简称，指断善根无成佛可能之人' },
    { char: '双陆', pinyin: 'shuāng lù', meaning: '古代一种博戏，赵州以"不解双陆"表示不谈戏论' },
    { char: '蓦直', pinyin: 'mò zhí', meaning: '一直、径直，"蓦直去"意为一直前行不回头' },
    { char: '趯', pinyin: 'tì', meaning: '踢、跃，禅宗"趯出"指跃出、抛出' },
    { char: '叵耐', pinyin: 'pǒ nài', meaning: '不可忍受，"叵耐"为可恨之意' },
    { char: '不唧溜', pinyin: 'bù jī liū', meaning: '不伶俐、不明事理，十二时歌中自嘲住持无能' },
    { char: '褊衫', pinyin: 'biǎn shān', meaning: '僧人所穿的偏衫，即上衣' },
    { char: '裈', pinyin: 'kūn', meaning: '裤子，"裈无腰"指裤子没有裤腰' },
    { char: '䭔子', pinyin: 'duī zi', meaning: '一种蒸饼类食物' },
    { char: '虀', pinyin: 'jī', meaning: '捣碎的腌菜，"蜀黍米饭虀莴苣"指粗食' },
    { char: '䉬', pinyin: 'dié', meaning: '竹席，"破芦䉬"指破烂的芦苇席' },
    { char: '幢子', pinyin: 'chuáng zi', meaning: '石柱形的经幢，"幢子无一截"指残断的经幢' },
    { char: '公验', pinyin: 'gōng yàn', meaning: '官府发放的通行证，赵州以"还我公验来"比喻本分事' },
    { char: '拨尘', pinyin: 'bō chén', meaning: '扫除尘垢，"拨尘见佛"比喻去妄求真' },
    { char: '衲衣', pinyin: 'nà yī', meaning: '僧人百衲衣，用碎布缝制而成' },
  ],
    jueguanlun: [
    { char: '冲虚', pinyin: 'chōng xū', meaning: '深奥空寂，"大道冲虚"指大道深远空寂' },
    { char: '参罗', pinyin: 'sēn luó', meaning: '森罗万象，指宇宙间种种事物' },
    { char: '龟毛兔角', pinyin: 'guī máo tù jiǎo', meaning: '龟没有毛、兔没有角，比喻不存在之物' },
    { char: '根量', pinyin: 'gēn liàng', meaning: '感官的限度，"离一切根量"指超越感官认知的范围' },
    { char: '玄光', pinyin: 'xuán guāng', meaning: '玄妙之光，比喻超越感官的智慧照用' },
    { char: '意生身', pinyin: 'yì shēng shēn', meaning: '菩萨以意力所化现的身体，非父母所生' },
    { char: '鸯掘', pinyin: 'yāng jué', meaning: '鸯掘魔罗，佛经中杀人后经佛度化出家的人物' },
    { char: '瞿昙', pinyin: 'qú tán', meaning: '释迦牟尼佛的姓氏，此处指佛陀' },
    { char: '壅', pinyin: 'yōng', meaning: '堵塞不通，"妄动故壅"指妄念使心不通畅' },
    { char: '腾腾', pinyin: 'téng téng', meaning: '悠然自在的样子，"腾腾任运"指随缘自在' },
    { char: '呵呵唧唧', pinyin: 'hē hē jī jī', meaning: '笑声，形容豁达无拘的样子' },
    { char: '他心智', pinyin: 'tā xīn zhì', meaning: '能知他人心念的智慧，属六通之一' },
    { char: '如来藏', pinyin: 'rú lái zàng', meaning: '一切众生本具的佛性，含藏如来一切功德' },
  ],

  'boshan-canchanjingyu': [
    { char: '獦狚', pinyin: 'gé dàn', meaning: '一种犬类动物，禅宗用来比喻呆坐无心的状态' },
    { char: '謦欬', pinyin: 'qǐng kài', meaning: '咳嗽声，比喻发出声响' },
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面' },
    { char: '颟顸儱侗', pinyin: 'mān hān lǒng tǒng', meaning: '糊涂含混、笼统不清的样子' },
    { char: '畗塞', pinyin: 'bó sè', meaning: '充满塞满，形容疑情充塞虚空' },
    { char: '黧奴', pinyin: 'lí nú', meaning: '黑猫，禅宗比喻疑情紧盯不放' },
    { char: '伽陀', pinyin: 'qié tuó', meaning: '佛经中的偈颂、药方' },
    { char: '曲彔', pinyin: 'qū lù', meaning: '曲录床，禅僧坐的交椅' },
    { char: '拶', pinyin: 'zā', meaning: '逼迫、紧压，禅宗指逼拶话头' },
    { char: '蒺蔾', pinyin: 'jí lí', meaning: '蒺藜，带刺的植物，比喻险难境遇' },
    { char: '泮然', pinyin: 'pàn rán', meaning: '消融、消散的样子' },
    { char: '觏', pinyin: 'gòu', meaning: '遇见、见到' },
    { char: '恁么', pinyin: 'nèn me', meaning: '这样、如此，禅宗常用语' },
    { char: '卜度', pinyin: 'bǔ duó', meaning: '揣测、臆度' },
    { char: '觑', pinyin: 'qù', meaning: '看、窥视' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒、明白，禅宗指灵觉不昧' },
    { char: '瞰', pinyin: 'kàn', meaning: '窥视、盯视，贼瞰巨室即贼窥大户' },
    { char: '橐', pinyin: 'tuó', meaning: '袋子，橐为之倾即家当被搬空' },
    { char: '柝', pinyin: 'tuò', meaning: '巡夜敲击的梆子，严城击柝喻警备' },
    { char: '栗棘蓬', pinyin: 'lì jí péng', meaning: '带刺的栗壳，禅林喻吞不下吐不出的公案' },
    { char: '肱', pinyin: 'gōng', meaning: '手臂，三折肱为良医喻阅历多方能知病' },
    { char: '膺', pinyin: 'yīng', meaning: '胸口，碍膺之物即堵在胸口的疑团' },
    { char: '遏捺', pinyin: 'è nà', meaning: '压抑、按捺，遏捺妄心即强行压住念头' },
    { char: '蠓', pinyin: 'měng', meaning: '蠓虫，微小飞虫，如蠓入猛焰喻妄念遇智火' },
    { char: '醭', pinyin: 'bú', meaning: '白醭，口边生的白膜，从教白醭口边生喻苦参' },
    { char: '庠', pinyin: 'xiáng', meaning: '安详，举止安庠即行止安详稳重' },
    { char: '觔斗', pinyin: 'jīn dǒu', meaning: '筋斗、跟头，万仞岩头翻觔斗喻悟后转身' },
    { char: '髭', pinyin: 'zī', meaning: '嘴上边的胡须，髭须可鉴喻水清可照' },
    { char: '聩', pinyin: 'kuì', meaning: '耳聋，耳聩眼朦胧喻年老昏聩' },
    { char: '痫', pinyin: 'xián', meaning: '癫痫，如发痫病喻识神颠倒之态' },
    { char: '铛', pinyin: 'chēng', meaning: '锅，猛火热油铛喻功夫紧迫' },
    { char: '坌', pinyin: 'bèn', meaning: '尘土聚积，旋坌喻尘劳纷纷围拢' },
    { char: '漭漭', pinyin: 'mǎng mǎng', meaning: '广大空旷貌，漭漭荡荡喻心量无拘' },
  ],

  caoshanyulu: [
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面' },
    { char: '黧奴', pinyin: 'lí nú', meaning: '黑猫，禅宗比喻疑情紧盯不放' },
    { char: '髑髅', pinyin: 'dú lóu', meaning: '头骨、骷髅，禅宗喻无分别识' },
    { char: '攒簇', pinyin: 'cuán cù', meaning: '聚集、凑集，禅宗指把捉、凑合' },
    { char: '白牯', pinyin: 'bái gǔ', meaning: '白色的牯牛，禅宗喻无知的异类' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语阿阇黎的略称，意为轨范师' },
    { char: '恁么', pinyin: 'nèn me', meaning: '这样、如此，禅宗常用语' },
    { char: '卜度', pinyin: 'bǔ duó', meaning: '揣测、臆度' },
    { char: '椑树', pinyin: 'bēi shù', meaning: '椑树，禅僧名' },
    { char: '俸', pinyin: 'fèng', meaning: '俸禄、薪俸' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒、明白，禅宗指灵觉不昧' },
  ],

  fayanyulu: [
    { char: '啗啄', pinyin: 'dàn zhuó', meaning: '咬啄，比喻言语交涉、机锋对答' },
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面' },
    { char: '拶', pinyin: 'zā', meaning: '逼迫、紧压，禅宗指逼拶话头' },
    { char: '椓', pinyin: 'zhuó', meaning: '敲击' },
    { char: '踅', pinyin: 'xué', meaning: '来回走动' },
    { char: '髑髅', pinyin: 'dú lóu', meaning: '头骨、骷髅，禅宗喻无分别识' },
    { char: '謇', pinyin: 'jiǎn', meaning: '口吃、说话困难' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语阿阇黎的略称，意为轨范师' },
    { char: '恁么', pinyin: 'nèn me', meaning: '这样、如此，禅宗常用语' },
    { char: '的的是', pinyin: 'dì dì shì', meaning: '确确实实、明明白白' },
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '头至手或地，佛教礼节' },
    { char: '斟酌', pinyin: 'zhēn zhuó', meaning: '思量、考虑，禅宗指卜度分别' },
    { char: '沂', pinyin: 'yí', meaning: '沂水，地名' },
    { char: '镬', pinyin: 'huò', meaning: '大锅' },
    { char: '馐', pinyin: 'xiū', meaning: '美食、佳肴' },
    { char: '攒', pinyin: 'cuán', meaning: '聚拢、凑集' },
    { char: '觑', pinyin: 'qù', meaning: '看、窥视' },
    { char: '碓', pinyin: 'duì', meaning: '舂米的器具，法演以"打碓打磨"喻日常劳作' },
    { char: '跣足', pinyin: 'xiǎn zú', meaning: '赤脚' },
    { char: '飏', pinyin: 'yáng', meaning: '飞扬、扬起' },
    { char: '辊', pinyin: 'gǔn', meaning: '滚动、滚转' },
    { char: '绣毬', pinyin: 'xiù qiú', meaning: '绣球，法演喻禅机活泼' },
    { char: '巴鼻', pinyin: 'bā bí', meaning: '把柄、根据，禅宗指入手处' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒、明白，禅宗指灵觉不昧' },
    { char: '葛怛', pinyin: 'gé dá', meaning: '粗糙的葛布，法演山居诗中指粗陋的枕头' },
    { char: '泗洲', pinyin: 'sì zhōu', meaning: '地名，法演诗中引用大圣参拜之典' },
    { char: '叮咽', pinyin: 'dīng yè', meaning: '絮叨、叮咛' },
    { char: '柴棚', pinyin: 'chái péng', meaning: '柴草搭的棚子' },
  ],  zhonglun: [
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈，通常为四句' },
    { char: '瞿昙', pinyin: 'qú tán', meaning: '佛陀的姓氏，也代指佛陀' },
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '头至手或地，佛教最敬礼' },
    { char: '因缘', pinyin: 'yīn yuán', meaning: '佛教核心概念，指事物生起的条件' },
    { char: '二谛', pinyin: 'èr dì', meaning: '世俗谛与第一义谛，佛教真理的两个层次' },
    { char: '四句', pinyin: 'sì jù', meaning: '有、无、亦有亦无、非有非无，龙树破斥的四种边见' },
    { char: '中道', pinyin: 'zhōng dào', meaning: '不落空有二边的正见，佛教的核心义理' },
    { char: '缘起', pinyin: 'yuán qǐ', meaning: '因缘和合而生起，佛教对事物存在方式的解释' },
  ],
  wanshantongguiji: [
    { char: '阂', pinyin: 'ài', meaning: '阻碍、妨碍。理事无阂即理事互不妨碍' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、蒙蔽。如“久翳尘劳”' },
    { char: '莹彻', pinyin: 'yíng chè', meaning: '晶莹透彻，明净照彻' },
    { char: '醍醐', pinyin: 'tí hú', meaning: '从乳中提炼的至甘精华，比喻至高圆顿之佛性法味' },
    { char: '遮诠', pinyin: 'zhē quán', meaning: '从否定与破执层面表述真理（如“非心非佛”），与“表诠”相对' },
    { char: '表诠', pinyin: 'biǎo quán', meaning: '从正面直接显发指陈真理（如“即心即佛”），与“遮诠”相对' },
    { char: '秖', pinyin: 'zhǐ', meaning: '古同“只”，仅仅、只管' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '阿阇梨简称，意为轨范师、教授师' },
    { char: '水月道场', pinyin: 'shuǐ yuè dào chǎng', meaning: '比喻虽知一切道场如水中月幻化无实，仍大作佛事庄严修持' },
    { char: '实相', pinyin: 'shí xiàng', meaning: '一切诸法真实不变之本体，离一切虚妄之相' },
  ],

  'chanyuan_zhuquanjiduxu': [
    { char: '户牖', pinyin: 'hù yǒu', meaning: '门窗，喻各宗自立门户' },
    { char: '纷拏', pinyin: 'fēn ná', meaning: '纷争纠缠' },
    { char: '疑曀', pinyin: 'yí yì', meaning: '疑云遮蔽，如阴翳蔽日' },
    { char: '劬劳', pinyin: 'qú láo', meaning: '辛勤劳苦' },
    { char: '金鍮', pinyin: 'jīn tōu', meaning: '金与鍮石（似金之铜），喻真伪难辨' },
    { char: '漭荡', pinyin: 'mǎng dàng', meaning: '广大空旷貌' },
    { char: '礭', pinyin: 'què', meaning: '同确，坚定、确实之意' },
    { char: '毱多', pinyin: 'jú duō', meaning: '禅宗祖师之名（提多迦后承者）' },
    { char: '罽宾', pinyin: 'jì bīn', meaning: '古西域国名，迦湿弥罗' },
    { char: '南侁', pinyin: 'nán shēn', meaning: '指智侁禅师一系，禅门南宗一派' },
    { char: '镮钏', pinyin: 'huán chuàn', meaning: '手镯与臂钏，喻器物各异金体是一' },
    { char: '纥利陀耶', pinyin: 'hé lì tuó yē', meaning: '梵语，肉团心（心脏）之音译' },
    { char: '质多耶', pinyin: 'zhì duō yē', meaning: '梵语，集起心，指第八识' },
    { char: '干栗陀耶', pinyin: 'gān lì tuó yē', meaning: '梵语，坚实心，指真心' },
    { char: '胜鬘', pinyin: 'shèng mán', meaning: '胜鬘夫人，《胜鬘经》主名' },
    { char: '憍陈如', pinyin: 'jiāo chén rú', meaning: '佛陀初度五比丘之首' },
    { char: '波罗㮈', pinyin: 'bō luó nài', meaning: '波罗㮈国，鹿野苑所在' },
    { char: '师子频呻', pinyin: 'shī zǐ pín shēn', meaning: '师子频呻三昧，佛入此定大众证法界' },
    { char: '麁', pinyin: 'cū', meaning: '同粗' },
    { char: '粝飡', pinyin: 'lì cān', meaning: '粗米饭食' },
    { char: '菽麦', pinyin: 'shū mài', meaning: '豆与麦，喻基本之分辨' },
    { char: '昭穆', pinyin: 'zhāo mù', meaning: '宗法制度中的辈分次序' },
    { char: '病差', pinyin: 'chài', meaning: '病愈；差通瘥' },
    { char: '礭言', pinyin: 'què yán', meaning: '确定之言（确言）' },
  ],
  biyanlu: [
    { char: '髑髅', pinyin: 'dú lóu', meaning: '骷髅，死人头骨，禅语中指情识尽处' },
    { char: '羝羊触藩', pinyin: 'dī yáng chù fān', meaning: '公羊角挂篱笆，进退两难' },
    { char: '醯鸡蠛蠓', pinyin: 'xī jī miè měng', meaning: '醋瓮里的小虫，喻极微细之生灵' },
    { char: '楖栗', pinyin: 'jí lì', meaning: '禅杖，木名，可为杖' },
    { char: '挨拶', pinyin: 'āi zā', meaning: '逼迫挤压，宗师勘验学人的手段' },
    { char: '牸牛', pinyin: 'zì niú', meaning: '母牛' },
    { char: '鳖鼻蛇', pinyin: 'biē bí shé', meaning: '剧毒之蛇，喻公案凶险' },
    { char: '掠虚头', pinyin: 'lüè xū tóu', meaning: '弄虚头、不实落，掠取虚名' },
    { char: '担板汉', pinyin: 'dān bǎn hàn', meaning: '扛木板的人，喻只见一边不见全局' },
    { char: '颟顸', pinyin: 'mān hān', meaning: '糊涂马虎、不明事理' },
    { char: '鹘', pinyin: 'hú', meaning: '隼类猛禽，搏击迅速' },
    { char: '麈', pinyin: 'zhǔ', meaning: '鹿中之王，其尾可制拂尘' },
    { char: '挃', pinyin: 'zhì', meaning: '撞击、捣击' },
    { char: '禳', pinyin: 'ráng', meaning: '祭祷消灾' },
    { char: '窠窟', pinyin: 'kē kū', meaning: '巢穴，喻情识见解的窠臼' },
    { char: '葛藤', pinyin: 'gé téng', meaning: '藤蔓缠绕，喻言语知解纠缠' },
    { char: '盂', pinyin: 'yú', meaning: '盛饮食的圆口器皿' },
    { char: '阃', pinyin: 'kǔn', meaning: '门槛' },
    { char: '霹雳', pinyin: 'pī lì', meaning: '疾雷' },
    { char: '拗', pinyin: 'ǎo', meaning: '折断' },
    { char: '鍮', pinyin: 'tōu', meaning: '黄铜似金者' },
    { char: '摵', pinyin: 'shè', meaning: '击打声' },
    { char: '捩', pinyin: 'liè', meaning: '扭转' },
    { char: '幞', pinyin: 'fú', meaning: '包头软巾' },
    { char: '蟭螟', pinyin: 'jiāo míng', meaning: '极微小的虫' },
    { char: '鼈', pinyin: 'biē', meaning: '同鳖' },
    { char: '拕', pinyin: 'tuō', meaning: '同拖' },
    { char: '邈', pinyin: 'miǎo', meaning: '描绘' },
  ],
  yangqihoulu: [
    { char: '趺', pinyin: 'fū', meaning: '盘腿端坐，趺座即结跏趺坐' },
    { char: '槌', pinyin: 'chuí', meaning: '棒槌，维那白槌即鸣槌示意' },
    { char: '洎', pinyin: 'jì', meaning: '及、至，此处意为连同' },
    { char: '俾', pinyin: 'bǐ', meaning: '使、让' },
    { char: '阇', pinyin: 'dū', meaning: '阇梨，梵语阿阇梨，指有德行的僧人' },
    { char: '杓', pinyin: 'sháo', meaning: '勺子，瓢勺' },
    { char: '璏', pinyin: 'jué', meaning: '人名用字' },
    { char: '摵', pinyin: 'shè', meaning: '击打声，摵一摵即击打一下' },
    { char: '捩', pinyin: 'liè', meaning: '扭转，捩转面即转过脸去' },
    { char: '幞', pinyin: 'fú', meaning: '包头软巾，幞头为古代头巾' },
    { char: '蟭螟', pinyin: 'jiāo míng', meaning: '极微小的虫' },
    { char: '鼈', pinyin: 'biē', meaning: '同鳖' },
    { char: '拕', pinyin: 'tuō', meaning: '同拖，拖拽' },
    { char: '邈', pinyin: 'miǎo', meaning: '描绘，写真' },
    { char: '鍮', pinyin: 'tōu', meaning: '黄铜似金者，金鍮不辨即真假不分' },
    { char: '鹘', pinyin: 'hú', meaning: '隼类猛禽，辽天鹘比喻迅捷' },
    { char: '斫', pinyin: 'zhuó', meaning: '砍、削' },
    { char: '鹄', pinyin: 'gǔ', meaning: '同鹘，猛禽' },
  ],
  linjianhoulu: [
    { char: '栢', pinyin: 'bǎi', meaning: '同柏，枣栢为李通玄之号' },
    { char: '翛', pinyin: 'xiāo', meaning: '翛然，无拘无束貌' },
    { char: '跣', pinyin: 'xiǎn', meaning: '赤脚' },
    { char: '伽棃', pinyin: 'qié lí', meaning: '僧衣，袈裟之别称' },
    { char: '睥睨', pinyin: 'pì nì', meaning: '斜视，傲视' },
    { char: '匡床', pinyin: 'kuāng chuáng', meaning: '方正的床' },
    { char: '旃檀', pinyin: 'zhān tán', meaning: '檀香，梵语candana音译' },
    { char: '彖', pinyin: 'tuàn', meaning: '《易经》中统括一卦之辞' },
    { char: '挝', pinyin: 'wō', meaning: '敲击' },
    { char: '殒', pinyin: 'yǔn', meaning: '坠落、消殒' },
    { char: '醯', pinyin: 'xī', meaning: '摩醯首罗，大自在天' },
    { char: '棃', pinyin: 'lí', meaning: '同梨' },
    { char: '馎饦', pinyin: 'bó tuō', meaning: '汤饼，面食' },
    { char: '踔', pinyin: 'chuō', meaning: '跳跃' },
    { char: '鲲鹏', pinyin: 'kūn péng', meaning: '庄子寓言中的大鱼大鸟' },
    { char: '兜率', pinyin: 'dōu lǜ', meaning: '兜率天，弥勒菩萨所居天宫' },
    { char: '馎', pinyin: 'bó', meaning: '馎饦，面食' },
    { char: '槌', pinyin: 'chuí', meaning: '棒槌' },
    { char: '僵仆', pinyin: 'jiāng pū', meaning: '倒地' },
    { char: '粲', pinyin: 'càn', meaning: '鲜明、灿烂' },
  ],
};
