/* ---- 生僻字解释：按经典 id 对应，每条含字/词、读音、释义 ---- */
export interface GlossaryEntry {
  char: string;
  pinyin: string;
  meaning: string;
}

export const ZEN_GLOSSARY: Record<string, GlossaryEntry[]> = {
  'qifo': [
    { char: '拘留孙', pinyin: 'jū liú sūn', meaning: '过去七佛之第四佛' },
    { char: '迦叶', pinyin: 'jiā shè', meaning: '过去七佛之第六佛，亦指佛陀大弟子' },
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈' },
    { char: '聚沫', pinyin: 'jù mò', meaning: '聚集的水泡，比喻身体虚幻不实' },
    { char: '正法眼藏', pinyin: 'zhèng fǎ yǎn zàng', meaning: '禅宗指佛陀心传的究竟法门' },
  ],
  'juelin': [
    { char: '觉林', pinyin: 'jué lín', meaning: '菩萨名，出自《华严经》' },
    { char: '大种', pinyin: 'dà zhǒng', meaning: '地水火风四大元素' },
    { char: '五蕴', pinyin: 'wǔ yùn', meaning: '色受想行识，构成身心的五种要素' },
    { char: '法界', pinyin: 'fǎ jiè', meaning: '一切法的总汇，宇宙万有的整体' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '舍利弗', pinyin: 'shè lì fú', meaning: '佛陀十大弟子之一，智慧第一' },
  ],
  'wenshu': [
    { char: '文殊师利', pinyin: 'wén shū shī lì', meaning: '大智菩萨，智慧第一的菩萨' },
    { char: '摩诃般若', pinyin: 'mó hē bō rě', meaning: '大智慧，通达诸法实相的究竟智慧' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '法界', pinyin: 'fǎ jiè', meaning: '一切法的总汇，宇宙万有的整体' },
    { char: '舍利弗', pinyin: 'shè lì fú', meaning: '佛陀十大弟子之一，智慧第一' },
    { char: '曼陀罗仙', pinyin: 'màn tuó luó xiān', meaning: '梁代译经僧，译出《文殊说般若经》' },
  ],
  'wuran': [
    { char: '莲花生', pinyin: 'lián huā shēng', meaning: '藏传佛教宁玛派祖师' },
    { char: '觉性', pinyin: 'jué xìng', meaning: '本觉之性，众生本具的灵知灵觉' },
    { char: '三味耶', pinyin: 'sān mèi yē', meaning: '密宗誓约、印契' },
    { char: '娑婆', pinyin: 'suō pó', meaning: '堪忍世界，即我们所在的现实世间' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '轮回', pinyin: 'lún huí', meaning: '众生在六道中生死流转不已' },
    { char: '声闻', pinyin: 'shēng wén', meaning: '听闻佛法而悟道者，修四谛法' },
    { char: '缘觉', pinyin: 'yuán jué', meaning: '观十二因缘而自行悟道者' },
    { char: '中观', pinyin: 'zhōng guān', meaning: '龙树所创学派，离空有二边之中道' },
    { char: '瑜珈', pinyin: 'yú jiā', meaning: '相应、结合，密宗修法之一' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉、愚痴，一切烦恼的根本' },
  ],
  'zhangzhi': [
    { char: '兰若', pinyin: 'lán rě', meaning: '阿兰若的简称，寂静处、寺院' },
    { char: '曼达', pinyin: 'màn dá', meaning: '密宗供养法器，象征宇宙供养' },
    { char: '明觉', pinyin: 'míng jué', meaning: '清明觉知，本觉的灵知作用' },
    { char: '空性', pinyin: 'kōng xìng', meaning: '一切法无自性的本质' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '常见', pinyin: 'cháng jiàn', meaning: '执着万法恒常不变的错误见解' },
    { char: '断见', pinyin: 'duàn jiàn', meaning: '执着万法断灭归无的错误见解' },
  ],
  'xuemaicong': [
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '三界', pinyin: 'sān jiè', meaning: '欲界、色界、无色界，众生生死轮回的范围' },
    { char: '旷大劫', pinyin: 'kuàng dà jié', meaning: '极漫长的时间，无数亿年' },
    { char: '驰求', pinyin: 'chí qiú', meaning: '向外奔走追求，指心向外攀缘' },
    { char: '十二部经', pinyin: 'shí èr bù jīng', meaning: '佛经的十二种分类体裁' },
    { char: '善星比丘', pinyin: 'shàn xīng bǐ qiū', meaning: '佛经中虽诵十二部经却不见性而轮回的人物' },
    { char: '皂白', pinyin: 'zào bái', meaning: '黑白，比喻是非善恶' },
    { char: '无间地狱', pinyin: 'wú jiān dì yù', meaning: '受苦无间断的地狱，最苦之处' },
  ],
  'wuxinglun': [
    { char: '寂照', pinyin: 'jì zhào', meaning: '寂而常照、照而常寂，定慧一体的境界' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '转第八识所成之智，如大圆镜映现万法' },
    { char: '无念', pinyin: 'wú niàn', meaning: '不执着妄念，非无心如木石' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
  ],
  'poxianglun': [
    { char: '六度', pinyin: 'liù dù', meaning: '布施、持戒、忍辱、精进、禅定、般若六种修行' },
    { char: '名相', pinyin: 'míng xiàng', meaning: '事物的名称和表相，非实相本体' },
    { char: '伽蓝', pinyin: 'qié lán', meaning: '寺院，僧伽蓝摩的简称' },
    { char: '塔庙', pinyin: 'tǎ miào', meaning: '供奉佛舍利或经像的建筑' },
    { char: '持犯', pinyin: 'chí fàn', meaning: '持戒与犯戒' },
    { char: '福田', pinyin: 'fú tián', meaning: '种福之田，比喻供养布施能生福报' },
  ],
  'wuxinlun': [
    { char: '无心', pinyin: 'wú xīn', meaning: '无妄心，非无真心；不起执着分别' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '妄心', pinyin: 'wàng xīn', meaning: '虚妄分别之心，执着外境之念' },
    { char: '真心', pinyin: 'zhēn xīn', meaning: '本来自性清净之心' },
  ],
  'xixulun': [
    { char: '无生法忍', pinyin: 'wú shēng fǎ rěn', meaning: '忍可诸法本自无生之真理' },
    { char: '狂心', pinyin: 'kuáng xīn', meaning: '狂乱的妄想心，歇下即菩提' },
    { char: '顿悟', pinyin: 'dùn wù', meaning: '顿时悟入本来实相' },
  ],
  'sixingguan': [
    { char: '报冤行', pinyin: 'bào yuān xíng', meaning: '逢苦不怨，认旧业而不报新怨' },
    { char: '随缘行', pinyin: 'suí yuán xíng', meaning: '苦乐随缘，得失不动' },
    { char: '无所求行', pinyin: 'wú suǒ qiú xíng', meaning: '万有皆空，无所贪求' },
    { char: '称法行', pinyin: 'chēng fǎ xíng', meaning: '称合清净法性而行六度' },
    { char: '理入', pinyin: 'lǐ rù', meaning: '藉教悟宗，深信含生同一真性' },
    { char: '行入', pinyin: 'xíng rù', meaning: '四行实践，于日常中磨炼心性' },
  ],
  'xinxinming': [
    { char: '至道', pinyin: 'zhì dào', meaning: '最高的道，指佛道、真如' },
    { char: '憎爱', pinyin: 'zēng ài', meaning: '厌恶与贪爱，一切烦恼的根源' },
    { char: '洞然', pinyin: 'dòng rán', meaning: '清楚明白的样子' },
    { char: '泯', pinyin: 'mǐn', meaning: '消灭、消除' },
    { char: '毫厘', pinyin: 'háo lí', meaning: '极微小的差别' },
  ],
  'fangcunlun': [
    { char: '方寸', pinyin: 'fāng cùn', meaning: '心，古人以方寸之地喻心' },
    { char: '须弥', pinyin: 'xū mí', meaning: '须弥山，佛教宇宙观中的世界中心' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '缘木求鱼', pinyin: 'yuán mù qiú yú', meaning: '爬到树上去找鱼，比喻方向错误徒劳无功' },
    { char: '中道', pinyin: 'zhōng dào', meaning: '离空有二边的不二之道' },
    { char: '灵山', pinyin: 'líng shān', meaning: '灵鹫山，佛说法处；亦指自心清净处' },
  ],
  'anxin': [
    { char: '蕲州', pinyin: 'qí zhōu', meaning: '古地名，今湖北蕲春一带' },
    { char: '一行三昧', pinyin: 'yī xíng sān mèi', meaning: '专一系缘法界的禅定' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '楞伽经', pinyin: 'léng qié jīng', meaning: '禅宗所依经典，以佛语心为宗' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '实相', pinyin: 'shí xiàng', meaning: '万法的真实本相，即空性' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '泯然', pinyin: 'mǐn rán', meaning: '消融、消失的样子' },
  ],
  'zuishangcheng': [
    { char: '金刚佛性', pinyin: 'jīn gāng fó xìng', meaning: '坚固不坏、能破一切的佛性' },
    { char: '五阴', pinyin: 'wǔ yīn', meaning: '即五蕴：色受想行识' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '烦恼熄灭的究竟解脱境界' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '三涂', pinyin: 'sān tú', meaning: '地狱、饿鬼、畜生三恶道' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '凝然', pinyin: 'níng rán', meaning: '安定不动摇的样子' },
    { char: '守心', pinyin: 'shǒu xīn', meaning: '守护本心不令散乱，五祖弘忍的核心教法' },
  ],
  'tanjing': [
    { char: '薙', pinyin: 'tì', meaning: '剃除，指剃发出家' },
    { char: '獦', pinyin: 'gé', meaning: '獦獠，古时对南方少数民族的贬称' },
    { char: '獠', pinyin: 'liáo', meaning: '同上，獦獠连用' },
    { char: '碓', pinyin: 'duì', meaning: '舂米的器具' },
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈' },
    { char: '阖', pinyin: 'hé', meaning: '全、都' },
    { char: '刹那', pinyin: 'chà nà', meaning: '极短的时间，一瞬间' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，即从生死此岸到达涅槃彼岸' },
    { char: '阿耨多罗三藐三菩提', pinyin: 'ā nòu duō luó sān miǎo sān pú tí', meaning: '无上正等正觉，佛果的智德' },
  ],
  'zhengdaoge': [
    { char: '兀', pinyin: 'wù', meaning: '高耸特立的样子' },
    { char: '迥', pinyin: 'jiǒng', meaning: '远、差得远' },
    { char: '澄', pinyin: 'chéng', meaning: '水静而清' },
    { char: '皎', pinyin: 'jiǎo', meaning: '洁白明亮' },
    { char: '渊', pinyin: 'yuān', meaning: '深水、深潭' },
  ],
  'mazu': [
    { char: '什邡', pinyin: 'shí fāng', meaning: '古地名，今四川什邡市，马祖故里' },
    { char: '醍醐', pinyin: 'tí hú', meaning: '酥酪提炼出的最精纯之物，喻最上法味' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '般若多罗', pinyin: 'bō rě duō luó', meaning: '达摩之师，西天第二十七祖' },
    { char: '蹋', pinyin: 'tà', meaning: '踩、踏' },
    { char: '谄曲', pinyin: 'chǎn qū', meaning: '谄媚歪曲，不正直' },
    { char: '海印三昧', pinyin: 'hǎi yìn sān mèi', meaning: '如大海映现万象的三昧境界' },
    { char: '声闻', pinyin: 'shēng wén', meaning: '听闻佛法而悟道者，修四谛法' },
    { char: '法性', pinyin: 'fǎ xìng', meaning: '万法的本性，即空性、真如' },
    { char: '恒沙', pinyin: 'héng shā', meaning: '恒河沙，比喻数量极多' },
    { char: '弋猎', pinyin: 'yì liè', meaning: '以弓箭射猎' },
    { char: '摑', pinyin: 'guō', meaning: '用巴掌打、掴' },
    { char: '祗对', pinyin: 'zhī duì', meaning: '应对、对答' },
    { char: '伎儿', pinyin: 'jì ér', meaning: '表演技艺的人' },
    { char: '篾', pinyin: 'miè', meaning: '竹篾，劈成细条的竹片' },
  ],
  'baizhang': [
    { char: '怀海', pinyin: 'huái hǎi', meaning: '百丈禅师名，马祖道一的法嗣' },
    { char: '该练', pinyin: 'gāi liàn', meaning: '全面通达、熟习' },
    { char: '寮', pinyin: 'liáo', meaning: '僧人住的房间' },
    { char: '罔然', pinyin: 'wǎng rán', meaning: '茫然、不知所措的样子' },
    { char: '拂子', pinyin: 'fú zǐ', meaning: '拂尘，禅师说法时手持的器具' },
    { char: '岩峦', pinyin: 'yán luán', meaning: '山峰、山峦' },
    { char: '蘑至', pinyin: 'mó zhì', meaning: '纷纷到来' },
    { char: '不昧因果', pinyin: 'bù mèi yīn guǒ', meaning: '不蒙蔽因果，悟者仍在因果中但不被蒙蔽' },
    { char: '迥脱', pinyin: 'jiǒng tuō', meaning: '迥然超脱，彻底超越' },
    { char: '根尘', pinyin: 'gēn chén', meaning: '六根（眼耳鼻舌身意）与六尘（色声香味触法）' },
  ],
  'huangbo': [
    { char: '希运', pinyin: 'xī yùn', meaning: '黄檗禅师名，临济义玄之师' },
    { char: '鹫峰', pinyin: 'jiù fēng', meaning: '灵鹫山，黄檗山所在' },
    { char: '嫡孙', pinyin: 'dí sūn', meaning: '正宗法孙，直系传人' },
    { char: '裴休', pinyin: 'péi xiū', meaning: '唐代宰相，黄檗禅师俗家弟子，记录《传心法要》' },
    { char: '纤埃', pinyin: 'xiān āi', meaning: '极微小的尘埃' },
    { char: '乖', pinyin: 'guāi', meaning: '违背、背离' },
    { char: '蠢动含灵', pinyin: 'chǔn dòng hán líng', meaning: '一切有知觉的生命，从人到微小虫类' },
    { char: '攀缘', pinyin: 'pān yuán', meaning: '心执着外境，如攀枝缘树' },
    { char: '如如', pinyin: 'rú rú', meaning: '真如之体，本来如是、不生不灭' },
  ],
  'xiuxinjue': [
    { char: '热恼', pinyin: 'rè nǎo', meaning: '炽热的烦恼，如火灼身' },
    { char: '火宅', pinyin: 'huǒ zhái', meaning: '比喻三界生死充满众苦，如着火的房屋' },
    { char: '无漏', pinyin: 'wú lòu', meaning: '没有烦恼漏失的清净法' },
    { char: '顿悟', pinyin: 'dùn wù', meaning: '顿时悟入本来实相' },
    { char: '渐修', pinyin: 'jiàn xiū', meaning: '循序渐进地修行，逐步除习气' },
    { char: '习气', pinyin: 'xí qì', meaning: '多生多世积累的烦恼惯势' },
    { char: '蒸沙作饭', pinyin: 'zhēng shā zuò fàn', meaning: '蒸沙子想做成饭，比喻方法错误徒劳无功' },
  ],
  'linji': [
    { char: '无位真人', pinyin: 'wú wèi zhēn rén', meaning: '临济宗核心概念，超越一切名位框架的本来自性' },
    { char: '干屎橛', pinyin: 'gān shǐ jué', meaning: '干粪块，禅师用以截断学人分别心的峻烈话头' },
    { char: '赤肉团', pinyin: 'chì ròu tuán', meaning: '血肉之躯，指人的身体' },
    { char: '面门', pinyin: 'miàn mén', meaning: '面部，指眼耳鼻舌等感官' },
    { char: '精魅', pinyin: 'jīng mèi', meaning: '妖精鬼怪，比喻迷惑学人的邪见' },
    { char: '凑泊', pinyin: 'còu bó', meaning: '凑近、靠拢，指心向外攀缘执着' },
    { char: '五无间业', pinyin: 'wǔ wú jiàn yè', meaning: '五种必堕无间地狱的重罪' },
    { char: '驰求', pinyin: 'chí qiú', meaning: '向外奔走追求，指心向外攀缘' },
    { char: '逢着便杀', pinyin: 'féng zhe biàn shā', meaning: '遇佛杀佛遇祖杀祖，比喻彻底放下一切执着' },
  ],
  'dunwu': [
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '以头触地行礼，佛教最敬礼' },
    { char: '和南', pinyin: 'hé nán', meaning: '佛教礼敬语，即顶礼' },
    { char: '有情', pinyin: 'yǒu qíng', meaning: '一切有情感知觉的众生' },
    { char: '八风', pinyin: 'bā fēng', meaning: '利衰毁誉称讥苦乐，八种能动摇人心的境界' },
    { char: '无生心', pinyin: 'wú shēng xīn', meaning: '不生妄念的清净心' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '无住', pinyin: 'wú zhù', meaning: '心不执着于任何一处' },
  ],
  'zhenxin': [
    { char: '真心', pinyin: 'zhēn xīn', meaning: '本来自性清净之心' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '转第八识所成之智，如大圆镜映现万法' },
    { char: '六尘', pinyin: 'liù chén', meaning: '色声香味触法六种外境' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉、愚痴，一切烦恼的根本' },
    { char: '法身', pinyin: 'fǎ shēn', meaning: '以空为体的佛身，无形无相' },
    { char: '威仪', pinyin: 'wēi yí', meaning: '行住坐卧四种姿态，僧人举止规范' },
  ],
  'zhigong': [
    { char: '宝志', pinyin: 'bǎo zhì', meaning: '梁代高僧，又称志公，以神通异行著称' },
    { char: '骑驴觅驴', pinyin: 'qí lǘ mì lǘ', meaning: '骑着驴找驴，比喻本已具足却向外驰求' },
    { char: '波旬', pinyin: 'bō xún', meaning: '魔王名，常干扰修行人' },
    { char: '泥盘', pinyin: 'ní pán', meaning: '同涅槃，烦恼熄灭的解脱境界' },
    { char: '大乘', pinyin: 'dà chéng', meaning: '能载众人至彼岸的佛法，以利他为宗' },
  ],
  'xinwangming': [
    { char: '心王', pinyin: 'xīn wáng', meaning: '心之主体，统率诸心所，比喻自性真心' },
    { char: '胶青', pinyin: 'jiāo qīng', meaning: '胶质，比喻真心存在而不可见其形' },
    { char: '波罗蜜', pinyin: 'bō luó mì', meaning: '到彼岸，从生死此岸到达涅槃彼岸' },
    { char: '六道', pinyin: 'liù dào', meaning: '天、人、阿修罗、地狱、饿鬼、畜生六种轮回境界' },
  ],
  'shenhui': [
    { char: '无念', pinyin: 'wú niàn', meaning: '不执着妄念，非无心如木石' },
    { char: '真空', pinyin: 'zhēn kōng', meaning: '非断灭之空，而是含摄万法的真实空性' },
    { char: '妙有', pinyin: 'miào yǒu', meaning: '从空性中显现的妙用，非实有之有' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '事物的真实本性，本来如是' },
    { char: '二乘', pinyin: 'èr chéng', meaning: '声闻乘与缘觉乘，修自了生死者' },
    { char: '断常', pinyin: 'duàn cháng', meaning: '断见与常见，两种边见' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
    { char: '系缚', pinyin: 'xì fù', meaning: '被烦恼捆绑，不得自在' },
    { char: '荷泽', pinyin: 'hé zé', meaning: '神会大师的宗派名，荷泽宗' },
  ],
  'jingangjing': [
    { char: '祇', pinyin: 'qí', meaning: '祇树给孤独园，佛说法处' },
    { char: '衲', pinyin: 'nà', meaning: '僧衣，也指僧人' },
    { char: '恒河沙', pinyin: 'héng hé shā', meaning: '比喻数量极多，如恒河中的沙粒' },
    { char: '须菩提', pinyin: 'xū pú tí', meaning: '佛陀十大弟子之一，解空第一' },
    { char: '阿兰那', pinyin: 'ā lán nà', meaning: '寂静处，修行之所' },
    { char: '筏', pinyin: 'fá', meaning: '竹筏，比喻佛法为渡河工具' },
    { char: '诃', pinyin: 'hē', meaning: '呵斥、责备' },
  ],
  'xinjing': [
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，特指通达诸法实相的智慧' },
    { char: '波罗蜜多', pinyin: 'bō luó mì duō', meaning: '到彼岸，超越生死到达涅槃' },
    { char: '菩提', pinyin: 'pú tí', meaning: '觉、智，佛果的智德' },
  ],
  'yuanjuejing': [
    { char: '骛', pinyin: 'wù', meaning: '追求、追逐' },
    { char: '棼', pinyin: 'fén', meaning: '纷乱、交错' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、障蔽' },
    { char: '幻', pinyin: 'huàn', meaning: '虚幻不实，如幻术' },
    { char: '奢摩他', pinyin: 'shē mó tā', meaning: '止，禅定的第一阶段——心专注一境' },
    { char: '三摩钵提', pinyin: 'sān mó bō tí', meaning: '观，禅定的第二阶段——于定中起观' },
    { char: '禅那', pinyin: 'chán nà', meaning: '静虑，禅定的第三阶段——止观双运' },
    { char: '陀罗尼', pinyin: 'tuó luó ní', meaning: '总持，能持集无量善法、遮止恶法' },
  ],
  'chanlinbaoxun': [
    { char: '衲子', pinyin: 'nà zǐ', meaning: '僧人，穿衲衣者' },
    { char: '苞苴', pinyin: 'bāo jū', meaning: '贿赂、馈赠之物' },
    { char: '砭', pinyin: 'biān', meaning: '古代治病的石针，引申为规劝、救治' },
    { char: '褫', pinyin: 'chǐ', meaning: '剥夺、脱去' },
    { char: '谮', pinyin: 'zèn', meaning: '诬陷、中伤' },
    { char: '刍', pinyin: 'chú', meaning: '割草、草料' },
    { char: '舂', pinyin: 'chōng', meaning: '用杵臼捣谷物去壳' },
    { char: '爨', pinyin: 'cuàn', meaning: '烧火做饭' },
    { char: '恣', pinyin: 'zì', meaning: '放纵、无拘束' },
    { char: '谧', pinyin: 'mì', meaning: '安静、静默' },
  ],
  'lengyanjing': [
    { char: '洎', pinyin: 'jì', meaning: '及、到' },
    { char: '麈', pinyin: 'zhǔ', meaning: '鹿类，尾毛可做拂尘；麈尾即说法时所用拂尘' },
    { char: '殒', pinyin: 'yǔn', meaning: '死亡、坠落' },
    { char: '抟', pinyin: 'tuán', meaning: '把东西揉成球形' },
    { char: '醐', pinyin: 'hú', meaning: '醍醐，酥酪提炼出的最精纯之物，喻佛果' },
    { char: '醍', pinyin: 'tí', meaning: '同上，醍醐连用' },
    { char: '阿难', pinyin: 'ā nán', meaning: '佛陀堂弟，多闻第一' },
    { char: '摩登伽', pinyin: 'mó dēng jiā', meaning: '低种姓女子，以咒术迷惑阿难' },
    { char: '楞严', pinyin: 'léng yán', meaning: '一切事究竟坚固，此经名' },
  ],
  'weimojiejing': [
    { char: '毘耶离', pinyin: 'pí yē lí', meaning: '古印度城名，维摩诘居住之地' },
    { char: '殁', pinyin: 'mò', meaning: '死亡' },
    { char: '诃', pinyin: 'hē', meaning: '呵斥、责备' },
    { char: '寤', pinyin: 'wù', meaning: '醒悟、觉醒' },
    { char: '筌', pinyin: 'quán', meaning: '捕鱼竹器，比喻言教为得鱼之工具' },
    { char: '殃', pinyin: 'yāng', meaning: '灾祸' },
    { char: '缶', pinyin: 'fǒu', meaning: '瓦器，盛酒浆的陶器' },
  ],
  'shiniutu': [
    { char: '廛', pinyin: 'chán', meaning: '市集、店铺集中的街道；入廛即入市井' },
    { char: '跣', pinyin: 'xiǎn', meaning: '赤脚、光脚' },
    { char: '迤逦', pinyin: 'yǐ lǐ', meaning: '曲折连绵、缓缓行走的样子' },
    { char: '羌笛', pinyin: 'qiāng dí', meaning: '古代西北少数民族的管乐器' },
    { char: '懡㦬', pinyin: 'mǒ luǒ', meaning: '羞愧、惭愧的样子' },
    { char: '廓庵', pinyin: 'kuò ān', meaning: '禅师号，南宋临济宗杨岐派' },
    { char: '威音劫', pinyin: 'wēi yīn jié', meaning: '最古远的劫名，指天地未分之前的绝对时间' },
    { char: '筌鱼', pinyin: 'quán yú', meaning: '筌为捕鱼工具，喻言教为工具' },
    { char: '蹄兔', pinyin: 'tí tù', meaning: '蹄为捕兔网，喻与筌同' },
  ],
  'baojingsanmei': [
    { char: '鹭', pinyin: 'lù', meaning: '鹭鸟，羽毛洁白。明月藏鹭，喻法界一相、理事交融' },
    { char: '窠臼', pinyin: 'kē jiù', meaning: '旧格式、陈套。动成窠臼，谓一动言说便落俗套' },
    { char: '顾伫', pinyin: 'gù zhù', meaning: '迟疑徘徊。差落顾伫，谓稍有迟疑便失机锋' },
    { char: '荎', pinyin: 'tí', meaning: '荎草，一种五味草。如荎草味，喻五味和合、偏正交融' },
    { char: '馵', pinyin: 'zhù', meaning: '马左后足白。如马之馵，喻不纯、有偏' },
    { char: '貍奴', pinyin: 'lí nú', meaning: '猫。貍奴白牯，喻以平常之物接引惊异根器者' },
    { char: '缁', pinyin: 'zī', meaning: '黑色。以缁为素，谓黑白颠倒、以邪为正' },
    { char: '檀度', pinyin: 'tán dù', meaning: '布施波罗蜜，六度之首。为法檀度，谓为法建立度门' },
    { char: '鞔鞔', pinyin: 'mán mán', meaning: '网罗密布貌。金锁网鞔鞔，喻修行不力则如披枷带锁' },
    { char: '渗漏', pinyin: 'shèn lòu', meaning: '三种修行偏差：见渗漏、情渗漏、语渗漏' },
    { char: '回互', pinyin: 'huí hù', meaning: '曹洞宗核心概念，指体用、偏正、理事相互含摄转化' },
    { char: '主中主', pinyin: 'zhǔ zhōng zhǔ', meaning: '曹洞四宾主最高位，超越宾主、不涉正偏的绝对境界' },
  ],
  'dongshanyulu': [
    { char: '溈山', pinyin: 'wéi shān', meaning: '沩山灵祐禅师，洞山曾参之。沩仰宗开山祖师' },
    { char: '云岩', pinyin: 'yún yán', meaning: '云岩昙晟禅师，洞山得法师父，药山惟俨法嗣' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语，意为轨范师，对僧人的尊称' },
    { char: '五位', pinyin: 'wǔ wèi', meaning: '曹洞宗纲宗：正中偏、偏中正、正中来、兼中至、兼中到' },
    { char: '功勋五位', pinyin: 'gōng xūn wǔ wèi', meaning: '向、奉、功、共功、功功——从发心到究竟的修证次第' },
    { char: '鸟道', pinyin: 'niǎo dào', meaning: '洞山三路之一，空中鸟迹无迹可寻，喻心空行无迹' },
    { char: '玄路', pinyin: 'xuán lù', meaning: '洞山三路之一，识偏正回互之路，接中下根器' },
    { char: '展手', pinyin: 'zhǎn shǒu', meaning: '洞山三路之一，当下便了，接上根利智' },
    { char: '乾慧', pinyin: 'qián huì', meaning: '有慧无定之空头智慧，末法时代人之通病' },
    { char: '曹洞宗', pinyin: 'cáo dòng zōng', meaning: '洞山良价与曹山本寂共创之禅宗五家之一，以偏正回互、绵密宗风著称' },
  ],
  'yongjia': [
    { char: '一宿觉', pinyin: 'yī xiǔ jué', meaning: '永嘉参六祖，一宿之间言下大悟，故得此号' },
    { char: '四宏誓愿', pinyin: 'sì hóng shì yuàn', meaning: '众生无边誓愿度，烦恼无数誓愿断，法门无量誓愿学，佛道无上誓愿成' },
    { char: '三谛', pinyin: 'sān dì', meaning: '天台宗核心：真谛（空）、俗谛（假）、中谛（中道）' },
    { char: '三乘', pinyin: 'sān shèng', meaning: '声闻乘、缘觉乘、菩萨乘，三种修行阶位' },
    { char: '黄门', pinyin: 'huáng mén', meaning: '古指阉人，发愿文中指不愿生为残缺之身' },
    { char: '曹溪', pinyin: 'cáo xī', meaning: '广东韶关曹溪，六祖惠能道场所在地，代指南宗禅' },
  ],
  'yunmen': [
    { char: '文偃', pinyin: 'wén yǎn', meaning: '云门大师法名，五代高僧，云门宗开山祖师' },
    { char: '睦州', pinyin: 'mù zhōu', meaning: '睦州道明禅师，黄檗法嗣，云门初参之师，机辩峭捷' },
    { char: '函盖乾坤', pinyin: 'hán gài qián kūn', meaning: '云门三句之一：万法皆真，物物全真，天地万法尽在一句中' },
    { char: '截断众流', pinyin: 'jié duàn zhòng liú', meaning: '云门三句之一：斩断妄想之流，言语道断，心行处灭' },
    { char: '随波逐浪', pinyin: 'suí bō zhú làng', meaning: '云门三句之一：随学人根机接引，应病与药，灵活无碍' },
    { char: '掠虚汉', pinyin: 'lüè xū hàn', meaning: '云门斥语，指记言抄语、依葫芦画瓢而无实悟之徒' },
    { char: '秦时轹钻', pinyin: 'qín shí lì zuān', meaning: '睦州勘云门之语。秦时之钻，钝而无用，截断学人思量' },
    { char: '灵树', pinyin: 'líng shù', meaning: '灵树如敏禅师道场，云门初为首座之处，在广东韶州' },
    { char: '苏噜苏噜', pinyin: 'sū lǔ sū lǔ', meaning: '云门答话惯用语，象声词，截断问头，不落言诠' },
  ],
  'bashiguijusong': [
    { char: '净色根', pinyin: 'jìng sè gēn', meaning: '佛教术语，指感官的微细生理基础，非肉眼可见' },
    { char: '九缘', pinyin: 'jiǔ yuán', meaning: '眼识生起所需的九种条件：空、明、根、境、作意、分别依、染净依、根本依、种子' },
    { char: '带质境', pinyin: 'dài zhì jìng', meaning: '唯识三境之一，以本质为依据而变现的影像境' },
    { char: '独影境', pinyin: 'dú yǐng jìng', meaning: '唯识三境之一，无所本质，由意识独自变现的影像' },
    { char: '性境', pinyin: 'xìng jìng', meaning: '唯识三境之一，有实体境，如实显现' },
    { char: '现量', pinyin: 'xiàn liàng', meaning: '三量之一，不经分别推度，直接缘境的真实认知' },
    { char: '比量', pinyin: 'bǐ liàng', meaning: '三量之一，经由推理比度而得的认知' },
    { char: '非量', pinyin: 'fēi liàng', meaning: '三量之一，错误的认知，不符合实际的判断' },
    { char: '阿赖耶识', pinyin: 'ā lài yē shí', meaning: '第八识，含藏一切种子，受熏持种，异熟果报' },
    { char: '大圆镜智', pinyin: 'dà yuán jìng zhì', meaning: '第八识所转之智，如大圆镜无所不照' },
    { char: '平等性智', pinyin: 'píng děng xìng zhì', meaning: '第七识所转之智，了知自他平等' },
    { char: '妙观察智', pinyin: 'miào guān chá zhì', meaning: '第六识所转之智，善观诸法自相共相' },
    { char: '成所作智', pinyin: 'chéng suǒ zuò zhì', meaning: '前五识所转之智，能现三类分身利益众生' },
    { char: '异熟', pinyin: 'yì shú', meaning: '因果异时成熟，指第八识感果报的功能' },
    { char: '无覆无记', pinyin: 'wú fù wú jì', meaning: '第八识的性：不覆障圣道，非善非恶' },
    { char: '有覆无记', pinyin: 'yǒu fù wú jì', meaning: '第七识的性：覆障圣道但非善非恶' },
    { char: '遍行', pinyin: 'biàn xíng', meaning: '五种遍行心所：触、作意、受、想、思，通一切识一切性' },
    { char: '随烦恼', pinyin: 'suí fán nǎo', meaning: '随根本烦恼而起的烦恼，分大随、中随、小随' },
    { char: '金刚道', pinyin: 'jīn gāng dào', meaning: '成佛前最后一念无间道，金刚喻定，断尽最后一品微细无明' },
  ],
  'wumenguan': [
    { char: '无门', pinyin: 'wú mén', meaning: '无门慧开，宋代禅宗高僧，编集《无门关》四十八则公案' },
    { char: '慧开', pinyin: 'huì kāi', meaning: '无门慧开之法名，宋绍定元年编集无门关' },
    { char: '敲门瓦子', pinyin: 'qiāo mén wǎ zi', meaning: '敲门砖，比喻公案是参究的工具，非究竟道理' },
    { char: '依草附木', pinyin: 'yī cǎo fù mù', meaning: '比喻无实悟者依附他人言句，如精灵依附草木' },
    { char: '那吒', pinyin: 'né zhā', meaning: '那吒太子，佛教护法神，八臂那吒喻勇猛无畏' },
    { char: '天龙', pinyin: 'tiān lóng', meaning: '天龙禅师，俱胝之师，传一指禅' },
    { char: '香严', pinyin: 'xiāng yán', meaning: '香严智闲禅师，沩山灵祐法嗣' },
    { char: '婆子', pinyin: 'pó zi', meaning: '台山婆子，无门关中勘验学人的女性禅者' },
    { char: '竹篦', pinyin: 'zhú bì', meaning: '竹制禅具，首山省念拈竹篦勘验学人' },
    { char: '净瓶', pinyin: 'jìng píng', meaning: '僧人用水器，百丈拈净瓶选沩山主人' },
    { char: '草鞋', pinyin: 'cǎo xié', meaning: '赵州顶草鞋出，以颠倒行径破南泉斩猫之令' },
    { char: '大庾岭', pinyin: 'dà yú lǐng', meaning: '六祖为惠明开示处，在广东江西交界' },
    { char: '本来面目', pinyin: 'běn lái miàn mù', meaning: '六祖为惠明直指——善恶念头不起时的本来觉性' },
    { char: '定盘星', pinyin: 'dìng pán xīng', meaning: '秤上的基准星，比喻错认标准或执着处' },
  ],
  'changuancejin': [
    { char: '禅关', pinyin: 'chán guān', meaning: '禅修之关隘，喻修行须经之关卡' },
    { char: '关棙子', pinyin: 'guān lì zi', meaning: '机关枢纽，喻禅修关键处' },
    { char: '蒲团', pinyin: 'pú tuán', meaning: '禅僧坐禅用的圆形坐垫' },
    { char: '疑情', pinyin: 'yí qíng', meaning: '参禅时生起的疑团，是悟道的动力' },
    { char: '本参', pinyin: 'běn cān', meaning: '修行者本人在参究的话头或公案' },
    { char: '打彻', pinyin: 'dǎ chè', meaning: '彻底悟透，禅宗语' },
    { char: '髑髅', pinyin: 'dú lóu', meaning: '头骨，喻妄心壳子，打破髑髅即打破妄心' },
    { char: '拚', pinyin: 'pàn', meaning: '豁出去，不顾一切' },
    { char: '厮捱', pinyin: 'sī ái', meaning: '相持、挨磨，喻与话头持续参究' },
    { char: '提撕', pinyin: 'tí sī', meaning: '提举警醒，不断提起话头' },
    { char: '增上慢', pinyin: 'zēng shàng màn', meaning: '未得谓得，以少为足的傲慢' },
    { char: '般舟三昧', pinyin: 'bān zhōu sān mèi', meaning: '九十日常行三昧，不坐不卧的修行法' },
    { char: '头陀', pinyin: 'tóu tuó', meaning: '苦行，舍弃贪着的修行方式' },
  ],
  'dachengqixinlun': [
    { char: '摩诃衍', pinyin: 'mó hē yǎn', meaning: '大乘的梵语音译' },
    { char: '真如', pinyin: 'zhēn rú', meaning: '诸法真实本性，离言绝相的绝对真理' },
    { char: '如来藏', pinyin: 'rú lái zàng', meaning: '众生本具的佛性，含藏如来一切功德' },
    { char: '阿赖耶识', pinyin: 'ā lài yē shí', meaning: '第八识，含藏一切种子的根本识' },
    { char: '熏习', pinyin: 'xūn xí', meaning: '互相影响、熏染，如衣熏香' },
    { char: '无明', pinyin: 'wú míng', meaning: '不觉悟，一切烦恼生死的根本' },
    { char: '三昧', pinyin: 'sān mèi', meaning: '正定，心专注一境而不散乱' },
    { char: '止观', pinyin: 'zhǐ guān', meaning: '止息妄念与观察实相，禅修两大法门' },
    { char: '檀那', pinyin: 'tán nà', meaning: '布施，梵语音译' },
    { char: '尸罗', pinyin: 'shī luó', meaning: '戒律，梵语音译' },
    { char: '羼提', pinyin: 'chàn tí', meaning: '忍辱，梵语音译' },
    { char: '毘梨耶', pinyin: 'pí lí yē', meaning: '精进，梵语音译' },
    { char: '禅那', pinyin: 'chán nà', meaning: '禅定，梵语音译' },
    { char: '般若', pinyin: 'bō rě', meaning: '智慧，通达诸法实相的智慧' },
    { char: '阿僧祇劫', pinyin: 'ā sēng qí jié', meaning: '无数劫，极长的时间单位' },
    { char: '摩尼宝', pinyin: 'mó ní bǎo', meaning: '如意宝珠，能满足所愿' },
    { char: '客尘', pinyin: 'kè chén', meaning: '外在的烦恼染污，如客尘染污明镜' },
  ],
  'huanwuxinyao': [
    { char: '覰', pinyin: 'qù', meaning: '看、窥视，禅宗多用此字表示机锋审视' },
    { char: '蹊径', pinyin: 'qī jìng', meaning: '小路，比喻修行的方法途径' },
    { char: '铢两', pinyin: 'zhū liǎng', meaning: '极微小的重量，比喻精密的判断' },
    { char: '阃奥', pinyin: 'kǔn ào', meaning: '深处、精微之地，比喻学问的精深处' },
    { char: '矻矻', pinyin: 'kū kū', meaning: '勤劳不懈的样子' },
    { char: '摝', pinyin: 'lù', meaning: '捞取、搅动，禅宗用语' },
    { char: '蚬', pinyin: 'xiǎn', meaning: '小蛤蜊，比喻微细事物' },
    { char: '湫湫', pinyin: 'qiū qiū', meaning: '冷清寂静的样子' },
    { char: '倮倮', pinyin: 'luǒ luǒ', meaning: '赤裸无遮，比喻心无挂碍' },
    { char: '洒洒', pinyin: 'sǎ sǎ', meaning: '洒脱无拘的样子' },
    { char: '蹋', pinyin: 'tà', meaning: '踩、踏，禅宗机锋中常指一踏令悟' },
    { char: '觑', pinyin: 'qù', meaning: '看、窥，禅宗指审视观照' },
    { char: '蓦', pinyin: 'mò', meaning: '忽然、突然' },
    { char: '踟蹰', pinyin: 'chí chú', meaning: '犹豫不决、徘徊不前' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、障碍，比喻无明遮蔽真心' },
    { char: '亘', pinyin: 'gèn', meaning: '横贯、贯穿，亘然即一直如此' },
    { char: '杲', pinyin: 'gǎo', meaning: '明亮，杲日即明亮的太阳' },
    { char: '趺', pinyin: 'fū', meaning: '盘腿坐，结加趺坐即双盘打坐' },
  ],
  'huanwuyulu': [
    { char: '謷', pinyin: 'áo', meaning: '诋毁、讥讽，謷讹即讹误差错' },
    { char: '鹁鸠', pinyin: 'bó jiū', meaning: '一种鸟名，斑鸠类' },
    { char: '仓庚', pinyin: 'cāng gēng', meaning: '黄鹂鸟' },
    { char: '寒蝉', pinyin: 'hán chán', meaning: '秋天的蝉，天冷不再鸣叫' },
    { char: '幞头', pinyin: 'fú tóu', meaning: '古代男子头巾' },
    { char: '镆', pinyin: 'mò', meaning: '镆铘，古代宝剑名' },
    { char: '凫', pinyin: 'fú', meaning: '野鸭' },
    { char: '胫', pinyin: 'jìng', meaning: '小腿' },
    { char: '棘', pinyin: 'jí', meaning: '荆棘' },
    { char: '鹄', pinyin: 'hú', meaning: '天鹅' },
    { char: '葛怛', pinyin: 'gé dá', meaning: '烦恼痛苦的佛教音译词' },
    { char: '阇维', pinyin: 'shé wéi', meaning: '梵语jhāpita，火化、荼毗' },
    { char: '龛', pinyin: 'kān', meaning: '供奉佛像或存放骨灰的小阁' },
    { char: '刈', pinyin: 'yì', meaning: '割、收割' },
    { char: '蟭螟', pinyin: 'jiāo míng', meaning: '极微小的虫' },
  ],
  'dahuiyulu': [
    { char: '劄', pinyin: 'zhá', meaning: '奏札，臣下呈给皇帝的文书' },
    { char: '鞦韆', pinyin: 'qiū qiān', meaning: '秋千，禅宗喻指虚妄不实' },
    { char: '蒺蔾', pinyin: 'jí lí', meaning: '蒺藜，带刺植物，喻指难以吞咽的话头' },
    { char: '鍚', pinyin: 'yáng', meaning: '马额上的金属饰物' },
    { char: '拄杖', pinyin: 'zhǔ zhàng', meaning: '禅师手中的法杖，用于开示和接引学人' },
    { char: '白槌', pinyin: 'bái chuí', meaning: '打椎宣布开堂，禅宗开法仪式' },
    { char: '热谩', pinyin: 'rè màn', meaning: '禅宗斥语，意为蒙骗、糊弄' },
  ],
  'chanjia_guijian': [
    { char: '卜度', pinyin: 'bǔ duó', meaning: '猜测、揣度，禅宗斥为意识分别' },
    { char: '逼拶', pinyin: 'bī zā', meaning: '逼迫、催迫，禅宗指以言句或话头逼迫学人至思量不及处' },
    { char: '龟鉴', pinyin: 'guī jiàn', meaning: '龟甲可卜，青铜镜可照，比喻借鉴、指南' },
    { char: '嫡子', pinyin: 'dí zǐ', meaning: '正室所生之子，禅宗喻指得法正宗的弟子' },
    { char: '孽子', pinyin: 'niè zǐ', meaning: '庶出或非正统之子，禅宗喻指偏离宗旨的弟子' },
    { char: '八风', pinyin: 'bā fēng', meaning: '利、衰、毁、誉、称、讥、苦、乐八种境界' },
    { char: '四恩', pinyin: 'sì ēn', meaning: '父母恩、国王恩、师友恩、施主恩' },
  ],
  'xinming': [
    { char: '熏炼', pinyin: 'xūn liàn', meaning: '熏习修炼，指渐次修持以转化心性' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒明觉貌，禅宗指灵知不昧的状态' },
    { char: '寂寂', pinyin: 'jì jì', meaning: '寂静无为之貌，与惺惺相对' },
    { char: '森罗', pinyin: 'sēn luó', meaning: '森罗万象，指宇宙间一切现象' },
    { char: '顽嚣', pinyin: 'wán xiāo', meaning: '愚顽喧嚣，此处指外表看似愚钝无知的模样' },
    { char: '虚冲', pinyin: 'xū chōng', meaning: '虚寂冲淡，指本际空灵无相' },
    { char: '诠神', pinyin: 'quán shén', meaning: '诠释神妙，指以言语表述不可言之境界' },
    { char: '四等', pinyin: 'sì děng', meaning: '即慈悲喜舍四无量心，又称四等心' },
  ],
  'zuochanyi': [
    { char: '跏趺', pinyin: 'jiā fū', meaning: '佛陀坐法，两足交叠置于两腿之上，全跏趺为双盘，半跏趺为单盘' },
    { char: '欠', pinyin: 'qiàn', meaning: '欠身，身体前倾的动作' },
    { char: '蹉跎', pinyin: 'cuō tuó', meaning: '虚度光阴，错失时机' },
  ],
  'huangbo_wanlinglu': [
    { char: '幻翳', pinyin: 'huàn yì', meaning: '幻象与眼翳，比喻虚妄的见闻觉知如眼翳所见之幻相' },
    { char: '权实', pinyin: 'quán shí', meaning: '权智与实智，文殊代表实智，普贤代表权智，究竟而言权实不二' },
    { char: '一体三宝', pinyin: 'yī tǐ sān bǎo', meaning: '于一心中具足佛法僧三宝，法即是佛，佛法俱无即僧' },
    { char: '歌利王', pinyin: 'gē lì wáng', meaning: '佛陀本生故事中的暴君，曾割截忍辱仙人身体，比喻心向外求如游猎' },
    { char: '黄叶为金', pinyin: 'huáng yè wéi jīn', meaning: '以黄叶当金子哄小孩不哭，比喻佛说一切法只是方便化度，实无有法' },
  ],
  'zhaozhouyulu': [
    { char: '𨍏轹', pinyin: 'lì lì', meaning: '人名号，𨍏轹道人为重校赵州语录者' },
    { char: '掠彴子', pinyin: 'lüè zhuó zi', meaning: '小木桥，简陋的便桥，赵州以之对比石桥' },
    { char: '丫角童', pinyin: 'yā jiǎo tóng', meaning: '梳双髻的童子，指行脚途中遇到的异僧' },
    { char: '啗啄', pinyin: 'dàn zhuó', meaning: '鸟类进食貌，禅宗喻指学人参究时当机立断，不可犹豫' },
    { char: '田厍奴', pinyin: 'tián shè nú', meaning: '田舍奴，讥称乡野无知之人' },
    { char: '阐提', pinyin: 'chǎn tí', meaning: '一阐提的简称，指断善根无成佛可能之人' },
    { char: '不唧溜', pinyin: 'bù jī liū', meaning: '不伶俐、不明事理，十二时歌中自嘲住持无能' },
    { char: '褊衫', pinyin: 'biǎn shān', meaning: '僧人所穿的偏衫，即上衣' },
    { char: '䭔子', pinyin: 'duī zi', meaning: '一种蒸饼类食物' },
    { char: '衲衣', pinyin: 'nà yī', meaning: '僧人百衲衣，用碎布缝制而成' },
  ],
  'jueguanlun': [
    { char: '参罗', pinyin: 'sēn luó', meaning: '森罗万象，指宇宙间种种事物' },
    { char: '龟毛兔角', pinyin: 'guī máo tù jiǎo', meaning: '龟没有毛、兔没有角，比喻不存在之物' },
    { char: '玄光', pinyin: 'xuán guāng', meaning: '玄妙之光，比喻超越感官的智慧照用' },
    { char: '意生身', pinyin: 'yì shēng shēn', meaning: '菩萨以意力所化现的身体，非父母所生' },
    { char: '鸯掘', pinyin: 'yāng jué', meaning: '鸯掘魔罗，佛经中杀人后经佛度化出家的人物' },
    { char: '瞿昙', pinyin: 'qú tán', meaning: '释迦牟尼佛的姓氏，此处指佛陀' },
    { char: '呵呵唧唧', pinyin: 'hē hē jī jī', meaning: '笑声，形容豁达无拘的样子' },
    { char: '他心智', pinyin: 'tā xīn zhì', meaning: '能知他人心念的智慧，属六通之一' },
    { char: '如来藏', pinyin: 'rú lái zàng', meaning: '一切众生本具的佛性，含藏如来一切功德' },
  ],
  'boshan-canchanjingyu': [
    { char: '獦狚', pinyin: 'gé dàn', meaning: '一种犬类动物，禅宗用来比喻呆坐无心的状态' },
    { char: '謦欬', pinyin: 'qǐng kài', meaning: '咳嗽声，比喻发出声响' },
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面' },
    { char: '颟顸儱侗', pinyin: 'mān hān lǒng tǒng', meaning: '糊涂含混、笼统不清的样子' },
    { char: '畗塞', pinyin: 'bó sè', meaning: '充满塞满，形容疑情充塞虚空' },
    { char: '黧奴', pinyin: 'lí nú', meaning: '黑猫，禅宗比喻疑情紧盯不放' },
    { char: '伽陀', pinyin: 'qié tuó', meaning: '佛经中的偈颂、药方' },
    { char: '曲彔', pinyin: 'qū lù', meaning: '曲录床，禅僧坐的交椅' },
    { char: '拶', pinyin: 'zā', meaning: '逼迫、紧压，禅宗指逼拶话头' },
    { char: '蒺蔾', pinyin: 'jí lí', meaning: '蒺藜，带刺的植物，比喻险难境遇' },
    { char: '泮然', pinyin: 'pàn rán', meaning: '消融、消散的样子' },
    { char: '觏', pinyin: 'gòu', meaning: '遇见、见到' },
    { char: '恁么', pinyin: 'nèn me', meaning: '这样、如此，禅宗常用语' },
    { char: '卜度', pinyin: 'bǔ duó', meaning: '揣测、臆度' },
    { char: '觑', pinyin: 'qù', meaning: '看、窥视' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒、明白，禅宗指灵觉不昧' },
    { char: '瞰', pinyin: 'kàn', meaning: '窥视、盯视，贼瞰巨室即贼窥大户' },
    { char: '橐', pinyin: 'tuó', meaning: '袋子，橐为之倾即家当被搬空' },
    { char: '柝', pinyin: 'tuò', meaning: '巡夜敲击的梆子，严城击柝喻警备' },
    { char: '栗棘蓬', pinyin: 'lì jí péng', meaning: '带刺的栗壳，禅林喻吞不下吐不出的公案' },
    { char: '肱', pinyin: 'gōng', meaning: '手臂，三折肱为良医喻阅历多方能知病' },
    { char: '膺', pinyin: 'yīng', meaning: '胸口，碍膺之物即堵在胸口的疑团' },
    { char: '遏捺', pinyin: 'è nà', meaning: '压抑、按捺，遏捺妄心即强行压住念头' },
    { char: '蠓', pinyin: 'měng', meaning: '蠓虫，微小飞虫，如蠓入猛焰喻妄念遇智火' },
    { char: '醭', pinyin: 'bú', meaning: '白醭，口边生的白膜，从教白醭口边生喻苦参' },
    { char: '庠', pinyin: 'xiáng', meaning: '安详，举止安庠即行止安详稳重' },
    { char: '觔斗', pinyin: 'jīn dǒu', meaning: '筋斗、跟头，万仞岩头翻觔斗喻悟后转身' },
    { char: '髭', pinyin: 'zī', meaning: '嘴上边的胡须，髭须可鉴喻水清可照' },
    { char: '聩', pinyin: 'kuì', meaning: '耳聋，耳聩眼朦胧喻年老昏聩' },
    { char: '痫', pinyin: 'xián', meaning: '癫痫，如发痫病喻识神颠倒之态' },
    { char: '铛', pinyin: 'chēng', meaning: '锅，猛火热油铛喻功夫紧迫' },
    { char: '坌', pinyin: 'bèn', meaning: '尘土聚积，旋坌喻尘劳纷纷围拢' },
    { char: '漭漭', pinyin: 'mǎng mǎng', meaning: '广大空旷貌，漭漭荡荡喻心量无拘' },
  ],
  'caoshanyulu': [
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面' },
    { char: '黧奴', pinyin: 'lí nú', meaning: '黑猫，禅宗比喻疑情紧盯不放' },
    { char: '髑髅', pinyin: 'dú lóu', meaning: '头骨、骷髅，禅宗喻无分别识' },
    { char: '攒簇', pinyin: 'cuán cù', meaning: '聚集、凑集，禅宗指把捉、凑合' },
    { char: '白牯', pinyin: 'bái gǔ', meaning: '白色的牯牛，禅宗喻无知的异类' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语阿阇黎的略称，意为轨范师' },
    { char: '恁么', pinyin: 'nèn me', meaning: '这样、如此，禅宗常用语' },
    { char: '卜度', pinyin: 'bǔ duó', meaning: '揣测、臆度' },
    { char: '椑树', pinyin: 'bēi shù', meaning: '椑树，禅僧名' },
    { char: '俸', pinyin: 'fèng', meaning: '俸禄、薪俸' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒、明白，禅宗指灵觉不昧' },
  ],
  'fayanyulu': [
    { char: '啗啄', pinyin: 'dàn zhuó', meaning: '咬啄，比喻言语交涉、机锋对答' },
    { char: '觌面', pinyin: 'dí miàn', meaning: '当面、面对面' },
    { char: '拶', pinyin: 'zā', meaning: '逼迫、紧压，禅宗指逼拶话头' },
    { char: '椓', pinyin: 'zhuó', meaning: '敲击' },
    { char: '踅', pinyin: 'xué', meaning: '来回走动' },
    { char: '髑髅', pinyin: 'dú lóu', meaning: '头骨、骷髅，禅宗喻无分别识' },
    { char: '謇', pinyin: 'jiǎn', meaning: '口吃、说话困难' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '梵语阿阇黎的略称，意为轨范师' },
    { char: '恁么', pinyin: 'nèn me', meaning: '这样、如此，禅宗常用语' },
    { char: '的的是', pinyin: 'dì dì shì', meaning: '确确实实、明明白白' },
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '头至手或地，佛教礼节' },
    { char: '斟酌', pinyin: 'zhēn zhuó', meaning: '思量、考虑，禅宗指卜度分别' },
    { char: '沂', pinyin: 'yí', meaning: '沂水，地名' },
    { char: '镬', pinyin: 'huò', meaning: '大锅' },
    { char: '馐', pinyin: 'xiū', meaning: '美食、佳肴' },
    { char: '攒', pinyin: 'cuán', meaning: '聚拢、凑集' },
    { char: '觑', pinyin: 'qù', meaning: '看、窥视' },
    { char: '跣足', pinyin: 'xiǎn zú', meaning: '赤脚' },
    { char: '飏', pinyin: 'yáng', meaning: '飞扬、扬起' },
    { char: '辊', pinyin: 'gǔn', meaning: '滚动、滚转' },
    { char: '绣毬', pinyin: 'xiù qiú', meaning: '绣球，法演喻禅机活泼' },
    { char: '巴鼻', pinyin: 'bā bí', meaning: '把柄、根据，禅宗指入手处' },
    { char: '惺惺', pinyin: 'xīng xīng', meaning: '清醒、明白，禅宗指灵觉不昧' },
    { char: '葛怛', pinyin: 'gé dá', meaning: '粗糙的葛布，法演山居诗中指粗陋的枕头' },
    { char: '泗洲', pinyin: 'sì zhōu', meaning: '地名，法演诗中引用大圣参拜之典' },
    { char: '叮咽', pinyin: 'dīng yè', meaning: '絮叨、叮咛' },
    { char: '柴棚', pinyin: 'chái péng', meaning: '柴草搭的棚子' },
  ],
  'zhonglun': [
    { char: '偈', pinyin: 'jì', meaning: '佛经中的颂诗、诗偈，通常为四句' },
    { char: '瞿昙', pinyin: 'qú tán', meaning: '佛陀的姓氏，也代指佛陀' },
    { char: '稽首', pinyin: 'qǐ shǒu', meaning: '头至手或地，佛教最敬礼' },
    { char: '因缘', pinyin: 'yīn yuán', meaning: '佛教核心概念，指事物生起的条件' },
    { char: '二谛', pinyin: 'èr dì', meaning: '世俗谛与第一义谛，佛教真理的两个层次' },
    { char: '四句', pinyin: 'sì jù', meaning: '有、无、亦有亦无、非有非无，龙树破斥的四种边见' },
    { char: '中道', pinyin: 'zhōng dào', meaning: '不落空有二边的正见，佛教的核心义理' },
    { char: '缘起', pinyin: 'yuán qǐ', meaning: '因缘和合而生起，佛教对事物存在方式的解释' },
    { char: '不生不灭', pinyin: 'bù shēng bù miè', meaning: '八不中道之一，破除一切执取生灭之戏论' },
    { char: '戏论', pinyin: 'xì lùn', meaning: '违背诸法实相的无益言论与虚妄分别' },
    { char: '自性', pinyin: 'zì xìng', meaning: '事物的独立、固有、不变的自体，中观破斥之' },
    { char: '假名', pinyin: 'jiǎ míng', meaning: '依因缘和合而假立的名字与概念' },
  ],
  'wanshantongguiji': [
    { char: '阂', pinyin: 'ài', meaning: '阻碍、妨碍。理事无阂即理事互不妨碍' },
    { char: '翳', pinyin: 'yì', meaning: '遮蔽、蒙蔽。如“久翳尘劳”' },
    { char: '莹彻', pinyin: 'yíng chè', meaning: '晶莹透彻，明净照彻' },
    { char: '醍醐', pinyin: 'tí hú', meaning: '从乳中提炼的至甘精华，比喻至高圆顿之佛性法味' },
    { char: '遮诠', pinyin: 'zhē quán', meaning: '从否定与破执层面表述真理（如“非心非佛”），与“表诠”相对' },
    { char: '表诠', pinyin: 'biǎo quán', meaning: '从正面直接显发指陈真理（如“即心即佛”），与“遮诠”相对' },
    { char: '秖', pinyin: 'zhǐ', meaning: '古同“只”，仅仅、只管' },
    { char: '阇黎', pinyin: 'shé lí', meaning: '阿阇梨简称，意为轨范师、教授师' },
    { char: '水月道场', pinyin: 'shuǐ yuè dào chǎng', meaning: '比喻虽知一切道场如水中月幻化无实，仍大作佛事庄严修持' },
    { char: '实相', pinyin: 'shí xiàng', meaning: '一切诸法真实不变之本体，离一切虚妄之相' },
  ],
  'chanyuan_zhuquanjiduxu': [
    { char: '户牖', pinyin: 'hù yǒu', meaning: '门窗，喻各宗自立门户' },
    { char: '纷拏', pinyin: 'fēn ná', meaning: '纷争纠缠' },
    { char: '疑曀', pinyin: 'yí yì', meaning: '疑云遮蔽，如阴翳蔽日' },
    { char: '劬劳', pinyin: 'qú láo', meaning: '辛勤劳苦' },
    { char: '金鍮', pinyin: 'jīn tōu', meaning: '金与鍮石（似金之铜），喻真伪难辨' },
    { char: '漭荡', pinyin: 'mǎng dàng', meaning: '广大空旷貌' },
    { char: '礭', pinyin: 'què', meaning: '同确，坚定、确实之意' },
    { char: '毱多', pinyin: 'jú duō', meaning: '禅宗祖师之名（提多迦后承者）' },
    { char: '罽宾', pinyin: 'jì bīn', meaning: '古西域国名，迦湿弥罗' },
    { char: '南侁', pinyin: 'nán shēn', meaning: '指智侁禅师一系，禅门南宗一派' },
    { char: '镮钏', pinyin: 'huán chuàn', meaning: '手镯与臂钏，喻器物各异金体是一' },
    { char: '纥利陀耶', pinyin: 'hé lì tuó yē', meaning: '梵语，肉团心（心脏）之音译' },
    { char: '质多耶', pinyin: 'zhì duō yē', meaning: '梵语，集起心，指第八识' },
    { char: '干栗陀耶', pinyin: 'gān lì tuó yē', meaning: '梵语，坚实心，指真心' },
    { char: '胜鬘', pinyin: 'shèng mán', meaning: '胜鬘夫人，《胜鬘经》主名' },
    { char: '憍陈如', pinyin: 'jiāo chén rú', meaning: '佛陀初度五比丘之首' },
    { char: '波罗㮈', pinyin: 'bō luó nài', meaning: '波罗㮈国，鹿野苑所在' },
    { char: '师子频呻', pinyin: 'shī zǐ pín shēn', meaning: '师子频呻三昧，佛入此定大众证法界' },
    { char: '麁', pinyin: 'cū', meaning: '同粗' },
    { char: '粝飡', pinyin: 'lì cān', meaning: '粗米饭食' },
    { char: '菽麦', pinyin: 'shū mài', meaning: '豆与麦，喻基本之分辨' },
    { char: '昭穆', pinyin: 'zhāo mù', meaning: '宗法制度中的辈分次序' },
    { char: '病差', pinyin: 'chài', meaning: '病愈；差通瘥' },
    { char: '礭言', pinyin: 'què yán', meaning: '确定之言（确言）' },
  ],
  'biyanlu': [
    { char: '髑髅', pinyin: 'dú lóu', meaning: '骷髅，死人头骨，禅语中指情识尽处' },
    { char: '羝羊触藩', pinyin: 'dī yáng chù fān', meaning: '公羊角挂篱笆，进退两难' },
    { char: '醯鸡蠛蠓', pinyin: 'xī jī miè měng', meaning: '醋瓮里的小虫，喻极微细之生灵' },
    { char: '楖栗', pinyin: 'jí lì', meaning: '禅杖，木名，可为杖' },
    { char: '挨拶', pinyin: 'āi zā', meaning: '逼迫挤压，宗师勘验学人的手段' },
    { char: '牸牛', pinyin: 'zì niú', meaning: '母牛' },
    { char: '鳖鼻蛇', pinyin: 'biē bí shé', meaning: '剧毒之蛇，喻公案凶险' },
    { char: '掠虚头', pinyin: 'lüè xū tóu', meaning: '弄虚头、不实落，掠取虚名' },
    { char: '担板汉', pinyin: 'dān bǎn hàn', meaning: '扛木板的人，喻只见一边不见全局' },
    { char: '颟顸', pinyin: 'mān hān', meaning: '糊涂马虎、不明事理' },
    { char: '鹘', pinyin: 'hú', meaning: '隼类猛禽，搏击迅速' },
    { char: '麈', pinyin: 'zhǔ', meaning: '鹿中之王，其尾可制拂尘' },
    { char: '挃', pinyin: 'zhì', meaning: '撞击、捣击' },
    { char: '禳', pinyin: 'ráng', meaning: '祭祷消灾' },
    { char: '窠窟', pinyin: 'kē kū', meaning: '巢穴，喻情识见解的窠臼' },
    { char: '葛藤', pinyin: 'gé téng', meaning: '藤蔓缠绕，喻言语知解纠缠' },
    { char: '盂', pinyin: 'yú', meaning: '盛饮食的圆口器皿' },
    { char: '阃', pinyin: 'kǔn', meaning: '门槛' },
    { char: '霹雳', pinyin: 'pī lì', meaning: '疾雷' },
    { char: '拗', pinyin: 'ǎo', meaning: '折断' },
    { char: '鍮', pinyin: 'tōu', meaning: '黄铜似金者' },
    { char: '摵', pinyin: 'shè', meaning: '击打声' },
    { char: '捩', pinyin: 'liè', meaning: '扭转' },
    { char: '幞', pinyin: 'fú', meaning: '包头软巾' },
    { char: '蟭螟', pinyin: 'jiāo míng', meaning: '极微小的虫' },
    { char: '鼈', pinyin: 'biē', meaning: '同鳖' },
    { char: '拕', pinyin: 'tuō', meaning: '同拖' },
    { char: '邈', pinyin: 'miǎo', meaning: '描绘' },
  ],
  'yangqihoulu': [
    { char: '趺', pinyin: 'fū', meaning: '盘腿端坐，趺座即结跏趺坐' },
    { char: '槌', pinyin: 'chuí', meaning: '棒槌，维那白槌即鸣槌示意' },
    { char: '洎', pinyin: 'jì', meaning: '及、至，此处意为连同' },
    { char: '俾', pinyin: 'bǐ', meaning: '使、让' },
    { char: '阇', pinyin: 'dū', meaning: '阇梨，梵语阿阇梨，指有德行的僧人' },
    { char: '杓', pinyin: 'sháo', meaning: '勺子，瓢勺' },
    { char: '璏', pinyin: 'jué', meaning: '人名用字' },
    { char: '摵', pinyin: 'shè', meaning: '击打声，摵一摵即击打一下' },
    { char: '捩', pinyin: 'liè', meaning: '扭转，捩转面即转过脸去' },
    { char: '幞', pinyin: 'fú', meaning: '包头软巾，幞头为古代头巾' },
    { char: '蟭螟', pinyin: 'jiāo míng', meaning: '极微小的虫' },
    { char: '鼈', pinyin: 'biē', meaning: '同鳖' },
    { char: '拕', pinyin: 'tuō', meaning: '同拖，拖拽' },
    { char: '邈', pinyin: 'miǎo', meaning: '描绘，写真' },
    { char: '鍮', pinyin: 'tōu', meaning: '黄铜似金者，金鍮不辨即真假不分' },
    { char: '鹘', pinyin: 'hú', meaning: '隼类猛禽，辽天鹘比喻迅捷' },
    { char: '斫', pinyin: 'zhuó', meaning: '砍、削' },
    { char: '鹄', pinyin: 'gǔ', meaning: '同鹘，猛禽' },
  ],
  'linjianhoulu': [
    { char: '栢', pinyin: 'bǎi', meaning: '同柏，枣栢为李通玄之号' },
    { char: '翛', pinyin: 'xiāo', meaning: '翛然，无拘无束貌' },
    { char: '跣', pinyin: 'xiǎn', meaning: '赤脚' },
    { char: '伽棃', pinyin: 'qié lí', meaning: '僧衣，袈裟之别称' },
    { char: '睥睨', pinyin: 'pì nì', meaning: '斜视，傲视' },
    { char: '匡床', pinyin: 'kuāng chuáng', meaning: '方正的床' },
    { char: '旃檀', pinyin: 'zhān tán', meaning: '檀香，梵语candana音译' },
    { char: '彖', pinyin: 'tuàn', meaning: '《易经》中统括一卦之辞' },
    { char: '挝', pinyin: 'wō', meaning: '敲击' },
    { char: '殒', pinyin: 'yǔn', meaning: '坠落、消殒' },
    { char: '醯', pinyin: 'xī', meaning: '摩醯首罗，大自在天' },
    { char: '棃', pinyin: 'lí', meaning: '同梨' },
    { char: '馎饦', pinyin: 'bó tuō', meaning: '汤饼，面食' },
    { char: '踔', pinyin: 'chuō', meaning: '跳跃' },
    { char: '鲲鹏', pinyin: 'kūn péng', meaning: '庄子寓言中的大鱼大鸟' },
    { char: '兜率', pinyin: 'dōu lǜ', meaning: '兜率天，弥勒菩萨所居天宫' },
    { char: '馎', pinyin: 'bó', meaning: '馎饦，面食' },
    { char: '槌', pinyin: 'chuí', meaning: '棒槌' },
    { char: '僵仆', pinyin: 'jiāng pū', meaning: '倒地' },
    { char: '粲', pinyin: 'càn', meaning: '鲜明、灿烂' },
  ],
  'shanglibian': [
    { char: '蠛蠓', pinyin: 'miè měng', meaning: '微小的飞虫，喻渺小' },
    { char: '睽', pinyin: 'kuí', meaning: '背离、违背' },
    { char: '憍倨', pinyin: 'jiāo jù', meaning: '骄傲自大' },
    { char: '荧惑', pinyin: 'yíng huò', meaning: '迷惑、惑乱' },
    { char: '俚', pinyin: 'lǐ', meaning: '粗俗、鄙陋' },
    { char: '闾阎', pinyin: 'lǘ yán', meaning: '民间、乡里' },
    { char: '隲', pinyin: 'zhì', meaning: '评定、安排' },
    { char: '隲德', pinyin: 'zhì dé', meaning: '阴德' },
    { char: '隳', pinyin: 'huī', meaning: '毁坏' },
    { char: '隤', pinyin: 'tuí', meaning: '坠落' },
    { char: '隤然', pinyin: 'tuí rán', meaning: '颓倒貌' },
    { char: '爇', pinyin: 'ruò', meaning: '点燃、焚烧' },
    { char: '杻械', pinyin: 'chǒu xiè', meaning: '刑具枷锁' },
    { char: '煨烬', pinyin: 'wēi jìn', meaning: '灰烬' },
    { char: '消殒', pinyin: 'xiāo yǔn', meaning: '消亡殒灭' },
    { char: '牯', pinyin: 'gǔ', meaning: '水牯牛即水牛' },
    { char: '摝', pinyin: 'lù', meaning: '捞取，河里失钱河里摝' },
    { char: '拕', pinyin: 'tuō', meaning: '同拖，横拕倒拽' },
    { char: '踣', pinyin: 'bó', meaning: '跌倒，踣跳即跳跃' },
    { char: '噇', pinyin: 'chuáng', meaning: '狂吃猛喝，噇眠即贪吃贪睡' },
    { char: '嚗', pinyin: 'bō', meaning: '嚗嚗，干硬貌' },
    { char: '鏴', pinyin: 'lù', meaning: '看锢鏴，指看偏了' },
    { char: '锢', pinyin: 'gù', meaning: '锢鏴，偏差不通' },
    { char: '蒺', pinyin: 'jí', meaning: '蒺藜，带刺植物' },
    { char: '藜', pinyin: 'lí', meaning: '蒺藜，带刺植物' },
    { char: '嬭', pinyin: 'nǎi', meaning: '同奶，兔子吃牛嬭' },
    { char: '槌', pinyin: 'chuí', meaning: '木槌，白槌即敲槌宣布' },
    { char: '筵', pinyin: 'yán', meaning: '筵席，法筵即法席' },
    { char: '椁', pinyin: 'guǒ', meaning: '棺椁，外棺' },
    { char: '趺', pinyin: 'fū', meaning: '双趺，双脚盘坐' },
    { char: '搥', pinyin: 'chuí', meaning: '搥胸，捶胸' },
    { char: '飨', pinyin: 'xiǎng', meaning: '伏惟尚飨，祭奠用语' },
    { char: '苾', pinyin: 'bì', meaning: '苾刍即比丘' },
    { char: '刍', pinyin: 'chú', meaning: '苾刍即比丘' },
    { char: '崄', pinyin: 'xiǎn', meaning: '同险，山势崄即山势险峻' },
    { char: '杪', pinyin: 'miǎo', meaning: '三春将杪，即春末' },
    { char: '粜', pinyin: 'tiào', meaning: '和麸粜面，即卖面' },
    { char: '麸', pinyin: 'fū', meaning: '麸皮，和麸粜面' },
    { char: '磕', pinyin: 'kē', meaning: '磕额，叩头至地' },
    { char: '攒', pinyin: 'cuán', meaning: '孤轮众象攒，众象聚集' },
    { char: '翛', pinyin: 'xiāo', meaning: '翛然，自由自在貌' },
    { char: '鼈', pinyin: 'biē', meaning: '同鳖，巨鼈即大鳖' },
    { char: '馌', pinyin: 'yè', meaning: '给耕作者送饭' },
  ],
  'yangqiyulu': [
    { char: '拕', pinyin: 'tuō', meaning: '同拖，拕倒拽即拖拽' },
    { char: '崄', pinyin: 'xiǎn', meaning: '同险，山势崄即山势险峻' },
    { char: '摝', pinyin: 'lù', meaning: '捞取，河里失钱河里摝' },
    { char: '噇', pinyin: 'chuáng', meaning: '大口吃，爱噇眠即爱吃睡' },
    { char: '踣', pinyin: 'bó', meaning: '跌倒，踣跳即跳跃' },
    { char: '覰', pinyin: 'qù', meaning: '窥视，觑破即看破' },
    { char: '𫍢', pinyin: 'chán', meaning: '多言，𫍢讹即差错' },
    { char: '拗', pinyin: 'ǎo', meaning: '折断，拗折秤衡' },
    { char: '咤', pinyin: 'zhà', meaning: '怒吼，咤沙即粗鲁' },
    { char: '朔', pinyin: 'shuò', meaning: '北方，眉毛卓朔即竖起' },
    { char: '䬪', pinyin: 'bó', meaning: '䬪饦，即汤饼' },
    { char: '踣跳', pinyin: 'bó tiào', meaning: '跳跃，禅门指机锋跃动' },
    { char: '葛藤', pinyin: 'gé téng', meaning: '禅门指语言文字的纠缠' },
    { char: '白槌', pinyin: 'bái chuí', meaning: '维那鸣槌宣布开法' },
    { char: '展钵', pinyin: 'zhǎn bō', meaning: '展开钵盂准备进食' },
    { char: '苾刍', pinyin: 'bì chú', meaning: '比丘，出家僧人' },
    { char: '疏', pinyin: 'shū', meaning: '疏文，寺院宣读的文书' },
    { char: '真', pinyin: 'zhēn', meaning: '画像，挂真即悬挂遗像' },
    { char: '忌晨', pinyin: 'jì chén', meaning: '忌日，祖师圆寂纪念日' },
    { char: '坐具', pinyin: 'zuò jù', meaning: '僧人随身携带的布垫' },
  ],
  'chanzongjueyiji': [
    { char: '衲', pinyin: 'nà', meaning: '僧人自称，野衲即山野僧人' },
    { char: '迤逦', pinyin: 'yǐ lǐ', meaning: '曲折前行，一路行走' },
    { char: '夔府', pinyin: 'kuí fǔ', meaning: '古地名，今重庆奉节一带' },
    { char: '澹泊', pinyin: 'dàn bó', meaning: '恬淡寡欲，不慕荣利' },
    { char: '担板汉', pinyin: 'dān bǎn hàn', meaning: '扛板之人，喻执固一端者' },
    { char: '长连床', pinyin: 'cháng lián chuáng', meaning: '禅堂中的长条坐床' },
    { char: '辘辘', pinyin: 'lù lù', meaning: '转动灵活貌，活辘辘即活泼自在' },
    { char: '蹴毬', pinyin: 'cù qiú', meaning: '踢球，喻工夫灵活自如' },
    { char: '罣碍', pinyin: 'guà ài', meaning: '牵挂障碍，同挂碍' },
    { char: '阴翊', pinyin: 'yīn yì', meaning: '暗中辅佐护持' },
    { char: '悭贪', pinyin: 'qiān tān', meaning: '吝啬贪婪' },
    { char: '波罗提木叉', pinyin: 'bō luó tí mù chā', meaning: '戒律，意为别解脱' },
    { char: '二六时中', pinyin: 'èr liù shí zhōng', meaning: '一昼夜十二时辰中，即全天' },
    { char: '五体投地', pinyin: 'wǔ tǐ tóu dì', meaning: '双肘双膝及头着地，最敬礼' },
    { char: '发露', pinyin: 'fā lù', meaning: '坦白表露，发露忏悔即公开忏悔' },
    { char: '镴', pinyin: 'là', meaning: '锡铅合金，喻不结实之物' },
    { char: '钉桩摇橹', pinyin: 'dīng zhuāng yáo lǔ', meaning: '钉住桩子摇橹，喻执一不通' },
    { char: '炉鞴', pinyin: 'lú bèi', meaning: '冶炉鼓风设备，喻锻炼学人' },
    { char: '落索', pinyin: 'luò suǒ', meaning: '啰嗦，一番话语' },
    { char: '优昙华', pinyin: 'yōu tán huá', meaning: '优昙钵罗花，三千年一现，喻极稀有' },
  ],
  'huanglonghuinan': [
    { char: '獬豸', pinyin: 'xiè zhì', meaning: '古代传说中的异兽，能辨是非，喻刚直之人' },
    { char: '白槌', pinyin: 'bái chuí', meaning: '打白槌，禅林开堂时维那敲槌宣布规矩' },
    { char: '啐啄', pinyin: 'cuì zhuó', meaning: '雏鸟欲出时母鸟啄壳，喻师弟机锋相应' },
    { char: '阇梨', pinyin: 'shé lí', meaning: '梵语阿阇梨的略称，意为轨范师' },
    { char: '拕', pinyin: 'tuō', meaning: '同拖，拉拽' },
    { char: '搊', pinyin: 'chōu', meaning: '抓取，揪住' },
    { char: '掴', pinyin: 'guó', meaning: '用巴掌打，掴一掴即打一耳光' },
    { char: '馎饦', pinyin: 'bó tuō', meaning: '古代面食，类似汤饼' },
    { char: '粜', pinyin: 'tiào', meaning: '卖出粮食' },
    { char: '蹉过', pinyin: 'cuō guò', meaning: '错过，失误' },
    { char: '鈯斧', pinyin: 'tú fǔ', meaning: '钝斧头，喻钝根学人' },
    { char: '撗破', pinyin: 'pī pò', meaning: '劈开，剖破' },
    { char: '毬', pinyin: 'qiú', meaning: '同球，皮球' },
    { char: '镆鎁', pinyin: 'mò yé', meaning: '古代宝剑名，喻锋利之机' },
    { char: '幞头', pinyin: 'fú tóu', meaning: '古代男子头巾' },
    { char: '笊篱', pinyin: 'zhào lí', meaning: '竹编捞具，庞居士卖笊篱公案' },
    { char: '嗄嗄', pinyin: 'shà shà', meaning: '笑声' },
    { char: '刢利', pinyin: 'líng lì', meaning: '伶俐，聪明利索' },
    { char: '蹔', pinyin: 'zàn', meaning: '同暂，暂时' },
    { char: '夤缘', pinyin: 'yín yuán', meaning: '攀附连缘，向上攀爬' },
  ],
  'zhaolun': [
    { char: '沤和', pinyin: 'ōu hé', meaning: '梵语upāya音译，方便善巧，菩萨度生的权智' },
    { char: '般若', pinyin: 'bō rě', meaning: '梵语prajñā音译，通达诸法实相的智慧' },
    { char: '涅槃', pinyin: 'niè pán', meaning: '梵语nirvāṇa音译，烦恼灭尽、生死解脱的究竟境界' },
    { char: '缘会', pinyin: 'yuán huì', meaning: '因缘聚会，诸法生起的条件' },
    { char: '实相', pinyin: 'shí xiàng', meaning: '诸法真实的相状，即空性' },
    { char: '法性', pinyin: 'fǎ xìng', meaning: '一切法的本性，即空性' },
    { char: '性空', pinyin: 'xìng kōng', meaning: '诸法自性本空，非分析方空' },
    { char: '本无', pinyin: 'běn wú', meaning: '万物本来自无，非推之使无' },
    { char: '二谛', pinyin: 'èr dì', meaning: '真谛与俗谛，佛法的两层真理' },
    { char: '三乘', pinyin: 'sān chéng', meaning: '声闻、缘觉、菩萨三乘，佛为不同根机所说' },
    { char: '五阴', pinyin: 'wǔ yīn', meaning: '色受想行识，即五蕴，构成身心的五种要素' },
    { char: '六入', pinyin: 'liù rù', meaning: '六根入于六境，眼耳鼻舌身意' },
    { char: '八解', pinyin: 'bā jiě', meaning: '八解脱，八种禅定解脱法门' },
    { char: '七觉', pinyin: 'qī jué', meaning: '七觉支，七种觉悟的要素' },
    { char: '三明', pinyin: 'sān míng', meaning: '天眼明、宿命明、漏尽明，三种智慧' },
    { char: '六通', pinyin: 'liù tōng', meaning: '六种神通：天眼、天耳、他心、宿命、神足、漏尽' },
    { char: '四流', pinyin: 'sì liú', meaning: '见流、欲流、有流、无明流，四种烦恼流' },
    { char: '三无为', pinyin: 'sān wú wéi', meaning: '虚空、数缘尽（择灭）、非数缘尽（非择灭）' },
    { char: '结习', pinyin: 'jié xí', meaning: '烦恼习气，残余的执着' },
    { char: '无生忍', pinyin: 'wú shēng rěn', meaning: '忍可诸法本自无生之理，七地菩萨所证' },
    { char: '四谛', pinyin: 'sì dì', meaning: '苦集灭道四圣谛' },
    { char: '定慧', pinyin: 'dìng huì', meaning: '禅定与智慧，止观双运' },
    { char: '三毒', pinyin: 'sān dú', meaning: '贪嗔痴三种根本烦恼' },
    { char: '四倒', pinyin: 'sì dǎo', meaning: '四种颠倒见：非常计常、非乐计乐、非我计我、非净计净' },
    { char: '僧那', pinyin: 'sēng nà', meaning: '梵语sannāha，铠甲，指菩萨发心如披铠甲' },
    { char: '萨云', pinyin: 'sà yún', meaning: '萨云若，梵语sarvajña，一切智' },
    { char: '毘婆沙', pinyin: 'pí pó shā', meaning: '梵语vibhāṣā，广释经论的注释' },
    { char: '招提', pinyin: 'zhāo tí', meaning: '梵语caturdiśa，四方僧坊，小招提寺为慧达所在' },
    { char: '缁素', pinyin: 'zī sù', meaning: '僧人与俗人，缁为僧衣黑色，素为俗衣白色' },
    { char: '旋岚', pinyin: 'xuán lán', meaning: '梵语vairambha，猛风、劫风' },
    { char: '野马', pinyin: 'yě mǎ', meaning: '阳焰，热气如野马奔腾' },
    { char: '沤和般若', pinyin: 'ōu hé bō rě', meaning: '方便与般若，权智与实智' },
    { char: '九折十演', pinyin: 'jiǔ zhé shí yǎn', meaning: '涅槃无名论的结构：九次问难、十番演说' },
  ],
  'shangzhibian': [
    { char: '纡', pinyin: 'yū', meaning: '弯曲、曲折' },
    { char: '墙壍', pinyin: 'qiáng qiàn', meaning: '壕沟、壁垒，喻设障蔽' },
    { char: '逢蒙', pinyin: 'féng méng', meaning: '后羿弟子，学射后杀羿，喻背师反噬' },
    { char: '媸妍', pinyin: 'chī yán', meaning: '丑与美，喻是非真伪' },
    { char: '鬳齐', pinyin: 'yàn qí', meaning: '即鬳斋，林希逸之号' },
    { char: '虩虩', pinyin: 'xì xì', meaning: '恐惧貌，震来虩虩' },
    { char: '洊雷', pinyin: 'jiàn léi', meaning: '接连不断的雷' },
    { char: '阴骘', pinyin: 'yīn zhì', meaning: '暗中积累的德行' },
    { char: '皦', pinyin: 'jiǎo', meaning: '明亮、分明' },
    { char: '鱍鱍', pinyin: 'bō bō', meaning: '鱼跃貌，活鱍鱍地即活泼泼地' },
    { char: '垩', pinyin: 'è', meaning: '白土、白垩，垩人即圣人' },
    { char: '翊', pinyin: 'yì', meaning: '辅助、辅佐' },
    { char: '罹', pinyin: 'lí', meaning: '遭受、遭遇不幸' },
    { char: '蹇', pinyin: 'jiǎn', meaning: '困厄、不顺利' },
    { char: '夭阏', pinyin: 'yāo è', meaning: '中途夭折、受阻' },
    { char: '懵然', pinyin: 'měng rán', meaning: '不明、无知' },
    { char: '汩', pinyin: 'gǔ', meaning: '沉没、扰乱' },
    { char: '剽窃', pinyin: 'piāo qiè', meaning: '抄袭、窃取' },
    { char: '掊', pinyin: 'póu', meaning: '击、抨击' },
    { char: '隳', pinyin: 'huī', meaning: '毁坏' },
    { char: '豏', pinyin: 'xiàn', meaning: '酸豏，禅宗语，指难以吞咽之物' },
    { char: '鑊', pinyin: 'huò', meaning: '锅，古代的大锅' },
    { char: '鶻', pinyin: 'gǔ', meaning: '鹘，一种猛禽' },
    { char: '踒', pinyin: 'wō', meaning: '折断、扭伤' },
    { char: '鎰', pinyin: 'yì', meaning: '古代重量单位，二十两为一镒' },
    { char: '鎡', pinyin: 'zī', meaning: '鎡基，即锄头' },
    { char: '烜', pinyin: 'xuǎn', meaning: '显著、明亮' },
  ],
  'shishuangchuyuan': [
    { char: '楚圆', pinyin: 'chǔ yuán', meaning: '石霜楚圆（慈明禅师），临济宗杨岐、黄龙二派之源' },
    { char: '提撕', pinyin: 'tí sī', meaning: '提醒警觉，使心念时刻觉照不迷' },
    { char: '逼拶', pinyin: 'bī zǎ', meaning: '禅师以机锋逼迫学人至绝路以求彻悟' },
    { char: '啐啄', pinyin: 'cuì zhuó', meaning: '母鸡引雏与雏鸡出壳同时动作，喻师徒机缘契合' },
  ],
  'xuanshayulu': [
    { char: '师备', pinyin: 'shī bèi', meaning: '玄沙师备禅师，雪峰义存上足' },
    { char: '谛当', pinyin: 'dì dāng', meaning: '确凿、真实、不可动摇' },
    { char: '承当', pinyin: 'chéng dāng', meaning: '直下承担自性本体，无丝毫迟疑' },
    { char: '函盖', pinyin: 'hán gài', meaning: '包含包容，如盒与盖天然吻合' },
  ],
  'xuanshaguanglu': [
    { char: '举扬', pinyin: 'jǔ yáng', meaning: '提倡、宣扬宗门心法' },
    { char: '宗乘', pinyin: 'zōng chéng', meaning: '禅宗直指本心的最高教法' },
    { char: '拶勘', pinyin: 'zǎ kān', meaning: '逼迫勘验学人的悟境真伪' },
  ],
  'gaofengyulu': [
    { char: '原妙', pinyin: 'yuán miào', meaning: '高峰原妙禅师，元代临济宗巨匠' },
    { char: '死关', pinyin: 'sǐ guān', meaning: '修行者断除情识分别、置之死地而后生的关隘' },
    { char: '海底泥牛', pinyin: 'hǎi dǐ ní niú', meaning: '禅宗公案喻体，喻心体绝思绝虑、无迹可寻' },
  ],
  'xuefengyulu': [
    { char: '义存', pinyin: 'yì cún', meaning: '雪峰义存禅师，德山宣鉴法嗣，云门法眼之源' },
    { char: '辊球', pinyin: 'gǔn qiú', meaning: '雪峰接引学人之独特机锋施设' },
    { char: '鳖鼻', pinyin: 'biē bí', meaning: '南山鳖鼻蛇，雪峰用来逼拶学人的公案' },
  ],
  'foguojijielu': [
    { char: '克勤', pinyin: 'kè qín', meaning: '圆悟克勤（佛果禅师），《碧岩录》《击节录》作者' },
    { char: '击节', pinyin: 'jī jié', meaning: '打着节拍，赞叹评点古人公案妙趣' },
    { char: '机用', pinyin: 'jī yòng', meaning: '禅师随宜应机的大机大用' },
  ],
  'mianxianyulu': [
    { char: '咸杰', pinyin: 'xián jié', meaning: '密庵咸杰禅师，临济宗密庵派开山' },
    { char: '破庵', pinyin: 'pò ān', meaning: '破庵祖先，密庵法嗣' },
    { char: '垂示', pinyin: 'chuí shì', meaning: '禅师在方丈室中对学人的开示与勘验' },
  ],
  'zibaibieji': [
    { char: '真可', pinyin: 'zhēn kě', meaning: '紫柏真可（达观大师），明末四大高僧之一' },
    { char: '方册藏', pinyin: 'fāng cè zàng', meaning: '紫柏倡导刻印的线装大藏经（嘉兴藏）' },
    { char: '法眷', pinyin: 'fǎ juàn', meaning: '佛法上的法脉眷属与同修道友' },
  ],
  'renyantianmu': [
    { char: '揀', pinyin: 'jiǎn', meaning: '挑选、选择' },
    { char: '褫', pinyin: 'chǐ', meaning: '剥夺、除去' },
    { char: '誵', pinyin: 'xiáo', meaning: '誵讹，差错' },
    { char: '觌', pinyin: 'dí', meaning: '相见、见面' },
    { char: '镆', pinyin: 'mò', meaning: '镆铘，古代宝剑名' },
    { char: '铘', pinyin: 'yé', meaning: '镆铘，古代宝剑名' },
    { char: '殽', pinyin: 'yáo', meaning: '混杂' },
    { char: '钁', pinyin: 'jué', meaning: '锄头' },
    { char: '颋', pinyin: 'tǐng', meaning: '直、自在' },
  ],
  'linjianlu': [
    { char: '惠洪', pinyin: 'huì hóng', meaning: '宋代著名禅僧德洪惠洪（觉范）' },
    { char: '丛林', pinyin: 'cóng lín', meaning: '禅宗大型寺院僧团之通称' },
    { char: '林间', pinyin: 'lín jiān', meaning: '指禅林、僧堂之间的逸闻与道话' },
  ],
  'lengqiejing': [
    { char: '阿跋多罗', pinyin: 'ā bá duō luó', meaning: '梵语入、趣入之意' },
    { char: '如来藏', pinyin: 'rú lái zàng', meaning: '众生本具的自性清净心，被客尘覆蔽之体' },
    { char: '藏识', pinyin: 'zàng shí', meaning: '即阿赖耶识，含藏一切善恶种子' },
    { char: '转识', pinyin: 'zhuǎn shí', meaning: '由藏识变现依缘而起的前七识' },
  ],
  'chanyuanqinggui': [
    { char: '宗赜', pinyin: 'zōng zé', meaning: '长芦宗赜禅师，《禅苑清规》编撰者' },
    { char: '维那', pinyin: 'wéi nà', meaning: '寺院纲领执事之一，掌管僧众规矩与法事' },
    { char: '典座', pinyin: 'diǎn zuò', meaning: '寺院中执掌大众斋食烹饪的执事' },
    { char: '普请', pinyin: 'pǔ qǐng', meaning: '全寺上下不分尊卑共同劳作出坡之法' },
  ],
  'chixiu-baizhang-qinggui': [
    { char: '犍椎', pinyin: 'jiān zhuī', meaning: '梵语犍稚，寺院聚集大众所鸣之钟、磬、木鱼、鼓等发声之法器' },
    { char: '茶毘', pinyin: 'chá pí', meaning: '梵语，即火葬、焚化僧人遗体之仪式' },
    { char: '剳', pinyin: 'zhá', meaning: '抄剳、剳付，抄录登记或官府下达文书' },
    { char: '趺坐', pinyin: 'fū zuò', meaning: '跏趺坐，双盘或单盘端坐修禅' },
    { char: '䞋', pinyin: 'qián', meaning: '俵䞋、下䞋，施舍或分发钱物以作供养' },
    { char: '铙钹', pinyin: 'náo bó', meaning: '打击法器，铜制圆盘，用于迎请、送亡等佛事' },
    { char: '椸', pinyin: 'yí', meaning: '椸架，禅堂中用于悬挂衣服、袈裟等道具之木架' },
    { char: '祲', pinyin: 'jìn', meaning: '不祥之气、妖气、浊气' },
    { char: '霶𩃱', pinyin: 'pāng tuó', meaning: '雨水盛大貌，祈雨祈求甘霖之词' },
    { char: '砧基', pinyin: 'zhēn jī', meaning: '砧基簿，寺院记载田地房产户籍所有权之册籍' },
    { char: '秉拂', pinyin: 'bǐng fú', meaning: '首座或名德代住持持拂子升座说法' },
  ],
  'jingangge': [
    { char: '本觉', pinyin: 'běn jué', meaning: '众生自性本具之清净觉性，非修得' },
    { char: '任运', pinyin: 'rèn yùn', meaning: '自然而然，不加勉强与造作' },
    { char: '明空', pinyin: 'míng kōng', meaning: '心性光明与空性无二无别之状态' },
  ],
  'ziwojietuo': [
    { char: '莲花生', pinyin: 'lián huā shēng', meaning: '藏传佛教宁玛派祖师，大圆满法之传布者' },
    { char: '本净', pinyin: 'běn jìng', meaning: '心性从本以来清净无染' },
    { char: '妥噶', pinyin: 'tuǒ gá', meaning: '大圆满修行之顿超法门' },
  ],
  'songlingbaoxun': [
    { char: '益西措嘉', pinyin: 'yì xī cuò jiā', meaning: '莲花生大士明妃与上首弟子' },
    { char: '空行母', pinyin: 'kōng xíng mǔ', meaning: '梵语荼吉尼，护持甚深智慧法门之圣者' },
    { char: '甚深', pinyin: 'shèn shēn', meaning: '佛法义理幽微深远、不可思议' },
  ],
  'xizangduwangjing': [
    { char: '中阴', pinyin: 'zhōng yīn', meaning: '前一生死后至下一生投胎之间的过渡阶段（中有）' },
    { char: '闻解脱', pinyin: 'wén jiě tuō', meaning: '仅凭听闻甚深教法法音即可在中阴身获得解脱' },
    { char: '本尊', pinyin: 'běn zūn', meaning: '修行者所依止修持的特定佛菩萨形象' },
  ],
  'xinxingxiuxisong': [
    { char: '龙钦巴', pinyin: 'lóng qīn bā', meaning: '藏传佛教大圆满法集大成者（无垢光尊者）' },
    { char: '心性', pinyin: 'xīn xìng', meaning: '心的本来面目与空明本体' },
    { char: '自性大圆满', pinyin: 'zì xìng dà yuán mǎn', meaning: '一切诸法在心性本觉中本来圆满无缺' },
  ],
  'henghedashouyin': [
    { char: '帝洛巴', pinyin: 'dì luò bā', meaning: '印度八十四大成就者之一，大手印传承祖师' },
    { char: '那洛巴', pinyin: 'nà luò bā', meaning: '帝洛巴上足弟子，藏传噶举派之源' },
    { char: '大手印', pinyin: 'dà shǒu yìn', meaning: '直观心性明空不二、任运解脱之法门' },
  ],
  'zixingcanjiu': [
    { char: '拉玛那', pinyin: 'lā mǎ nà', meaning: '拉玛那·马哈希，现代印度非二元智者' },
    { char: '参究', pinyin: 'cān jiū', meaning: '向内追问“我是谁”，直至自我认同彻底消融' },
    { char: '阿鲁那查拉', pinyin: 'ā lǔ nà chá lā', meaning: '印度圣山，拉玛那常年驻锡之地' },
  ],
  'awatuotazhige': [
    { char: '达塔特雷亚', pinyin: 'dá tǎ tè léi yà', meaning: '吠陀神话中的智者，《阿瓦陀塔之歌》托名作者' },
    { char: '阿瓦陀塔', pinyin: 'ā wǎ tuó tǎ', meaning: '彻底摆脱一切世俗与宗教羁绊的极净游方智者' },
    { char: '非二元', pinyin: 'fēi èr yuán', meaning: '不落能所、主体与客体对立的绝待一体实相' },
  ],
  'ashitawakela': [
    { char: '阿什塔瓦克拉', pinyin: 'ā shí tǎ wǎ kè lā', meaning: '意为八处弯曲，印度古代著名非二元哲人' },
    { char: '王者之智', pinyin: 'wáng zhě zhī zhì', meaning: '向遮那迦国王传授的无上自性解脱法要' },
    { char: '见者', pinyin: 'jiàn zhě', meaning: '能知一切经验而自身不被经验所染的纯然觉知' },
  ],
  'baifamingmenlun': [
    { char: '心王', pinyin: 'xīn wáng', meaning: '八识心体，为精神作用之主导' },
    { char: '心所有法', pinyin: 'xīn suǒ yǒu fǎ', meaning: '从属于心王生起的五十一相应用（心所）' },
    { char: '心不相应行', pinyin: 'xīn bù xiāng yìng xíng', meaning: '非物质亦非精神的假立分位（二十四种）' },
    { char: '遍行', pinyin: 'biàn xíng', meaning: '遍一切心、一切地、一切时的五种基本心所' },
  ],
  'weishisanshilunsong': [
    { char: '异熟', pinyin: 'yì shú', meaning: '由善恶因所感召的非善非恶之果报（指阿赖耶识）' },
    { char: '思量', pinyin: 'sī liáng', meaning: '恒审思量我相，第七末那识之根本特质' },
    { char: '了境', pinyin: 'liǎo jìng', meaning: '前六识了别外界显现之境界相' },
    { char: '圆成实', pinyin: 'yuán chéng shí', meaning: '圆满、成就、真实的诸法真如法性' },
  ],
  'weishiershilun': [
    { char: '唯识无境', pinyin: 'wéi shí wú jìng', meaning: '唯有内心识体变现，心外并无实有境物' },
    { char: '极微', pinyin: 'jí wēi', meaning: '古代外道与小乘所立之物质最小不可分割单位' },
    { char: '翳眼', pinyin: 'yì yǎn', meaning: '眼睛生翳者妄见空中有发丝，喻识变妄相' },
  ],
  'rujingyulu': [
    { char: '如净', pinyin: 'rú jìng', meaning: '天童如净禅师，宋代曹洞宗大德，道元之师' },
    { char: '只管打坐', pinyin: 'zhǐ guǎn dǎ zuò', meaning: '不求开悟、不立阶梯，纯然端坐以现成本具佛性' },
    { char: '身心脱落', pinyin: 'shēn xīn tuō luò', meaning: '彻底放下身心我执，自性朗然独耀' },
  ],
  'rujingxuyulu': [
    { char: '虚堂', pinyin: 'xū táng', meaning: '虚堂智愚禅师，宋代名僧' },
    { char: '脱落身心', pinyin: 'tuō luò shēn xīn', meaning: '与身心脱落互文，曹洞宗悟证极则' },
  ],
  'weishanyulu': [
    { char: '灵祐', pinyin: 'líng yòu', meaning: '沩山灵祐禅师，百丈怀海法嗣，沩仰宗开山' },
    { char: '水牯牛', pinyin: 'shuǐ gǔ niú', meaning: '沩山示寂时自道“老僧百年后向山下作一头水牯牛”' },
    { char: '圆相', pinyin: 'yuán xiàng', meaning: '沩仰宗接引学人的九十六十六种圆相符号' },
  ],
  'chengyelun': [
    { char: '审虑思', pinyin: 'shěn lǜ sī', meaning: '起意之前反复思量之心理阶段' },
    { char: '决定思', pinyin: 'jué dìng sī', meaning: '思量之后定夺决断之心理阶段' },
    { char: '动发思', pinyin: 'dòng fā sī', meaning: '发动身体或语言有所造作之业力根本' },
  ],
  'bianzhongbianlun': [
    { char: '虚妄分别', pinyin: 'xū wàng fēn bié', meaning: '凡夫能取与所取的依他起识变功能' },
    { char: '二障', pinyin: 'èr zhàng', meaning: '障碍涅槃之烦恼障与障碍菩提之所知障' },
    { char: '十真实', pinyin: 'shí zhēn shí', meaning: '唯识学层层抉择实相的十个认知层面' },
  ],
  'qiaoyinyulu': [
    { char: '樵隐', pinyin: 'qiáo yǐn', meaning: '元代名僧樵隐悟逸禅师' },
    { char: '拈香', pinyin: 'niān xiāng', meaning: '上堂说法时焚香以敬佛报恩之礼仪' },
  ],
  'shoulengyansanmeijing': [
    { char: '首楞严', pinyin: 'shǒu léng yán', meaning: '梵语Surangama，一切事究竟坚固、健相大定' },
    { char: '坚意', pinyin: 'jiān yì', meaning: '首楞严三昧经中发起提问之大菩萨' },
    { char: '师子座', pinyin: 'shī zǐ zuò', meaning: '佛及大菩萨说法时所坐的高广宝座' },
  ],
  'shedachenglunben': [
    { char: '阿僧伽', pinyin: 'ā sēng qié', meaning: '无著菩萨之梵名音译' },
    { char: '十殊胜', pinyin: 'shí shū shèng', meaning: '《摄大乘论》总摄大乘教理的十种殊胜语' },
    { char: '染污意', pinyin: 'rǎn wù yì', meaning: '特指第七末那识，恒与四根本烦恼相应' },
  ],
  'huanzhu-anqinggui': [
    { char: '明本', pinyin: 'míng běn', meaning: '中峰明本禅师，高峰原妙法嗣，普应国师' },
    { char: '幻住', pinyin: 'huàn zhù', meaning: '中峰明本自号幻住道人，喻世间如幻、任运安住' },
    { char: '日资', pinyin: 'rì zī', meaning: '清规十门之首，一日修行起居之规程与资助' },
  ],
  'jieshenmijing': [
    { char: '阿陀那识', pinyin: 'ā tuó nà shí', meaning: '执持识，阿赖耶识异名，执持诸根与种子不失' },
    { char: '三无性', pinyin: 'sān wú xìng', meaning: '相无自性、生无自性、胜义无自性' },
    { char: '分别瑜伽', pinyin: 'fēn bié yú jiā', meaning: '解深密经第六品，系统宣说大乘止观要诀' },
  ],
  'miyanjing': [
    { char: '地婆诃罗', pinyin: 'dì pó hē luó', meaning: '唐代中印度译经三藏，意译“日照”' },
    { char: '密严', pinyin: 'mì yán', meaning: '超越三界、密不可测、庄严清净之佛国境界' },
    { char: '金指环喻', pinyin: 'jīn zhǐ huán yù', meaning: '如金与指环一体二名，喻如来藏与阿赖耶识体同名异' },
  ],
  'achengjilun': [
    { char: '对法', pinyin: 'duì fǎ', meaning: '阿毘达磨之意译，以无漏慧面对对向诸法真理' },
    { char: '本事分', pinyin: 'běn shì fēn', meaning: '集论前半部，系统归纳整理诸法名相纲目' },
    { char: '决择分', pinyin: 'jué zé fēn', meaning: '集论后半部，对诸法实相深义进行抉择判定' },
  ],
  'baoxinglun': [
    { char: '勒那摩提', pinyin: 'lè nà mó tí', meaning: '北印度三藏法师，后魏时译出《宝性论》' },
    { char: '九种譬喻', pinyin: 'jiǔ zhǒng pì yù', meaning: '宝性论用萎花佛、地中宝等九喻明一切众生皆有如来藏' },
    { char: '客尘', pinyin: 'kè chén', meaning: '烦恼非自性所有，如外来宾客与浮游微尘' },
  ],
  'xutangyulu': [
    { char: '虚堂智愚', pinyin: 'xū táng zhì yú', meaning: '南宋临济宗杨岐派大宗匠，日本临济宗应灯关派远祖' },
    { char: '榾柮', pinyin: 'gǔ duò', meaning: '块状柴木，禅门常借“榾柮火”喻暗中微温、本地风光' },
    { char: '栗棘蓬', pinyin: 'lì jí péng', meaning: '带硬刺之板栗壳，禅门喻吞不进吐不出、绝断情识之公案机锋' },
    { char: '蹲鸱', pinyin: 'dūn chī', meaning: '大芋头，形如蹲伏之鸱鸟，禅僧山居常食之粗羹' },
    { char: '豏', pinyin: 'xiàn', meaning: '糕饼肉馅，语录中“铁酸豏”喻无从下口之险绝公案' },
  ],
};

