export interface LineageNode {
  id: string;
  name: string;
  title: string;
  era: string;
  sect: 'india' | 'main' | 'linji' | 'caodong' | 'weiyang' | 'yunmen' | 'fayan' | 'yangqi' | 'huanglong' | 'other';
  summary: string;
  personId?: string; // 关联 ZEN_PERSONS 的 id
  children?: LineageNode[];
}

export const ZEN_LINEAGE_TREE: LineageNode = {
  id: 'shijiamouni',
  name: '释迦牟尼佛',
  title: '天人之师 · 禅宗本源',
  era: '公元前6世纪',
  sect: 'india',
  summary: '灵山会上，拈花微笑。吾有正法眼藏，涅槃妙心，实相无相，微妙法门，不立文字，教外别传，付嘱摩诃迦叶。',
  children: [
    {
      id: 'jiaye',
      name: '摩诃迦叶',
      title: '西天第一祖',
      era: '古印度',
      sect: 'india',
      personId: 'jiaye',
      summary: '头陀第一，破颜微笑，密受心印。结集三藏，传法阿难。',
      children: [
        {
          id: 'anan',
          name: '阿难尊者',
          title: '西天第二祖',
          era: '古印度',
          sect: 'india',
          personId: 'anan',
          summary: '多闻第一，迦叶唤‘倒却门前刹竿著’，阿难大悟，受付法眼。',
          children: [
            {
              id: 'shangnawaxiu',
              name: '商那和修',
              title: '西天第三祖',
              era: '古印度',
              sect: 'india',
              summary: '于深山得道，传法优婆毱多。',
              children: [
                {
                  id: 'youpojudo',
                  name: '优婆毱多',
                  title: '西天第四祖',
                  era: '古印度',
                  sect: 'india',
                  summary: '化度无量众生，筹室堆满，称为无相佛。',
                  children: [
                    {
                      id: 'tiduojia',
                      name: '提多迦',
                      title: '西天第五祖',
                      era: '古印度',
                      sect: 'india',
                      summary: '本名香姓，初生时父梦金日从屋出，遂出家成道。',
                      children: [
                        {
                          id: 'longshu',
                          name: '龙树菩萨',
                          title: '西天第十四祖 · 八宗共祖',
                          era: '约2-3世纪',
                          sect: 'india',
                          personId: 'nagarjuna',
                          summary: '入龙宫开铁塔，造《中论》《十二门论》《大智度论》，阐明缘起性空、八不中道。',
                          children: [
                            {
                              id: 'ti-po',
                              name: '迦那提婆',
                              title: '西天第十五祖',
                              era: '约3世纪',
                              sect: 'india',
                              personId: 'ti-po',
                              summary: '以破邪显正为宗，辩才无碍，造《百论》《四百论》。',
                              children: [
                                {
                                  id: 'banruoduoluo',
                                  name: '般若多罗',
                                  title: '西天第二十七祖',
                                  era: '5世纪',
                                  sect: 'india',
                                  summary: '付法于达摩：‘汝于震旦，有大因缘，莫急往，听吾偈言。’',
                                  children: [
                                    {
                                      id: 'bodhidharma',
                                      name: '菩提达摩',
                                      title: '西天二十八祖 · 东土初祖',
                                      era: '约483-536',
                                      sect: 'main',
                                      personId: 'bodhidharma',
                                      summary: '航海东来，面壁九年，二入四行，传《楞伽经》印心，开中土禅宗万古法脉。',
                                      children: [
                                        {
                                          id: 'huike',
                                          name: '二祖慧可',
                                          title: '东土第二祖',
                                          era: '487-593',
                                          sect: 'main',
                                          personId: 'huike',
                                          summary: '立雪断臂求法：‘我心未宁，乞师与安。’达摩曰：‘将心来，与汝安！’师曰：‘觅心了不可得。’达摩曰：‘我与汝安心竟。’',
                                          children: [
                                            {
                                              id: 'sengcan',
                                              name: '三祖僧璨',
                                              title: '东土第三祖',
                                              era: '约?-606',
                                              sect: 'main',
                                              personId: 'sengcan',
                                              summary: '著《信心铭》：‘至道无难，唯嫌挑选。但莫憎爱，洞然明白。’绝能所、破二边。',
                                              children: [
                                                {
                                                  id: 'daoxin',
                                                  name: '四祖道信',
                                                  title: '东土第四祖',
                                                  era: '580-651',
                                                  sect: 'main',
                                                  personId: 'daoxin',
                                                  summary: '开创黄梅双峰山定居道场，倡导‘农禅并重’、‘入道安心方便法门’。',
                                                  children: [
                                                    {
                                                      id: 'niutou-farong',
                                                      name: '牛头法融',
                                                      title: '牛头禅始祖',
                                                      era: '594-657',
                                                      sect: 'other',
                                                      personId: 'niutou-farong',
                                                      summary: '未见四祖时百鸟衔花，既见四祖后百鸟不衔花。忘境忘心，体无所得。',
                                                    },
                                                    {
                                                      id: 'hongren',
                                                      name: '五祖弘忍',
                                                      title: '东土第五祖',
                                                      era: '601-674',
                                                      sect: 'main',
                                                      personId: 'hongren',
                                                      summary: '开创黄梅东山法门，门下龙象辈出。以《金刚经》开引大众明自本心。',
                                                      children: [
                                                        {
                                                          id: 'shenxiu',
                                                          name: '神秀大师',
                                                          title: '北宗禅开山',
                                                          era: '606-706',
                                                          sect: 'other',
                                                          personId: 'shenxiu',
                                                          summary: '‘身是菩提树，心如明镜台。时时勤拂拭，莫使惹尘埃。’两京法主，三帝国师，主渐悟。',
                                                        },
                                                        {
                                                          id: 'huineng',
                                                          name: '六祖惠能',
                                                          title: '东土第六祖 · 曹溪顿教',
                                                          era: '638-713',
                                                          sect: 'main',
                                                          personId: 'huineng',
                                                          summary: '‘菩提本无树，明镜亦非台。本来无一物，何处惹尘埃。’听金刚经‘应无所住而生其心’大彻大悟，传《坛经》。',
                                                          children: [
                                                            {
                                                              id: 'nanyang-huizhong',
                                                              name: '南阳慧忠',
                                                              title: '唐肃宗代宗国师',
                                                              era: '675-775',
                                                              sect: 'other',
                                                              personId: 'nanyang-huizhong',
                                                              summary: '示无缝塔，问答三唤侍者，显法身无相常住不灭。',
                                                            },
                                                            {
                                                              id: 'yongjia',
                                                              name: '永嘉玄觉',
                                                              title: '一宿觉 · 真觉大师',
                                                              era: '665-713',
                                                              sect: 'other',
                                                              personId: 'yongjia',
                                                              summary: '著《证道歌》：‘绝学无为闲道人，不除妄想不求真。无明实性即佛性，幻化空身即法身。’',
                                                            },
                                                            {
                                                              id: 'shenhui',
                                                              name: '荷泽神会',
                                                              title: '荷泽宗开山',
                                                              era: '684-758',
                                                              sect: 'other',
                                                              personId: 'shenhui',
                                                              summary: '滑台大云寺确立曹溪顿教正统，著《显宗记》：‘知之一字，众妙之门。’',
                                                            },
                                                            {
                                                              id: 'huairang',
                                                              name: '南岳怀让',
                                                              title: '南岳系开山 · 马祖之师',
                                                              era: '677-744',
                                                              sect: 'linji',
                                                              personId: 'huairang',
                                                              summary: '磨砖作镜：‘磨砖既不成镜，坐禅岂得成佛？’修证即不无，染污即不得。',
                                                              children: [
                                                                {
                                                                  id: 'mazu',
                                                                  name: '马祖道一',
                                                                  title: '洪州宗主 · 江西马祖',
                                                                  era: '709-788',
                                                                  sect: 'linji',
                                                                  personId: 'mazu',
                                                                  summary: '‘即心即佛’、‘非心非佛’、‘平常心是道’。大机大用，喝雷棒霹，开创丛林禅风盛世。',
                                                                  children: [
                                                                    {
                                                                      id: 'baizhang',
                                                                      name: '百丈怀海',
                                                                      title: '百丈清规立制者',
                                                                      era: '749-814',
                                                                      sect: 'linji',
                                                                      personId: 'baizhang',
                                                                      summary: '立禅门清规，倡‘一日不作，一日不食’。野狐公案：‘不昧因果’。',
                                                                      children: [
                                                                        {
                                                                          id: 'huangbo',
                                                                          name: '黄檗希运',
                                                                          title: '传心法要大师',
                                                                          era: '?-850',
                                                                          sect: 'linji',
                                                                          personId: 'huangbo',
                                                                          summary: '传裴休《传心法要》：‘唯此一心，即是佛。心外无物，即心是道。’大机大用，打临济三顿六十棒。',
                                                                          children: [
                                                                            {
                                                                              id: 'linji',
                                                                              name: '临济义玄',
                                                                              title: '临济宗开山始祖',
                                                                              era: '?-866',
                                                                              sect: 'linji',
                                                                              personId: 'linji',
                                                                              summary: '立临济喝、三玄三要、四料简、四宾主、四照用。‘无依道人’、‘随处作主，立处皆真’。宗风峻烈勇猛。',
                                                                              children: [
                                                                                {
                                                                                  id: 'shishuang-chuyuan',
                                                                                  name: '石霜楚圆',
                                                                                  title: '慈明禅师 · 临济中兴',
                                                                                  era: '986-1039',
                                                                                  sect: 'linji',
                                                                                  summary: '刺股夜参，机辩无碍。门下分出杨岐、黄龙二大派，形成‘五家七宗’。',
                                                                                  children: [
                                                                                    {
                                                                                      id: 'yangqi-fanghui',
                                                                                      name: '杨岐方会',
                                                                                      title: '杨岐派开山',
                                                                                      era: '992-1049',
                                                                                      sect: 'yangqi',
                                                                                      personId: 'yangqi-fanghui',
                                                                                      summary: '三脚驴子弄蹄行。宗风明快严谨，大畅宗乘，日后成为临济正宗代表。',
                                                                                      children: [
                                                                                        {
                                                                                          id: 'yuanwu-keqin',
                                                                                          name: '圆悟克勤',
                                                                                          title: '佛果禅师 · 碧岩录评唱',
                                                                                          era: '1063-1135',
                                                                                          sect: 'yangqi',
                                                                                          personId: 'yuanwu-keqin',
                                                                                          summary: '于雪窦重显百则颂古上作评唱，著《碧岩录》，被尊为‘宗门第一书’。',
                                                                                          children: [
                                                                                            {
                                                                                              id: 'dahui-zonggao',
                                                                                              name: '大慧宗杲',
                                                                                              title: '大慧普觉 · 看话禅集大成者',
                                                                                              era: '1089-1163',
                                                                                              sect: 'yangqi',
                                                                                              personId: 'dahui-zonggao',
                                                                                              summary: '力主看话头（参赵州‘无’字），破情识断葛藤，与宏智正觉默照禅相映生辉。',
                                                                                            },
                                                                                          ],
                                                                                        },
                                                                                      ],
                                                                                    },
                                                                                    {
                                                                                      id: 'huanglong-huinan',
                                                                                      name: '黄龙慧南',
                                                                                      title: '黄龙派开山',
                                                                                      era: '1002-1069',
                                                                                      sect: 'huanglong',
                                                                                      personId: 'huanglong-huinan',
                                                                                      summary: '立‘黄龙三关’（生缘、佛手、驴脚），验人极深，宗风盛极一时。',
                                                                                    },
                                                                                  ],
                                                                                },
                                                                              ],
                                                                            },
                                                                          ],
                                                                        },
                                                                        {
                                                                          id: 'weishan-lingyou',
                                                                          name: '沩山灵祐',
                                                                          title: '沩仰宗开山',
                                                                          era: '771-853',
                                                                          sect: 'weiyang',
                                                                          personId: 'weishan-lingyou',
                                                                          summary: '踢倒净瓶出任沩山开山，著《沩山警策》。宗风温良谨肃，圆相暗契。',
                                                                          children: [
                                                                            {
                                                                              id: 'yangshan-huiji',
                                                                              name: '仰山慧寂',
                                                                              title: '小释迦 · 沩仰宗立宗人',
                                                                              era: '807-883',
                                                                              sect: 'weiyang',
                                                                              personId: 'yangshan-huiji',
                                                                              summary: '立九十六种圆相接引学者，师资互酬，父子一家，开成沩仰宗法脉。',
                                                                            },
                                                                          ],
                                                                        },
                                                                      ],
                                                                    },
                                                                    {
                                                                      id: 'nanquan-puyuan',
                                                                      name: '南泉普愿',
                                                                      title: '南泉大师',
                                                                      era: '748-834',
                                                                      sect: 'linji',
                                                                      personId: 'nanquan-puyuan',
                                                                      summary: '三十年不下南泉。‘王老师要斩猫儿’、‘平常心是道’机锋大振。',
                                                                      children: [
                                                                        {
                                                                          id: 'zhaozhou',
                                                                          name: '赵州从谂',
                                                                          title: '赵州古佛',
                                                                          era: '778-897',
                                                                          sect: 'linji',
                                                                          personId: 'zhaozhou',
                                                                          summary: '活到一百二十岁，行脚八十方知歇。‘狗子无佛性’、‘吃茶去’、‘庭前柏树子’。古佛宗风。',
                                                                        },
                                                                      ],
                                                                    },
                                                                    {
                                                                      id: 'dazhu-huihai',
                                                                      name: '大珠慧海',
                                                                      title: '顿悟入道要门论作者',
                                                                      era: '唐代',
                                                                      sect: 'linji',
                                                                      personId: 'dazhu-huihai',
                                                                      summary: '马祖叹曰：‘越州有大珠，圆明光透，自在无碍。’著《顿悟入道要门论》。',
                                                                    },
                                                                  ],
                                                                },
                                                              ],
                                                            },
                                                            {
                                                              id: 'xingsi',
                                                              name: '青原行思',
                                                              title: '青原系开山 · 石头之师',
                                                              era: '671-740',
                                                              sect: 'caodong',
                                                              personId: 'xingsi',
                                                              summary: '‘圣谛亦不为，何阶级之有！’与南岳怀让并称曹溪二大渊薮。',
                                                              children: [
                                                                {
                                                                  id: 'shitou',
                                                                  name: '石头希迁',
                                                                  title: '石头和尚 · 参同契作者',
                                                                  era: '700-790',
                                                                  sect: 'caodong',
                                                                  personId: 'shitou',
                                                                  summary: '著《参同契》《草庵歌》，明回互不回互、理事相摄之旨。‘江西主马祖，湖南主石头。’',
                                                                  children: [
                                                                    {
                                                                      id: 'yaoshan-weiyan',
                                                                      name: '药山惟俨',
                                                                      title: '药山和尚',
                                                                      era: '745-828',
                                                                      sect: 'caodong',
                                                                      personId: 'yaoshan-weiyan',
                                                                      summary: '‘思量个不思量底。’如何思量？‘非思量！’留李翱问道名公案：‘云在青天水在瓶’。',
                                                                      children: [
                                                                        {
                                                                          id: 'yunyan-tancheng',
                                                                          name: '云岩昙晟',
                                                                          title: '云岩禅师',
                                                                          era: '782-841',
                                                                          sect: 'caodong',
                                                                          personId: 'yunyan-tancheng',
                                                                          summary: '传法洞山：‘即此便是，通身是眼。’悟无情说法公案。',
                                                                          children: [
                                                                            {
                                                                              id: 'dongshan',
                                                                              name: '洞山良价',
                                                                              title: '曹洞宗开山祖师',
                                                                              era: '807-869',
                                                                              sect: 'caodong',
                                                                              personId: 'dongshan',
                                                                              summary: '作《宝镜三昧歌》《新丰吟》，立‘五位君臣’。微细推究，绵密回互。',
                                                                              children: [
                                                                                {
                                                                                  id: 'caoshan-benji',
                                                                                  name: '曹山本寂',
                                                                                  title: '曹洞宗立宗人',
                                                                                  era: '840-901',
                                                                                  sect: 'caodong',
                                                                                  personId: 'caoshan-benji',
                                                                                  summary: '与洞山并称‘曹洞宗’，精阐五位君臣，宗风绵密严谨，如水赴海。',
                                                                                },
                                                                                {
                                                                                  id: 'hongzhi-zhengjue',
                                                                                  name: '宏智正觉',
                                                                                  title: '默照禅集大成者',
                                                                                  era: '1091-1157',
                                                                                  sect: 'caodong',
                                                                                  personId: 'hongzhi-zhengjue',
                                                                                  summary: '著《默照铭》《坐禅箴》：‘默照理圆，莲开梦觉。’主默默静坐、自性圆照。',
                                                                                },
                                                                                {
                                                                                  id: 'rujing',
                                                                                  name: '天童如净',
                                                                                  title: '天童如净禅师',
                                                                                  era: '1163-1228',
                                                                                  sect: 'caodong',
                                                                                  personId: 'rujing',
                                                                                  summary: '倡‘身心脱落，只管打坐’。传法日本道元禅师，开创日本曹洞宗。',
                                                                                },
                                                                              ],
                                                                            },
                                                                          ],
                                                                        },
                                                                      ],
                                                                    },
                                                                    {
                                                                      id: 'danxia-tianran',
                                                                      name: '丹霞天然',
                                                                      title: '丹霞禅师',
                                                                      era: '739-824',
                                                                      sect: 'caodong',
                                                                      personId: 'danxia-tianran',
                                                                      summary: '冬日天寒，于慧林寺烧木佛御寒取暖：‘吾烧取舍利。’破除执相，直指法身无碍。',
                                                                    },
                                                                    {
                                                                      id: 'tianhuang-daowu',
                                                                      name: '天皇道悟',
                                                                      title: '荆南道悟',
                                                                      era: '748-807',
                                                                      sect: 'yunmen',
                                                                      summary: '石头门下龙象，后出云门、法眼两宗，为下衍三家之总源。',
                                                                      children: [
                                                                        {
                                                                          id: 'longtan-chongxin',
                                                                          name: '龙潭崇信',
                                                                          title: '龙潭大师',
                                                                          era: '唐代',
                                                                          sect: 'yunmen',
                                                                          summary: '吹灭纸烛，德山宣鉴当下大悟，点破夜暗本来光明。',
                                                                          children: [
                                                                            {
                                                                              id: 'deshan-xuanjian',
                                                                              name: '德山宣鉴',
                                                                              title: '德山棒 · 棒喝齐驱',
                                                                              era: '782-865',
                                                                              sect: 'yunmen',
                                                                              personId: 'deshan-xuanjian',
                                                                              summary: '‘道得也三十棒，道不得也三十棒！’与临济喝并称‘德山棒、临济喝’，扫荡一切解会葛藤。',
                                                                              children: [
                                                                                {
                                                                                  id: 'xuefeng-yicun',
                                                                                  name: '雪峰义存',
                                                                                  title: '雪峰大师 · 门开两宗',
                                                                                  era: '822-908',
                                                                                  sect: 'yunmen',
                                                                                  personId: 'xuefeng-yicun',
                                                                                  summary: '鳖山成道，坐拥千僧，门下出云门文偃、玄沙师备二大圣，开云门、法眼二宗。',
                                                                                  children: [
                                                                                    {
                                                                                      id: 'yunmen',
                                                                                      name: '云门文偃',
                                                                                      title: '云门宗开山祖师',
                                                                                      era: '864-949',
                                                                                      sect: 'yunmen',
                                                                                      personId: 'yunmen',
                                                                                      summary: '立‘云门三句’（涵盖乾坤、截断众流、随波逐浪）。一字关、顾鉴咦。孤危耸拔。',
                                                                                      children: [
                                                                                        {
                                                                                          id: 'xuedou-zhongxian',
                                                                                          name: '雪窦重显',
                                                                                          title: '明觉禅师 · 颂古百则作者',
                                                                                          era: '980-1052',
                                                                                          sect: 'yunmen',
                                                                                          personId: 'xuedou-zhongxian',
                                                                                          summary: '云门宗巨擘，文辞华茂，著《颂古百则》，后成为《碧岩录》之骨髓。',
                                                                                        },
                                                                                      ],
                                                                                    },
                                                                                    {
                                                                                      id: 'xuansha-shibei',
                                                                                      name: '玄沙师备',
                                                                                      title: '宗一禅师',
                                                                                      era: '835-908',
                                                                                      sect: 'fayan',
                                                                                      summary: '踢着石指血流而大悟：‘尽十方世界，是一颗圆成明珠！’',
                                                                                      children: [
                                                                                        {
                                                                                          id: 'luohan-guichen',
                                                                                          name: '罗汉桂琛',
                                                                                          title: '地藏桂琛',
                                                                                          era: '867-928',
                                                                                          sect: 'fayan',
                                                                                          summary: '指片石问法眼：‘此石在心内，在心外？’答：‘在心内。’琛曰：‘行脚人有甚因缘，安片石在心头？’法眼大悟。',
                                                                                          children: [
                                                                                            {
                                                                                              id: 'fayan-wenyi',
                                                                                              name: '法眼文益',
                                                                                              title: '法眼宗开山祖师',
                                                                                              era: '885-958',
                                                                                              sect: 'fayan',
                                                                                              personId: 'fayan-wenyi',
                                                                                              summary: '立‘六相圆融’、‘三界唯心，万法唯识’。著《宗门十规论》，整肃禅风，一切现成。',
                                                                                              children: [
                                                                                                {
                                                                                                  id: 'yongming-yanshou',
                                                                                                  name: '永明延寿',
                                                                                                  title: '宗镜大宗师 · 禅净双修',
                                                                                                  era: '904-975',
                                                                                                  sect: 'fayan',
                                                                                                  personId: 'yongming-yanshou',
                                                                                                  summary: '著百卷《宗镜录》《万善同归集》，融通禅宗、天台、华严、唯识与净土，大成佛法枢机。',
                                                                                                },
                                                                                              ],
                                                                                            },
                                                                                          ],
                                                                                        },
                                                                                      ],
                                                                                    },
                                                                                  ],
                                                                                },
                                                                              ],
                                                                            },
                                                                          ],
                                                                        },
                                                                      ],
                                                                    },
                                                                  ],
                                                                },
                                                              ],
                                                            },
                                                          ],
                                                        },
                                                      ],
                                                    },
                                                  ],
                                                },
                                              ],
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const SECT_META: Record<string, { label: string; color: string; bgClass: string; textClass: string; borderClass: string; desc: string }> = {
  all: {
    label: '全宗源流',
    color: '#B45309',
    bgClass: 'bg-amber-100/80',
    textClass: 'text-amber-950',
    borderClass: 'border-amber-300',
    desc: '从灵山拈花微笑至五家七宗全景世系',
  },
  india: {
    label: '西天源流',
    color: '#6366F1',
    bgClass: 'bg-indigo-100/80',
    textClass: 'text-indigo-950',
    borderClass: 'border-indigo-300',
    desc: '西天二十八祖 · 正法眼藏以心印心',
  },
  main: {
    label: '东土六祖',
    color: '#D97706',
    bgClass: 'bg-amber-100/80',
    textClass: 'text-amber-950',
    borderClass: 'border-amber-300',
    desc: '达摩东来至六祖惠能曹溪顿教主干',
  },
  linji: {
    label: '临济宗',
    color: '#DC2626',
    bgClass: 'bg-red-100/80',
    textClass: 'text-red-950',
    borderClass: 'border-red-300',
    desc: '黄檗临济 · 四宾主三玄要 · 棒喝峻烈',
  },
  yangqi: {
    label: '杨岐派',
    color: '#EA580C',
    bgClass: 'bg-orange-100/80',
    textClass: 'text-orange-950',
    borderClass: 'border-orange-300',
    desc: '临济出杨岐 · 圆悟克勤大慧宗杲看话禅',
  },
  huanglong: {
    label: '黄龙派',
    color: '#CA8A04',
    bgClass: 'bg-yellow-100/80',
    textClass: 'text-yellow-950',
    borderClass: 'border-yellow-300',
    desc: '临济出黄龙 · 黄龙三关 · 宗风横绝',
  },
  caodong: {
    label: '曹洞宗',
    color: '#059669',
    bgClass: 'bg-emerald-100/80',
    textClass: 'text-emerald-950',
    borderClass: 'border-emerald-300',
    desc: '青原石头洞山 · 宝镜三昧五位君臣默照禅',
  },
  weiyang: {
    label: '沩仰宗',
    color: '#7C3AED',
    bgClass: 'bg-purple-100/80',
    textClass: 'text-purple-950',
    borderClass: 'border-purple-300',
    desc: '沩山仰山 · 九十六种圆相 · 父子一家',
  },
  yunmen: {
    label: '云门宗',
    color: '#0284C7',
    bgClass: 'bg-sky-100/80',
    textClass: 'text-sky-950',
    borderClass: 'border-sky-300',
    desc: '德山雪峰云门 · 云门三句一字关 · 险峻绝伦',
  },
  fayan: {
    label: '法眼宗',
    color: '#92400E',
    bgClass: 'bg-stone-200/80',
    textClass: 'text-stone-900',
    borderClass: 'border-stone-300',
    desc: '玄沙地藏法眼 · 六相圆融 · 宗镜大成',
  },
  other: {
    label: '宗门诸老',
    color: '#64748B',
    bgClass: 'bg-slate-100/80',
    textClass: 'text-slate-900',
    borderClass: 'border-slate-300',
    desc: '牛头禅、北宗神秀、南阳国师等旁系龙象',
  },
};
